// Generated from WebsiteContent; run scripts/build_public_content_fixtures.py.
export type Demonstration = {
  disclosure: string;
  organization_label: string;
  workers?: Array<Entry>;
  jobs?: Array<Entry>;
  approvals?: Array<Entry>;
  run_steps?: Array<Entry>;
};
export type Entry = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
};
export type HeroScene = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
  scene: "autonomy" | "control" | "oversight";
  word: string;
};
export type JourneyChapter = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
  phase: "defined" | "policy" | "approval" | "recorded";
};
export type Link = {
  label: string;
  destination: string;
  section_id?: string | null;
  selected_record_id?: string | null;
};
export type MediaReference = {
  asset_id: string;
  role: "image" | "logo" | "video" | "model" | "poster" | "caption" | "download" | "rendition";
  fallback_asset_id?: string | null;
  poster_asset_id?: string | null;
  caption_asset_ids?: Array<string>;
  duration_seconds?: number | null;
  rendition_asset_ids?: Array<string>;
};
export type OperatingArea = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
  area: "workers" | "jobs" | "governance" | "supervision";
  path: Array<string>;
  signal: string;
};
export type Plan = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
  plan_key: string;
  price_minor: number;
  currency: string;
  billing_period: "month" | "year";
  availability: "free_signup" | "unavailable" | "contact";
  worker_capacity_display: number;
};
export type Section = {
  id: string;
  eyebrow?: string;
  heading: string;
  paragraphs?: Array<string>;
  points?: Array<string>;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
};
export type SecurityDecision = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
  decision: "allow" | "review" | "deny";
  note: string;
};
export type Solution = {
  id: string;
  label: string;
  heading?: string;
  description?: string;
  summary?: string;
  detail?: string;
  status_label?: string;
  category?: string;
  points?: Array<string>;
  icon?: "workers" | "jobs" | "governance" | "supervision" | "operations" | "research" | "support" | "sales" | "marketing" | "engineering" | "github" | "gmail" | "slack" | "drive" | "calendar" | "browser" | "document" | "shield" | "check" | "clock" | null;
  links?: Array<Link>;
  media?: Array<MediaReference>;
  record_ids?: Array<string>;
  worker: string;
  job: string;
  tools: Array<string>;
  output: string;
};
export type WebsiteContent = {
  contract?: "audoryn.public.v1";
  profile: "home" | "product" | "solutions" | "security" | "pricing" | "resources" | "company" | "privacy" | "terms" | "branding" | "article" | "news" | "guide" | "research" | "changelog" | "resource" | "case_study" | "feature" | "integration" | "customer" | "testimonial" | "author" | "category" | "tag" | "faq" | "announcement";
  sections?: Array<Section>;
  entries?: Array<Entry>;
  hero_scenes?: Array<HeroScene>;
  journey?: Array<JourneyChapter>;
  operating_areas?: Array<OperatingArea>;
  solutions?: Array<Solution>;
  security_decisions?: Array<SecurityDecision>;
  plans?: Array<Plan>;
  demonstration?: Demonstration | null;
  effective_date?: string | null;
  document_version?: string | null;
};
