import { api } from '@appdeploy/client';
import type { CapabilityRisk } from './capabilityApi';
import type { PolicyOutcome } from './policyApi';
import type { ApiVersion } from './systemApi';
export type ActionStatus='processing'|'executed'|'blocked'|'held'|'failed';
export interface ActionRecord{id:string;organizationId:string;agent:{id:string;name:string;credentialFingerprint:string};request:{resourceId:string;resourceName:string|null;integrationId:string|null;provider:'github'|null;scope:string;action:string|null;target:string|null;risk:CapabilityRisk|null;providerOperation:string|null};status:ActionStatus;correlationId:string;idempotencyHash:string;policy:{outcome:PolicyOutcome;reason:string;winningPolicy:{id:string;name:string;effect:string;priority:number;revision:number}|null;matchedPolicies:Array<{id:string;name:string;effect:string;priority:number;revision:number}>};result:{providerOperation:string;summary:string;executedAt:string;providerRequestId:string|null;data:unknown}|null;error:string|null;requestedAt:string;completedAt:string|null}
interface V2Action{identity:{id:string;status:ActionStatus;correlationId:string;requestedAt:string;completedAt:string|null};actor:ActionRecord['agent'];request:ActionRecord['request'];authorization:ActionRecord['policy'];execution:{result:ActionRecord['result'];error:string|null;idempotencyHash:string};organizationId:string}
function normalize(item:V2Action):ActionRecord{return{id:item.identity.id,status:item.identity.status,correlationId:item.identity.correlationId,requestedAt:item.identity.requestedAt,completedAt:item.identity.completedAt,agent:item.actor,request:item.request,policy:item.authorization,result:item.execution.result,error:item.execution.error,idempotencyHash:item.execution.idempotencyHash,organizationId:item.organizationId}}
export async function listActions(version:ApiVersion,organizationId:string):Promise<ActionRecord[]>{const response=await api.get(`/api/${version}/organizations/${organizationId}/actions`);return version==='v1'?response.data.actions as ActionRecord[]:(response.data.items as V2Action[]).map(normalize)}
export async function runGatewayTest(version:ApiVersion,organizationId:string,input:{agentId:string;credential:string;resourceId:string;scope:string;idempotencyKey:string;correlationId?:string}):Promise<ActionRecord>{const response=await api.post(`/api/${version}/organizations/${organizationId}/action-gateway/tests`,input);return version==='v1'?response.data.action as ActionRecord:normalize(response.data.data.action as V2Action)}
