import { api, notifications } from '@appdeploy/client';
import type { CapabilityRisk } from './capabilityApi';
import type { PolicyOutcome } from './policyApi';
import type { ApiVersion } from './systemApi';
export type ApprovalStatus='pending'|'approved'|'rejected';
export interface ApprovalRecord{id:string;organizationId:string;actionId:string;agentId:string;agentName:string;request:{resourceId:string;resourceName:string;integrationId:string;scope:string;action:string;target:string;risk:CapabilityRisk;providerOperation:string};policy:{outcome:PolicyOutcome;reason:string;winningPolicy:{id:string;name:string;effect:string;priority:number;revision:number}|null;matchedPolicies:Array<{id:string;name:string;effect:string;priority:number;revision:number}>};status:ApprovalStatus;decision:{decision:'approve'|'reject';note:string;decidedBy:string;decidedAt:string}|null;execution:{state:'not_started'|'executed'|'blocked'|'failed';actionStatus:string|null;summary:string|null;completedAt:string|null;reauthorization:ApprovalRecord['policy']|null};notification:{state:'not_attempted'|'sent'|'unavailable'|'failed';attemptedAt:string|null;sent:number;failed:number};requestedAt:string}
interface V2Approval{identity:{id:string;status:ApprovalStatus;requestedAt:string};action:{id:string;agent:{id:string;name:string};request:ApprovalRecord['request'];policy:ApprovalRecord['policy']};decision:ApprovalRecord['decision'];execution:ApprovalRecord['execution'];notification:ApprovalRecord['notification'];organizationId:string}
function normalize(item:V2Approval):ApprovalRecord{return{id:item.identity.id,status:item.identity.status,requestedAt:item.identity.requestedAt,actionId:item.action.id,agentId:item.action.agent.id,agentName:item.action.agent.name,request:item.action.request,policy:item.action.policy,decision:item.decision,execution:item.execution,notification:item.notification,organizationId:item.organizationId}}
export async function listApprovals(version:ApiVersion,organizationId:string):Promise<ApprovalRecord[]>{const response=await api.get(`/api/${version}/organizations/${organizationId}/approvals`);return version==='v1'?response.data.approvals as ApprovalRecord[]:(response.data.items as V2Approval[]).map(normalize)}
export async function decideApproval(version:ApiVersion,organizationId:string,approvalId:string,decision:'approve'|'reject',note:string):Promise<ApprovalRecord>{const response=await api.post(`/api/${version}/organizations/${organizationId}/approvals/${approvalId}/decision`,{decision,note});return version==='v1'?response.data.approval as ApprovalRecord:normalize(response.data.data.approval as V2Approval)}
export type ApprovalNotificationState=Awaited<ReturnType<typeof notifications.getEnvironment>>;
export async function getApprovalNotificationState(){return notifications.getEnvironment()}
export async function enableApprovalNotifications(){await notifications.subscribe();return notifications.getEnvironment()}
export function onApprovalNotification(callback:()=>void){return notifications.onMessage((payload)=>{if('data' in payload&&payload.data.kind==='approval')callback()})}
