import { api } from '@appdeploy/client';
import type { ApiVersion } from './systemApi';
export type CapabilityRisk = 'low' | 'medium' | 'high' | 'critical';
export interface CapabilityAction { id: string; action: string; target: string; providerOperation: string; scope: string; description: string; risk: CapabilityRisk; }
export interface CapabilityResource { id: string; organizationId: string; integrationId: string; provider: 'github'; type: string; key: string; displayName: string; status: 'connected' | 'degraded'; metadata: Record<string, string | number | boolean | null>; actions: CapabilityAction[]; scopes: string[]; }
export interface CapabilityCatalog { resources: CapabilityResource[]; scopes: string[]; summary: { resources: number; actions: number; scopes: number }; }
export interface AgentCapabilityProfile { agent: { id: string; name: string; status: string }; declaredScopes: string[]; activeScopes: string[]; staleScopes: string[]; updatedAt: string | null; updatedBy: string | null; authorization: { state: 'contextual'; reason: string }; }
interface V2Resource { identity: { id: string; type: string; provider: 'github'; status: 'connected' | 'degraded' }; source: { organizationId: string; integrationId: string; key: string; displayName: string; metadata: Record<string, string | number | boolean | null> }; capabilities: { actions: CapabilityAction[]; scopes: string[] } }
function normalizeCatalogV2(data: { resources: V2Resource[]; summary: CapabilityCatalog['summary'] }): CapabilityCatalog { const resources = data.resources.map((item) => ({ ...item.identity, ...item.source, actions: item.capabilities.actions, scopes: item.capabilities.scopes })); return { resources, scopes: Array.from(new Set(resources.flatMap((resource) => resource.scopes))).sort(), summary: data.summary }; }
function normalizeProfileV2(data: { agent: AgentCapabilityProfile['agent']; declaration: { scopes: string[]; activeScopes: string[]; staleScopes: string[]; updatedAt: string | null; updatedBy: string | null }; enforcement: AgentCapabilityProfile['authorization'] }): AgentCapabilityProfile { return { agent: data.agent, declaredScopes: data.declaration.scopes, activeScopes: data.declaration.activeScopes, staleScopes: data.declaration.staleScopes, updatedAt: data.declaration.updatedAt, updatedBy: data.declaration.updatedBy, authorization: data.enforcement }; }
export async function listCapabilityCatalog(version: ApiVersion, organizationId: string): Promise<CapabilityCatalog> { const response = await api.get(`/api/${version}/organizations/${organizationId}/capabilities`); return version === 'v1' ? response.data as CapabilityCatalog : normalizeCatalogV2(response.data.data); }
export async function getAgentCapabilityProfile(version: ApiVersion, organizationId: string, agentId: string): Promise<AgentCapabilityProfile> { const response = await api.get(`/api/${version}/organizations/${organizationId}/agents/${agentId}/capabilities`); return version === 'v1' ? response.data.profile as AgentCapabilityProfile : normalizeProfileV2(response.data.data); }
export async function saveAgentCapabilityProfile(version: ApiVersion, organizationId: string, agentId: string, scopes: string[]): Promise<AgentCapabilityProfile> { const response = await api.put(`/api/${version}/organizations/${organizationId}/agents/${agentId}/capabilities`, { scopes }); return version === 'v1' ? response.data.profile as AgentCapabilityProfile : normalizeProfileV2(response.data.data); }
