import { api } from '@appdeploy/client';
import type { ApiVersion } from './systemApi';
export type IntegrationStatus = 'connected' | 'degraded' | 'disconnected';
export interface IntegrationConnection { id: string; organizationId: string; provider: 'github'; displayName: string; resourceKey: string; webUrl: string; metadata: Record<string, string | number | boolean | null>; supportedOperations: string[]; status: IntegrationStatus; credential: { mode: 'none' | 'encrypted_secret'; configured: boolean; fingerprint: string | null }; health: { message: string; lastCheckedAt: string }; createdBy: string; createdAt: string; updatedAt: string; }
export interface IntegrationSecurityStatus { credentialVaultConfigured: boolean; encryption: string; secretSource: string; }
interface V2Integration { identity: { id: string; provider: 'github'; status: IntegrationStatus; createdAt: string; updatedAt: string }; resource: { organizationId: string; displayName: string; resourceKey: string; webUrl: string; metadata: Record<string, string | number | boolean | null> }; boundary: { supportedOperations: string[]; credential: IntegrationConnection['credential'] }; health: IntegrationConnection['health']; ownership: { createdBy: string } }
function normalizeV2(item: V2Integration): IntegrationConnection { return { ...item.identity, ...item.resource, supportedOperations: item.boundary.supportedOperations, credential: item.boundary.credential, health: item.health, createdBy: item.ownership.createdBy }; }
export async function listIntegrations(version: ApiVersion, organizationId: string): Promise<IntegrationConnection[]> { const response = await api.get(`/api/${version}/organizations/${organizationId}/integrations`); if (version === 'v1') return response.data.integrations as IntegrationConnection[]; return (response.data.items as V2Integration[]).map(normalizeV2); }
export async function integrationSecurityStatus(version: ApiVersion, organizationId: string): Promise<IntegrationSecurityStatus> { const response = await api.get(`/api/${version}/organizations/${organizationId}/integrations/security`); return version === 'v1' ? response.data.security as IntegrationSecurityStatus : response.data.data.security as IntegrationSecurityStatus; }
export async function connectGitHub(version: ApiVersion, organizationId: string, repository: string, token: string): Promise<IntegrationConnection> { const response = await api.post(`/api/${version}/organizations/${organizationId}/integrations/github`, { repository, token: token || undefined }); return version === 'v1' ? response.data.integration as IntegrationConnection : normalizeV2(response.data.data.integration as V2Integration); }
export async function checkIntegration(version: ApiVersion, organizationId: string, integrationId: string): Promise<IntegrationConnection> { const response = await api.post(`/api/${version}/organizations/${organizationId}/integrations/${integrationId}/check`); return version === 'v1' ? response.data.integration as IntegrationConnection : normalizeV2(response.data.data.integration as V2Integration); }
export async function disconnectIntegration(version: ApiVersion, organizationId: string, integrationId: string): Promise<IntegrationConnection> { const response = await api.delete(`/api/${version}/organizations/${organizationId}/integrations/${integrationId}`); return version === 'v1' ? response.data.integration as IntegrationConnection : normalizeV2(response.data.data.integration as V2Integration); }
