import { api } from '@appdeploy/client';
import type { ApiVersion } from './systemApi';
export interface PerformanceSummary{workers:number;activeWorkers:number;runs:number;terminalRuns:number;completed:number;failed:number;cancelled:number;successRate:number;failureRate:number;approvalRate:number;blockedActions:number;escalations:number;escalationsPer100Runs:number;incidents:number;incidentsPer100Runs:number;averageRunDurationMs:number;medianRunDurationMs:number}
export interface WorkerPerformance{id:string;name:string;department:string;status:string;supervisorUserId:string;runs:number;completed:number;failed:number;cancelled:number;waitingApproval:number;successRate:number;failureRate:number;approvalRate:number;blockedActions:number;escalations:number;incidents:number;averageRunDurationMs:number;medianRunDurationMs:number}
export interface DepartmentPerformance{name:string;workers:number;runs:number;completed:number;failed:number;cancelled:number;successRate:number;escalations:number;incidents:number}
export interface ToolPerformance{id:string;name:string;provider:string;executed:number;failed:number;blocked:number;held:number;providerAttempts:number;reliabilityRate:number}
export interface TrendPoint{date:string;completed:number;failed:number;cancelled:number}
export interface ActivityItem{id:string;workerId:string;workerName:string;department:string;kind:'run'|'action'|'escalation'|'incident';status:string;label:string;occurredAt:string;correlationId:string|null}
export interface PerformanceWorkspace{generatedAt:string;summary:PerformanceSummary;workers:WorkerPerformance[];departments:DepartmentPerformance[];tools:ToolPerformance[];trends:TrendPoint[];activity:ActivityItem[];window:Record<string,{scanned:number;limit:number;truncated:boolean;matched?:number}>;methodology:{score:string;successRate:string;approvalRate:string;toolReliability:string;escalationRate:string;incidentRate:string;bounded:boolean}}
export async function loadPerformance(version:ApiVersion,organizationId:string):Promise<PerformanceWorkspace>{const response=await api.get(`/api/${version}/organizations/${organizationId}/performance`);if(version==='v1')return response.data as PerformanceWorkspace;const d=response.data.data;return{generatedAt:d.generatedAt,summary:d.overview,workers:d.workforce.workers,departments:d.workforce.departments,tools:d.operations.tools,trends:d.runTrends,activity:d.operations.activity,window:d.windows,methodology:d.methodology}}
