import { api } from '@appdeploy/client';
import type { CapabilityRisk } from './capabilityApi';
import type { ApiVersion } from './systemApi';
import type { RiskAssessment } from './riskApi';
export type PolicyEffect='allow'|'deny'|'require_approval';export type PolicyStatus='enabled'|'disabled';export type PolicyOutcome='ALLOW'|'DENY'|'REQUIRE_APPROVAL';
export interface PolicySelectors{agentIds:string[];resourceIds:string[];actions:string[];scopes:string[];risks:CapabilityRisk[]}
export interface PolicyRecord{id:string;organizationId:string;name:string;description:string;effect:PolicyEffect;priority:number;status:PolicyStatus;selectors:PolicySelectors;revision:number;createdBy:string;createdAt:string;updatedBy:string;updatedAt:string}
export interface PolicyInput{name:string;description:string;effect:PolicyEffect;priority:number;selectors:PolicySelectors}
export interface PolicyDecision{outcome:PolicyOutcome;reason:string;evaluatedAt:string;request:{agentId:string;resourceId:string;scope:string;agentName:string|null;resourceName:string|null;action:string|null;target:string|null;risk:CapabilityRisk|null};preconditions:{agentActive:boolean;resourceLive:boolean;scopeAvailable:boolean;scopeDeclared:boolean};winningPolicy:{id:string;name:string;effect:PolicyEffect;priority:number;revision:number}|null;matchedPolicies:Array<{id:string;name:string;effect:PolicyEffect;priority:number;revision:number}>;riskAssessment:RiskAssessment|null}
interface V2Policy{identity:{id:string;name:string;status:PolicyStatus;revision:number};decision:{effect:PolicyEffect;priority:number};selectors:PolicySelectors;description:string;ownership:{organizationId:string;createdBy:string;updatedBy:string};timestamps:{createdAt:string;updatedAt:string}}
function normalizePolicy(item:V2Policy):PolicyRecord{return{id:item.identity.id,name:item.identity.name,status:item.identity.status,revision:item.identity.revision,effect:item.decision.effect,priority:item.decision.priority,selectors:item.selectors,description:item.description,organizationId:item.ownership.organizationId,createdBy:item.ownership.createdBy,updatedBy:item.ownership.updatedBy,createdAt:item.timestamps.createdAt,updatedAt:item.timestamps.updatedAt}}
function normalizeDecision(data:{decision:{outcome:PolicyOutcome;reason:string;evaluatedAt:string};request:PolicyDecision['request'];riskAssessment:RiskAssessment|null;preconditions:PolicyDecision['preconditions'];resolution:{winningPolicy:PolicyDecision['winningPolicy'];matchedPolicies:PolicyDecision['matchedPolicies']}}):PolicyDecision{return{...data.decision,request:data.request,riskAssessment:data.riskAssessment,preconditions:data.preconditions,winningPolicy:data.resolution.winningPolicy,matchedPolicies:data.resolution.matchedPolicies}}
export async function listPolicies(version:ApiVersion,organizationId:string):Promise<PolicyRecord[]>{const response=await api.get(`/api/${version}/organizations/${organizationId}/policies`);return version==='v1'?response.data.policies as PolicyRecord[]:(response.data.items as V2Policy[]).map(normalizePolicy)}
export async function createPolicy(version:ApiVersion,organizationId:string,input:PolicyInput):Promise<PolicyRecord>{const response=await api.post(`/api/${version}/organizations/${organizationId}/policies`,input);return version==='v1'?response.data.policy as PolicyRecord:normalizePolicy(response.data.data.policy as V2Policy)}
export async function updatePolicy(version:ApiVersion,organizationId:string,policyId:string,input:PolicyInput):Promise<PolicyRecord>{const response=await api.put(`/api/${version}/organizations/${organizationId}/policies/${policyId}`,input);return version==='v1'?response.data.policy as PolicyRecord:normalizePolicy(response.data.data.policy as V2Policy)}
export async function setPolicyStatus(version:ApiVersion,organizationId:string,policyId:string,status:PolicyStatus):Promise<PolicyRecord>{const response=await api.post(`/api/${version}/organizations/${organizationId}/policies/${policyId}/status`,{status});return version==='v1'?response.data.policy as PolicyRecord:normalizePolicy(response.data.data.policy as V2Policy)}
export async function evaluatePolicy(version:ApiVersion,organizationId:string,agentId:string,resourceId:string,scope:string):Promise<PolicyDecision>{const response=await api.post(`/api/${version}/organizations/${organizationId}/policy-evaluations`,{agentId,resourceId,scope});return version==='v1'?response.data.decision as PolicyDecision:normalizeDecision(response.data.data)}
