import { api } from '@appdeploy/client';
import type { CapabilityRisk } from './capabilityApi';
import type { ApiVersion } from './systemApi';
export type RiskSignalCode='burst_activity'|'repeated_blocks'|'repeated_failures'|'approval_pressure'|'history_truncated';
export interface RiskSignal{code:RiskSignalCode;active:boolean;increment:0|1;count:number;threshold:number;windowMinutes:number|null;reason:string}
export interface RiskAssessment{baselineRisk:CapabilityRisk;effectiveRisk:CapabilityRisk;elevationSteps:number;evaluatedAt:string;signals:RiskSignal[];counters:{requests10m:number;blocked30m:number;failed30m:number;approval30m:number};window:{scanned:number;agentMatches:number;limit:number;truncated:boolean};context:{agentId:string;agentName:string;resourceId:string;resourceName:string;scope:string;action:string}}
export interface RiskOverviewItem{actionId:string;correlationId:string;status:string;agent:{id:string;name:string};resource:{id:string;name:string|null};scope:string;assessment:RiskAssessment}
export interface RiskOverview{assessments:RiskOverviewItem[];summary:{assessedActions:number;elevated:number;activeSignalHits:number;highOrCritical:number;byEffectiveRisk:Record<CapabilityRisk,number>;latestAt:string|null};window:{scanned:number;limit:number;truncated:boolean};thresholds:{burst:{count:number;minutes:number};blocks:{count:number;minutes:number};failures:{count:number;minutes:number};approvals:{count:number;minutes:number};truncatedHistoryElevation:boolean}}
interface V2Assessment{context:RiskAssessment['context'];risk:{baseline:CapabilityRisk;effective:CapabilityRisk;elevationSteps:number;evaluatedAt:string};signals:RiskSignal[];counters:RiskAssessment['counters'];window:RiskAssessment['window']}
function normalizeAssessment(item:V2Assessment):RiskAssessment{return{baselineRisk:item.risk.baseline,effectiveRisk:item.risk.effective,elevationSteps:item.risk.elevationSteps,evaluatedAt:item.risk.evaluatedAt,signals:item.signals,counters:item.counters,window:item.window,context:item.context}}
export async function loadRiskOverview(version:ApiVersion,organizationId:string):Promise<RiskOverview>{const response=await api.get(`/api/${version}/organizations/${organizationId}/risk`);if(version==='v1')return response.data as RiskOverview;const data=response.data.data as{items:Array<{identity:{actionId:string;correlationId:string;status:string};actor:{id:string;name:string};resource:{id:string;name:string|null};scope:string;assessment:V2Assessment}>;summary:RiskOverview['summary'];window:RiskOverview['window'];thresholds:RiskOverview['thresholds']};return{assessments:data.items.map((item)=>({actionId:item.identity.actionId,correlationId:item.identity.correlationId,status:item.identity.status,agent:item.actor,resource:item.resource,scope:item.scope,assessment:normalizeAssessment(item.assessment)})),summary:data.summary,window:data.window,thresholds:data.thresholds}}
export async function assessRisk(version:ApiVersion,organizationId:string,input:{agentId:string;resourceId:string;scope:string}):Promise<RiskAssessment>{const response=await api.post(`/api/${version}/organizations/${organizationId}/risk-assessments`,input);return version==='v1'?response.data.assessment as RiskAssessment:normalizeAssessment(response.data.data as V2Assessment)}
