import { db, notifications } from '@appdeploy/sdk';
import { getOrganizationForUser } from './organizations';
import type { CapabilityRisk } from '../integrations/contracts';
import type { PolicyOutcome } from './policies';
import { appendAuditEvent } from './audit';
export type ApprovalStatus = 'pending' | 'approved' | 'rejected';
export type ApprovalDecision = 'approve' | 'reject';
export interface ApprovalPolicySnapshot { outcome: PolicyOutcome; reason: string; winningPolicy: { id: string; name: string; effect: string; priority: number; revision: number } | null; matchedPolicies: Array<{ id: string; name: string; effect: string; priority: number; revision: number }>; }
export interface ApprovalExecution { state: 'not_started' | 'executed' | 'blocked' | 'failed'; actionStatus: string | null; summary: string | null; completedAt: string | null; reauthorization: ApprovalPolicySnapshot | null; }
export interface ApprovalRecord { organizationId: string; actionId: string; agentId: string; agentName: string; correlationId: string; request: { resourceId: string; resourceName: string; integrationId: string; scope: string; action: string; target: string; risk: CapabilityRisk; providerOperation: string }; policy: ApprovalPolicySnapshot; status: ApprovalStatus; decision: { decision: ApprovalDecision; note: string; decidedBy: string; decidedAt: string } | null; execution: ApprovalExecution; notification: { state: 'not_attempted' | 'sent' | 'unavailable' | 'failed'; attemptedAt: string | null; sent: number; failed: number }; requestedAt: string; }
export interface ApprovalEntry { id: string; record: ApprovalRecord; }
function approvalsTable(organizationId: string) { return `approvals:${organizationId}`; }
async function write(entry: ApprovalEntry) { const [updated] = await db.update(approvalsTable(entry.record.organizationId), [{ id: entry.id, record: entry.record }]); if (!updated) throw new Error('Approval state could not be persisted.'); return entry; }
export async function createPendingApproval(input: Omit<ApprovalRecord, 'status' | 'decision' | 'execution' | 'notification'>) { const record: ApprovalRecord = { ...input, status: 'pending', decision: null, execution: { state: 'not_started', actionStatus: null, summary: null, completedAt: null, reauthorization: null }, notification: { state: 'not_attempted', attemptedAt: null, sent: 0, failed: 0 } }; const [id] = await db.add(approvalsTable(input.organizationId), [record]); if (!id) throw new Error('Approval request could not be persisted.'); try{await appendAuditEvent({organizationId:input.organizationId,eventType:'approval.requested',category:'approval',severity:'warning',actor:{type:'agent',id:input.agentId,label:input.agentName},resource:{type:'approval',id,name:input.request.resourceName},correlationId:input.correlationId,outcome:'pending',summary:`Approval requested for ${input.request.scope}.`,metadata:{actionId:input.actionId,scope:input.request.scope,risk:input.request.risk}})}catch(caught){await db.delete(approvalsTable(input.organizationId),[id]);throw caught} return { id, record }; }
export async function deletePendingApproval(entry: ApprovalEntry) { if (entry.record.status !== 'pending') return; await db.delete(approvalsTable(entry.record.organizationId), [entry.id]); }
export async function notifyApproval(entry: ApprovalEntry, recipientUserId: string) { const attemptedAt = new Date().toISOString(); let next = entry; try { const membership = await getOrganizationForUser(recipientUserId, entry.record.organizationId); if (!membership?.permissions.includes('approvals.review')) { next = { ...entry, record: { ...entry.record, notification: { state: 'unavailable', attemptedAt, sent: 0, failed: 0 } } }; try { await write(next); } catch {} return next; } const delivery = await notifications.send({ userIds: [recipientUserId], notification: { title: 'Agent approval required', body: `${entry.record.agentName} requests ${entry.record.request.scope} on ${entry.record.request.resourceName}.` }, data: { kind: 'approval', organizationId: entry.record.organizationId, approvalId: entry.id, actionId: entry.record.actionId }, ttlSeconds: 600 }); next = { ...entry, record: { ...entry.record, notification: { state: delivery.sent > 0 ? 'sent' : 'unavailable', attemptedAt, sent: delivery.sent, failed: delivery.failed } } }; try { await write(next); } catch {} return next; } catch { next = { ...entry, record: { ...entry.record, notification: { state: 'failed', attemptedAt, sent: 0, failed: 1 } } }; try { await write(next); } catch {} return next; } }
export async function getApprovalEntry(organizationId: string, approvalId: string) { const [record] = await db.get<ApprovalRecord>(approvalsTable(organizationId), [approvalId]); return record ? { id: approvalId, record } : null; }
export async function listApprovalEntries(organizationId: string) { const { items } = await db.list<ApprovalRecord>(approvalsTable(organizationId), { limit: 100 }); return items.map((item) => { const { id, ...record } = item; return { id, record: record as ApprovalRecord }; }).sort((a, b) => b.record.requestedAt.localeCompare(a.record.requestedAt)); }
export async function setApprovalDecision(organizationId: string, approvalId: string, decision: ApprovalDecision, note: string, decidedBy: string) { const entry = await getApprovalEntry(organizationId, approvalId); if (!entry) return null; if (entry.record.status !== 'pending') return entry; const next: ApprovalEntry = { id: approvalId, record: { ...entry.record, status: decision === 'approve' ? 'approved' : 'rejected', decision: { decision, note, decidedBy, decidedAt: new Date().toISOString() } } }; return write(next); }
export async function setApprovalExecution(organizationId: string, approvalId: string, execution: ApprovalExecution) { const entry = await getApprovalEntry(organizationId, approvalId); if (!entry) return null; if (entry.record.status === 'pending') throw new Error('Pending approval cannot receive execution state.'); return write({ id: approvalId, record: { ...entry.record, execution } }); }
