import { db } from '@appdeploy/sdk';
import { getOrganizationForUser } from './organizations';
export type AuditCategory='identity'|'integration'|'policy'|'action'|'approval'|'risk'|'incident'|'security'|'system';
export type AuditSeverity='info'|'warning'|'critical';
export type AuditActorType='human'|'agent'|'system';
export interface AuditEventInput{organizationId:string;eventType:string;category:AuditCategory;severity:AuditSeverity;actor:{type:AuditActorType;id:string;label?:string|null};resource:{type:string;id:string;name?:string|null};correlationId?:string|null;outcome?:string|null;summary:string;metadata?:Record<string,string|number|boolean|null>;occurredAt?:string}
interface AuditRecord{organizationId:string;eventType:string;category:AuditCategory;severity:AuditSeverity;actor:{type:AuditActorType;id:string;label:string|null};resource:{type:string;id:string;name:string|null};correlationId:string|null;outcome:string|null;summary:string;metadata:Record<string,string|number|boolean|null>;occurredAt:string}
export class AuditDomainError extends Error{statusCode:number;constructor(message:string,statusCode=400){super(message);this.statusCode=statusCode}}
function table(organizationId:string){return `audit:${organizationId}`}
function publicEvent(id:string,record:AuditRecord){return{id,...record}}
export async function appendAuditEvent(input:AuditEventInput){const record:AuditRecord={organizationId:input.organizationId,eventType:input.eventType,category:input.category,severity:input.severity,actor:{type:input.actor.type,id:input.actor.id,label:input.actor.label??null},resource:{type:input.resource.type,id:input.resource.id,name:input.resource.name??null},correlationId:input.correlationId??null,outcome:input.outcome??null,summary:input.summary,metadata:input.metadata??{},occurredAt:input.occurredAt??new Date().toISOString()};const[id]=await db.add(table(input.organizationId),[record]);if(!id)throw new AuditDomainError('Audit event could not be persisted.',503);return publicEvent(id,record)}
export async function appendAuditEventBestEffort(input:AuditEventInput){try{return await appendAuditEvent(input)}catch(caught){console.warn('AgentGate audit emission failed',caught);return null}}
async function requireAccess(userId:string,organizationId:string){const organization=await getOrganizationForUser(userId,organizationId);if(!organization)throw new AuditDomainError('Organization not found or access denied.',404);if(!organization.permissions.includes('audit.read'))throw new AuditDomainError('Forbidden: your organization role does not grant audit access.',403);return organization}
function queryOf(raw:Record<string,string>){const q=(raw.q??'').trim().slice(0,120).toLowerCase();const category=(raw.category??'').trim() as AuditCategory;const severity=(raw.severity??'').trim() as AuditSeverity;const actorType=(raw.actorType??'').trim() as AuditActorType;const correlationId=(raw.correlationId??'').trim().slice(0,128);if(category&&!['identity','integration','policy','action','approval','risk','incident','security','system'].includes(category))throw new AuditDomainError('Invalid audit category.');if(severity&&!['info','warning','critical'].includes(severity))throw new AuditDomainError('Invalid audit severity.');if(actorType&&!['human','agent','system'].includes(actorType))throw new AuditDomainError('Invalid audit actor type.');return{q,category,severity,actorType,correlationId}}
export async function listAuditForUser(userId:string,organizationId:string,rawQuery:Record<string,string>){await requireAccess(userId,organizationId);const filters=queryOf(rawQuery);const{items,nextToken}=await db.list<AuditRecord>(table(organizationId),{limit:200});let events=items.map((item)=>{const{id,...record}=item;return publicEvent(id,record as AuditRecord)}).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));if(filters.category)events=events.filter((event)=>event.category===filters.category);if(filters.severity)events=events.filter((event)=>event.severity===filters.severity);if(filters.actorType)events=events.filter((event)=>event.actor.type===filters.actorType);if(filters.correlationId)events=events.filter((event)=>event.correlationId===filters.correlationId);if(filters.q)events=events.filter((event)=>[event.eventType,event.summary,event.actor.id,event.actor.label,event.resource.id,event.resource.name,event.correlationId].filter(Boolean).join(' ').toLowerCase().includes(filters.q));const bySeverity={info:0,warning:0,critical:0};const byCategory:Record<AuditCategory,number>={identity:0,integration:0,policy:0,action:0,approval:0,risk:0,incident:0,security:0,system:0};for(const event of events){bySeverity[event.severity]+=1;byCategory[event.category]+=1}return{events,summary:{visible:events.length,bySeverity,byCategory,uniqueCorrelations:new Set(events.map((event)=>event.correlationId).filter(Boolean)).size,latestAt:events[0]?.occurredAt??null},window:{scanned:items.length,limit:200,truncated:Boolean(nextToken)}}}
export function serializeAuditV2(result:Awaited<ReturnType<typeof listAuditForUser>>){return{items:result.events.map((event)=>({identity:{id:event.id,eventType:event.eventType,category:event.category,severity:event.severity,occurredAt:event.occurredAt},actor:event.actor,resource:event.resource,trace:{correlationId:event.correlationId},outcome:event.outcome,summary:event.summary,metadata:event.metadata})),summary:result.summary,window:result.window}}
