import { db } from '@appdeploy/sdk';
import { listAgentsForUser } from './agents';
import { listIntegrationsForUser } from './integrations';
import { getOrganizationForUser } from './organizations';
import { getIntegrationAdapter } from '../integrations/registry';
export class CapabilityDomainError extends Error { statusCode: number; constructor(message: string, statusCode = 400) { super(message); this.statusCode = statusCode; } }
interface CapabilityProfileRecord { agentId: string; scopes: string[]; createdBy: string; createdAt: string; updatedBy: string; updatedAt: string; }
function profileTable(organizationId: string, agentId: string) { return `capability_profile:${organizationId}:${agentId}`; }
async function requireAccess(userId: string, organizationId: string, permission: 'capabilities.read' | 'capabilities.manage') { const organization = await getOrganizationForUser(userId, organizationId); if (!organization) throw new CapabilityDomainError('Organization not found or access denied.', 404); if (!organization.permissions.includes(permission)) throw new CapabilityDomainError('Forbidden: your organization role does not grant this capability permission.', 403); return organization; }
export async function listCapabilityCatalog(userId: string, organizationId: string) { await requireAccess(userId, organizationId, 'capabilities.read'); const integrations = await listIntegrationsForUser(userId, organizationId); const resources = integrations.filter((integration) => integration.status !== 'disconnected').map((integration) => { const adapter = getIntegrationAdapter(integration.provider); const actions = adapter.capabilities.map((capability) => ({ id: `${capability.action}:${capability.target}`, action: capability.action, target: capability.target, providerOperation: capability.providerOperation, scope: capability.scope, description: capability.description, risk: capability.risk })); return { id: `integration:${integration.id}`, organizationId, integrationId: integration.id, provider: integration.provider, type: adapter.capabilities[0]?.resourceType ?? 'resource', key: integration.resourceKey, displayName: integration.displayName, status: integration.status, metadata: integration.metadata, actions, scopes: actions.map((action) => action.scope) }; }); const scopes = Array.from(new Set(resources.flatMap((resource) => resource.scopes))).sort(); const actions = resources.reduce((total, resource) => total + resource.actions.length, 0); return { resources, scopes, summary: { resources: resources.length, actions, scopes: scopes.length } }; }
async function requireAgent(userId: string, organizationId: string, agentId: string) { const agent = (await listAgentsForUser(userId, organizationId)).find((item) => item.id === agentId); if (!agent) throw new CapabilityDomainError('Agent identity not found or access denied.', 404); return agent; }
export async function getAgentCapabilityProfile(userId: string, organizationId: string, agentId: string) { await requireAccess(userId, organizationId, 'capabilities.read'); const agent = await requireAgent(userId, organizationId, agentId); const catalog = await listCapabilityCatalog(userId, organizationId); const available = new Set(catalog.scopes); const { items } = await db.list<CapabilityProfileRecord>(profileTable(organizationId, agentId), { limit: 1 }); const record = items[0]; const declaredScopes = record?.scopes ?? []; const activeScopes = declaredScopes.filter((scope) => available.has(scope)); const staleScopes = declaredScopes.filter((scope) => !available.has(scope)); return { agent: { id: agent.id, name: agent.name, status: agent.status }, declaredScopes, activeScopes, staleScopes, updatedAt: record?.updatedAt ?? null, updatedBy: record?.updatedBy ?? null, authorization: { state: 'contextual' as const, reason: 'Capability declarations are not standing grants. Each attempted action requires a Policy Engine decision.' } }; }
export async function setAgentCapabilityProfile(userId: string, organizationId: string, agentId: string, rawScopes: unknown) { await requireAccess(userId, organizationId, 'capabilities.manage'); await requireAgent(userId, organizationId, agentId); if (!Array.isArray(rawScopes) || rawScopes.some((scope) => typeof scope !== 'string')) throw new CapabilityDomainError('Scopes must be an array of capability scope strings.'); if (rawScopes.length > 100) throw new CapabilityDomainError('No more than 100 capability scopes may be declared for one agent.'); const scopes = Array.from(new Set(rawScopes.map((scope) => scope.trim()).filter(Boolean))).sort(); const catalog = await listCapabilityCatalog(userId, organizationId); const available = new Set(catalog.scopes); const unavailable = scopes.filter((scope) => !available.has(scope)); if (unavailable.length) throw new CapabilityDomainError(`Unavailable capability scope: ${unavailable[0]}.`, 409); const table = profileTable(organizationId, agentId); const { items } = await db.list<CapabilityProfileRecord>(table, { limit: 1 }); const now = new Date().toISOString(); const current = items[0]; if (current) { const [updated] = await db.update(table, [{ id: current.id, record: { agentId, scopes, createdBy: current.createdBy, createdAt: current.createdAt, updatedBy: userId, updatedAt: now } }]); if (!updated) throw new CapabilityDomainError('Failed to update capability declaration.', 500); } else { const [id] = await db.add(table, [{ agentId, scopes, createdBy: userId, createdAt: now, updatedBy: userId, updatedAt: now }]); if (!id) throw new CapabilityDomainError('Failed to create capability declaration.', 500); } return getAgentCapabilityProfile(userId, organizationId, agentId); }
export function serializeCapabilityCatalogV2(catalog: Awaited<ReturnType<typeof listCapabilityCatalog>>) { return { resources: catalog.resources.map((resource) => ({ identity: { id: resource.id, type: resource.type, provider: resource.provider, status: resource.status }, source: { organizationId: resource.organizationId, integrationId: resource.integrationId, key: resource.key, displayName: resource.displayName, metadata: resource.metadata }, capabilities: { actions: resource.actions, scopes: resource.scopes } })), summary: catalog.summary }; }
export function serializeCapabilityProfileV2(profile: Awaited<ReturnType<typeof getAgentCapabilityProfile>>) { return { agent: profile.agent, declaration: { scopes: profile.declaredScopes, activeScopes: profile.activeScopes, staleScopes: profile.staleScopes, updatedAt: profile.updatedAt, updatedBy: profile.updatedBy }, enforcement: profile.authorization }; }
