import { db } from '@appdeploy/sdk';
import { createAgent,setAgentStatus } from './agents';
import { createJobForUser,getJobForRuntime,queueJobForQuickStart,setJobStatusForUser } from './jobs';
import { saveTriggerConfigForUser } from './scheduler';
import { createWorkerForUser,getWorkerForRuntime,setWorkerStatusForUser } from './workforce';

type Weekday='monday'|'tuesday'|'wednesday'|'thursday'|'friday'|'saturday'|'sunday';
type TimingMode='manual'|'start_now'|'once'|'interval'|'daily'|'weekly'|'custom'|'event'|'dependency';
interface Timing{mode:TimingMode;timezone:string;at:string|null;intervalMinutes:number;localTime:string;weekdays:Weekday[];eventKey:string|null;dependencyJobIds:string[]}
interface IntentJob{jobId:string;timing:Timing;configured:boolean;queued:boolean}
interface IntentRecord{organizationId:string;userId:string;workerId:string;autoActivateWorker:boolean;source:'worker_quick_start'|'job_quick_start';jobs:IntentJob[];blockers:string[];createdAt:string;updatedAt:string}
interface ReconcileState{cursor:string|null;updatedAt:string}

export class QuickStartDomainError extends Error{statusCode:number;constructor(message:string,statusCode=400){super(message);this.statusCode=statusCode}}

const WEEKDAYS:Weekday[]=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
const INTENTS='quick_start_intents';
const STATE='quick_start_state';

function objectOf(raw:unknown){return typeof raw==='object'&&raw!==null?raw as Record<string,unknown>:{} }
function text(raw:unknown){return typeof raw==='string'?raw.trim():''}
function list(raw:unknown){return Array.isArray(raw)?Array.from(new Set(raw.map(text).filter(Boolean))):[]}
function timezoneOf(raw:unknown,fallback='UTC'){const timezone=text(raw)||fallback;try{new Intl.DateTimeFormat('en-US',{timeZone:timezone}).format(new Date())}catch{throw new QuickStartDomainError('Schedule timezone must be a valid IANA timezone.')}return timezone}
function timeOf(raw:unknown,fallback='09:00'){const value=text(raw)||fallback;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new QuickStartDomainError('Schedule time must use HH:MM.');return value}
function timingOf(raw:unknown,defaultTimezone:string):Timing{const value=objectOf(raw);const mode=(text(value.mode)||'start_now') as TimingMode;if(!['manual','start_now','once','interval','daily','weekly','custom','event','dependency'].includes(mode))throw new QuickStartDomainError('Run timing is invalid.');const timezone=timezoneOf(value.timezone,defaultTimezone);const weekdays=list(value.weekdays) as Weekday[];if(weekdays.some((day)=>!WEEKDAYS.includes(day)))throw new QuickStartDomainError('Schedule contains an invalid weekday.');const intervalMinutes=Number(value.intervalMinutes??60);if(mode==='interval'&&(!Number.isInteger(intervalMinutes)||intervalMinutes<5||intervalMinutes>10080))throw new QuickStartDomainError('Recurring intervals must be between 5 and 10080 minutes.');const localTime=timeOf(value.localTime);const eventKey=text(value.eventKey)||null;if(mode==='event'&&(!eventKey||!/^[A-Za-z0-9_.:-]{2,120}$/.test(eventKey)))throw new QuickStartDomainError('Event key is invalid.');const dependencyJobIds=list(value.dependencyJobIds);if(mode==='dependency'&&!dependencyJobIds.length)throw new QuickStartDomainError('Choose at least one dependency Job.');let at:string|null=null;if(mode==='once'){const parsed=new Date(text(value.at));if(Number.isNaN(parsed.getTime())||parsed.getTime()<=Date.now())throw new QuickStartDomainError('One-time work must be scheduled in the future.');at=parsed.toISOString()}if((mode==='weekly'||mode==='custom')&&!weekdays.length)throw new QuickStartDomainError('Choose at least one working day for this schedule.');return{mode,timezone,at,intervalMinutes,localTime,weekdays,eventKey,dependencyJobIds}}
function triggerInput(timing:Timing){const scheduled=['interval','daily','weekly','custom'].includes(timing.mode);return{schedule:{enabled:scheduled,cadence:timing.mode==='interval'?'interval':timing.mode==='daily'?'daily':'weekly',timezone:timing.timezone,localTime:timing.localTime,weekdays:timing.weekdays,intervalMinutes:timing.intervalMinutes,missedRunPolicy:'queue_once',outsideWorkingHoursPolicy:'next_open'},apiEnabled:false,internalEventKeys:timing.mode==='event'&&timing.eventKey?[timing.eventKey]:[],dependencyJobIds:timing.mode==='dependency'?timing.dependencyJobIds:[]}}
function blocker(caught:unknown){return caught instanceof Error?caught.message:'Audoryn could not finish automatic setup.'}

async function persistIntent(record:IntentRecord){const[id]=await db.add(INTENTS,[record]);if(!id)throw new QuickStartDomainError('Automatic worker setup could not be registered.',500);return id}
async function updateIntent(id:string,record:IntentRecord){const[ok]=await db.update(INTENTS,[{id,record}]);if(!ok)throw new QuickStartDomainError('Automatic worker setup checkpoint could not be saved.',500)}
async function cleanupWorkerSetup(userId:string,organizationId:string,workerId:string|null,jobIds:string[],agentId:string|null){for(const jobId of jobIds)try{await setJobStatusForUser(userId,organizationId,jobId,'archived')}catch{}if(workerId)try{await setWorkerStatusForUser(userId,organizationId,workerId,'archived')}catch{}if(agentId)try{await setAgentStatus(userId,organizationId,agentId,'disabled')}catch{}}

async function configureJob(intentId:string,record:IntentRecord,item:IntentJob){const job=await getJobForRuntime(record.organizationId,item.jobId);if(job.status==='draft'){await setJobStatusForUser(record.userId,record.organizationId,item.jobId,'active')}else if(job.status!=='active')throw new QuickStartDomainError(`Job ${job.name} is ${job.status}; Audoryn will not override a human lifecycle state.`,409);if(item.configured)return item;const timing=item.timing;if(timing.mode==='manual')return{...item,configured:true};if(timing.mode==='start_now'){await queueJobForQuickStart(record.userId,record.organizationId,item.jobId,new Date().toISOString(),`quickstart:${intentId}:${item.jobId}:start`,'manual');return{...item,configured:true,queued:true}}if(timing.mode==='once'&&timing.at){await queueJobForQuickStart(record.userId,record.organizationId,item.jobId,timing.at,`quickstart:${intentId}:${item.jobId}:once:${timing.at}`,'schedule');return{...item,configured:true,queued:true}}await saveTriggerConfigForUser(record.userId,record.organizationId,item.jobId,triggerInput(timing));let queued=item.queued;if(record.source==='worker_quick_start'&&['interval','daily','weekly','custom'].includes(timing.mode)&&!queued){await queueJobForQuickStart(record.userId,record.organizationId,item.jobId,new Date().toISOString(),`quickstart:${intentId}:${item.jobId}:first`,'manual');queued=true}return{...item,configured:true,queued}}

async function reconcileIntent(id:string,record:IntentRecord){const blockers:string[]=[];let worker=await getWorkerForRuntime(record.organizationId,record.workerId);if(record.autoActivateWorker&&worker.status==='draft'){try{worker=await setWorkerStatusForUser(record.userId,record.organizationId,record.workerId,'active')}catch(caught){blockers.push(blocker(caught))}}else if(worker.status!=='active')blockers.push(`Worker ${worker.name} is ${worker.status}; Audoryn will not override a human lifecycle state.`);const jobs:IntentJob[]=[];for(const item of record.jobs){if(worker.status!=='active'){jobs.push(item);continue}try{jobs.push(await configureJob(id,record,item))}catch(caught){jobs.push(item);blockers.push(blocker(caught))}}const unique=Array.from(new Set(blockers));const complete=unique.length===0&&jobs.every((item)=>item.configured);if(complete){await db.delete(INTENTS,[id]);return{state:'started' as const,blockers:[],workerId:record.workerId,jobIds:jobs.map((item)=>item.jobId)}}const next={...record,jobs,blockers:unique,updatedAt:new Date().toISOString()};await updateIntent(id,next);return{state:'needs_setup' as const,blockers:unique,workerId:record.workerId,jobIds:jobs.map((item)=>item.jobId)}}

export async function createWorkerQuickStartForUser(userId:string,organizationId:string,raw:unknown){const value=objectOf(raw);const workerValue=objectOf(value.worker);const name=text(workerValue.name);if(name.length<2)throw new QuickStartDomainError('Worker name is required.');const rawJobs=Array.isArray(value.jobs)?value.jobs:[];if(rawJobs.length<1||rawJobs.length>5)throw new QuickStartDomainError('Create between 1 and 5 Jobs with a Worker.');const working=objectOf(workerValue.workingHours);const defaultTimezone=timezoneOf(working.timezone,'UTC');const preparedJobs=rawJobs.map((entry)=>{const item=objectOf(entry);return{raw:item,timing:timingOf(item.timing,defaultTimezone)}});const identityMode=text(workerValue.identityMode)==='existing'?'existing':'automatic';let autoAgentId:string|null=null;let autoCredential:Awaited<ReturnType<typeof createAgent>>['credential']|null=null;let workerId:string|null=null;const jobIds:string[]=[];try{let agentIdentityId=text(workerValue.agentIdentityId);if(identityMode==='automatic'){const created=await createAgent(userId,organizationId,`${name} Agent`,`Dedicated Agent Identity for managed worker ${name}.`);agentIdentityId=created.agent.id;autoAgentId=created.agent.id;autoCredential=created.credential}if(!agentIdentityId)throw new QuickStartDomainError('Choose an Agent Identity or keep automatic identity enabled.');const worker=await createWorkerForUser(userId,organizationId,{agentIdentityId,name,roleId:workerValue.roleId,department:workerValue.department,supervisorUserId:workerValue.supervisorUserId,description:workerValue.description,responsibilities:workerValue.responsibilities,instructions:workerValue.instructions,workingHours:workerValue.workingHours},{agentIdentityProvisioning:identityMode});workerId=worker.id;for(const prepared of preparedJobs){const job=await createJobForUser(userId,organizationId,{...prepared.raw,workerId:worker.id,timing:undefined});jobIds.push(job.id)}const now=new Date().toISOString();const record:IntentRecord={organizationId,userId,workerId:worker.id,autoActivateWorker:true,source:'worker_quick_start',jobs:jobIds.map((jobId,index)=>({jobId,timing:preparedJobs[index].timing,configured:false,queued:false})),blockers:[],createdAt:now,updatedAt:now};const intentId=await persistIntent(record);const readiness=await reconcileIntent(intentId,record);return{workerId:worker.id,jobIds,identity:{agentId:agentIdentityId,createdAutomatically:identityMode==='automatic',credential:autoCredential},readiness}}catch(caught){await cleanupWorkerSetup(userId,organizationId,workerId,jobIds,autoAgentId);throw caught}}

export async function createJobQuickStartForUser(userId:string,organizationId:string,raw:unknown){const value=objectOf(raw);const jobValue=objectOf(value.job);const job=await createJobForUser(userId,organizationId,jobValue);try{const worker=await getWorkerForRuntime(organizationId,job.workerId);const timing=timingOf(value.timing,worker.workingHours.timezone);const now=new Date().toISOString();const record:IntentRecord={organizationId,userId,workerId:job.workerId,autoActivateWorker:false,source:'job_quick_start',jobs:[{jobId:job.id,timing,configured:false,queued:false}],blockers:[],createdAt:now,updatedAt:now};const intentId=await persistIntent(record);const readiness=await reconcileIntent(intentId,record);return{jobId:job.id,workerId:job.workerId,readiness}}catch(caught){try{await setJobStatusForUser(userId,organizationId,job.id,'archived')}catch{}throw caught}}

export async function removeQuickStartIntentsForDeletion(organizationId:string,filter:{workerId?:string;jobIds?:string[]}){const result=await db.list<IntentRecord>(INTENTS,{limit:100});if(result.nextToken)throw new QuickStartDomainError('Quick Start reconciliation exceeds the safe deletion window.',503);const jobIds=new Set(filter.jobIds??[]);const ids=result.items.filter((item)=>item.organizationId===organizationId&&((filter.workerId&&item.workerId===filter.workerId)||item.jobs.some((job)=>jobIds.has(job.jobId)))).map((item)=>item.id);if(ids.length){const deleted=await db.delete(INTENTS,ids);if(deleted.some((ok)=>!ok))throw new QuickStartDomainError('Quick Start reconciliation records could not be cleared.',500)}return ids.length}
export async function reconcileQuickStarts(){const{items:states}=await db.list<ReconcileState>(STATE,{limit:1});const state=states[0];const page=await db.list<IntentRecord>(INTENTS,{limit:25,nextToken:state?.cursor??undefined});for(const item of page.items){const{id,...record}=item;try{await reconcileIntent(id,record as IntentRecord)}catch(caught){console.warn('Audoryn quick-start reconciliation failed',id,caught)}}const next:ReconcileState={cursor:page.nextToken??null,updatedAt:new Date().toISOString()};if(state){const[ok]=await db.update(STATE,[{id:state.id,record:next}]);if(!ok)console.warn('Audoryn quick-start cursor could not be updated')}else{const[id]=await db.add(STATE,[next]);if(!id)console.warn('Audoryn quick-start cursor could not be created')}return{processed:page.items.length,hasMore:Boolean(page.nextToken)}}