import { db } from '@appdeploy/sdk';
import { listAgentsForUser } from './agents';
import { appendAuditEventBestEffort } from './audit';
import { listCapabilityCatalog } from './capabilities';
import { getOrganizationForUser } from './organizations';
import type { CapabilityRisk } from '../integrations/contracts';
export type RiskSignalCode='burst_activity'|'repeated_blocks'|'repeated_failures'|'approval_pressure'|'history_truncated';
export interface RiskSignal{code:RiskSignalCode;active:boolean;increment:0|1;count:number;threshold:number;windowMinutes:number|null;reason:string}
export interface RiskAssessment{baselineRisk:CapabilityRisk;effectiveRisk:CapabilityRisk;elevationSteps:number;evaluatedAt:string;signals:RiskSignal[];counters:{requests10m:number;blocked30m:number;failed30m:number;approval30m:number};window:{scanned:number;agentMatches:number;limit:number;truncated:boolean};context:{agentId:string;agentName:string;resourceId:string;resourceName:string;scope:string;action:string}}
interface ActionHistoryRecord{agentId:string;agentName:string;resourceId:string;resourceName:string|null;scope:string;status:string;approvalId:string|null;correlationId:string;requestedAt:string;riskAssessment?:RiskAssessment|null}
export class RiskDomainError extends Error{statusCode:number;constructor(message:string,statusCode=400){super(message);this.statusCode=statusCode}}
const LEVELS:CapabilityRisk[]=['low','medium','high','critical'];const LIMIT=100;const MINUTE=60_000;
function actionsTable(organizationId:string){return `actions:${organizationId}`}
async function requireAccess(userId:string,organizationId:string){const organization=await getOrganizationForUser(userId,organizationId);if(!organization)throw new RiskDomainError('Organization not found or access denied.',404);if(!organization.permissions.includes('risk.read'))throw new RiskDomainError('Forbidden: your organization role does not grant risk access.',403);return organization}
function sinceMinutes(timestamp:string,minutes:number,now:number){const value=new Date(timestamp).getTime();return Number.isFinite(value)&&value>=now-minutes*MINUTE}
async function computeRisk(organizationId:string,input:{agentId:string;agentName:string;resourceId:string;resourceName:string;scope:string;action:string;baselineRisk:CapabilityRisk}){const now=Date.now();const{items,nextToken}=await db.list<ActionHistoryRecord>(actionsTable(organizationId),{limit:LIMIT});const history=items.filter((item)=>item.agentId===input.agentId);const counters={requests10m:history.filter((item)=>sinceMinutes(item.requestedAt,10,now)).length,blocked30m:history.filter((item)=>item.status==='blocked'&&sinceMinutes(item.requestedAt,30,now)).length,failed30m:history.filter((item)=>item.status==='failed'&&sinceMinutes(item.requestedAt,30,now)).length,approval30m:history.filter((item)=>Boolean(item.approvalId)&&sinceMinutes(item.requestedAt,30,now)).length};const truncated=Boolean(nextToken);const signals:RiskSignal[]=[{code:'burst_activity',active:counters.requests10m>=5,increment:counters.requests10m>=5?1:0,count:counters.requests10m,threshold:5,windowMinutes:10,reason:'Five or more requests from the same agent inside ten minutes increases execution pressure.'},{code:'repeated_blocks',active:counters.blocked30m>=3,increment:counters.blocked30m>=3?1:0,count:counters.blocked30m,threshold:3,windowMinutes:30,reason:'Three or more blocked actions inside thirty minutes indicate repeated boundary pressure.'},{code:'repeated_failures',active:counters.failed30m>=2,increment:counters.failed30m>=2?1:0,count:counters.failed30m,threshold:2,windowMinutes:30,reason:'Two or more provider failures inside thirty minutes increase uncertainty.'},{code:'approval_pressure',active:counters.approval30m>=3,increment:counters.approval30m>=3?1:0,count:counters.approval30m,threshold:3,windowMinutes:30,reason:'Three or more approval-gated requests inside thirty minutes increase review pressure.'},{code:'history_truncated',active:truncated,increment:truncated?1:0,count:truncated?1:0,threshold:1,windowMinutes:null,reason:'The bounded behavior window is truncated, so uncertainty conservatively raises risk.'}];const activeSteps=signals.reduce((sum,signal)=>sum+signal.increment,0);const baseIndex=LEVELS.indexOf(input.baselineRisk);const effectiveIndex=Math.min(LEVELS.length-1,Math.max(0,baseIndex)+activeSteps);return{baselineRisk:input.baselineRisk,effectiveRisk:LEVELS[effectiveIndex],elevationSteps:effectiveIndex-Math.max(0,baseIndex),evaluatedAt:new Date(now).toISOString(),signals,counters,window:{scanned:items.length,agentMatches:history.length,limit:LIMIT,truncated},context:{agentId:input.agentId,agentName:input.agentName,resourceId:input.resourceId,resourceName:input.resourceName,scope:input.scope,action:input.action}} satisfies RiskAssessment}
export async function assessRiskForRuntime(organizationId:string,input:{agentId:string;agentName:string;resourceId:string;resourceName:string;scope:string;action:string;baselineRisk:CapabilityRisk;correlationId?:string|null},options:{emitAudit?:boolean}={}){const assessment=await computeRisk(organizationId,input);if(options.emitAudit!==false){const active=assessment.signals.filter((signal)=>signal.active).map((signal)=>signal.code);await appendAuditEventBestEffort({organizationId,eventType:'risk.assessed',category:'risk',severity:assessment.effectiveRisk==='critical'?'critical':assessment.elevationSteps>0||assessment.effectiveRisk==='high'?'warning':'info',actor:{type:'agent',id:input.agentId,label:input.agentName},resource:{type:'risk_assessment',id:input.resourceId,name:input.resourceName},correlationId:input.correlationId??null,outcome:assessment.effectiveRisk,summary:`Risk assessed ${assessment.baselineRisk} → ${assessment.effectiveRisk} for ${input.scope}.`,metadata:{baselineRisk:assessment.baselineRisk,effectiveRisk:assessment.effectiveRisk,elevationSteps:assessment.elevationSteps,activeSignals:active.join(',')||'none',requests10m:assessment.counters.requests10m,blocked30m:assessment.counters.blocked30m,failed30m:assessment.counters.failed30m,approval30m:assessment.counters.approval30m,historyTruncated:assessment.window.truncated}})}return assessment}
export async function assessRiskForUser(userId:string,organizationId:string,rawAgentId:unknown,rawResourceId:unknown,rawScope:unknown){await requireAccess(userId,organizationId);const agentId=typeof rawAgentId==='string'?rawAgentId.trim():'';const resourceId=typeof rawResourceId==='string'?rawResourceId.trim():'';const scope=typeof rawScope==='string'?rawScope.trim():'';if(!agentId||!resourceId||!scope)throw new RiskDomainError('Risk assessment requires agentId, resourceId, and scope.');const[agents,catalog]=await Promise.all([listAgentsForUser(userId,organizationId),listCapabilityCatalog(userId,organizationId)]);const agent=agents.find((item)=>item.id===agentId);if(!agent)throw new RiskDomainError('Agent identity is unavailable.',404);const resource=catalog.resources.find((item)=>item.id===resourceId);if(!resource)throw new RiskDomainError('Resource is not present in the live capability catalog.',409);const capability=resource.actions.find((item)=>item.scope===scope);if(!capability)throw new RiskDomainError('Requested scope is not available on this resource.',409);return computeRisk(organizationId,{agentId,agentName:agent.name,resourceId,resourceName:resource.displayName,scope,action:capability.action,baselineRisk:capability.risk})}
export async function listRiskOverviewForUser(userId:string,organizationId:string){await requireAccess(userId,organizationId);const{items,nextToken}=await db.list<ActionHistoryRecord>(actionsTable(organizationId),{limit:LIMIT});const assessments=items.filter((item)=>item.riskAssessment).map((item)=>({actionId:item.id,correlationId:item.correlationId,status:item.status,agent:{id:item.agentId,name:item.agentName},resource:{id:item.resourceId,name:item.resourceName},scope:item.scope,assessment:item.riskAssessment as RiskAssessment})).sort((a,b)=>b.assessment.evaluatedAt.localeCompare(a.assessment.evaluatedAt));const byEffectiveRisk:{low:number;medium:number;high:number;critical:number}={low:0,medium:0,high:0,critical:0};let elevated=0;let activeSignalHits=0;for(const item of assessments){byEffectiveRisk[item.assessment.effectiveRisk]+=1;if(item.assessment.elevationSteps>0)elevated+=1;activeSignalHits+=item.assessment.signals.filter((signal)=>signal.active).length}return{assessments,summary:{assessedActions:assessments.length,elevated,activeSignalHits,highOrCritical:byEffectiveRisk.high+byEffectiveRisk.critical,byEffectiveRisk,latestAt:assessments[0]?.assessment.evaluatedAt??null},window:{scanned:items.length,limit:LIMIT,truncated:Boolean(nextToken)},thresholds:{burst:{count:5,minutes:10},blocks:{count:3,minutes:30},failures:{count:2,minutes:30},approvals:{count:3,minutes:30},truncatedHistoryElevation:true}}}
export function serializeRiskAssessmentV2(assessment:RiskAssessment){return{context:assessment.context,risk:{baseline:assessment.baselineRisk,effective:assessment.effectiveRisk,elevationSteps:assessment.elevationSteps,evaluatedAt:assessment.evaluatedAt},signals:assessment.signals,counters:assessment.counters,window:assessment.window}}
export function serializeRiskOverviewV2(result:Awaited<ReturnType<typeof listRiskOverviewForUser>>){return{items:result.assessments.map((item)=>({identity:{actionId:item.actionId,correlationId:item.correlationId,status:item.status},actor:item.agent,resource:item.resource,scope:item.scope,assessment:serializeRiskAssessmentV2(item.assessment)})),summary:result.summary,window:result.window,thresholds:result.thresholds}}
