import { disableManagedAgentForWorkerDeletion,getAgentForRuntime } from './agents';
import { appendAuditEventBestEffort } from './audit';
import { cancelWorkItemForSupervision,deleteJobRecordForUser,deleteWorkerJobRecordsForUser,getJobForDeletionForUser,listWorkerJobsForDeletionForUser,listWorkItemsForDestructionForUser,purgeWorkItemsForUser,type DestructiveWorkItemRef } from './jobs';
import { removeQuickStartIntentsForDeletion } from './quickStart';
import { forceCancelRunForDeletion } from './runtime';
import { markRuntimeCorrelationCancelled } from './runtimeInterventions';
import { removeJobAutomationsForDeletion } from './scheduler';
import { deleteWorkerRecordForUser,getWorkerForUser } from './workforce';

const TERMINAL=new Set(['completed','failed','dead_letter','cancelled']);
async function endWorkItems(userId:string,organizationId:string,items:DestructiveWorkItemRef[],reason:string){let runsTerminated=0;for(const item of items){if(TERMINAL.has(item.status))continue;await markRuntimeCorrelationCancelled(organizationId,item.correlationId,item.runId??`workitem:${item.id}`,userId,reason);if(item.runId){try{const run=await forceCancelRunForDeletion(organizationId,item.runId,userId,reason);if(run.status==='cancelled')runsTerminated+=1}catch(caught){console.warn('Audoryn destructive operation could not load/cancel a referenced Run; the cancellation fence remains authoritative.',item.runId,caught)}}try{await cancelWorkItemForSupervision(organizationId,item.id,userId,reason)}catch(caught){console.warn('Audoryn destructive operation could not checkpoint a Work Item before purge.',item.id,caught)}}return runsTerminated}

export async function clearWorkQueueForUser(userId:string,organizationId:string){const items=await listWorkItemsForDestructionForUser(userId,organizationId,'jobs.run');const runsTerminated=await endWorkItems(userId,organizationId,items,'Work Queue cleared by human operator.');const removed=await purgeWorkItemsForUser(userId,organizationId,items,'jobs.run');await appendAuditEventBestEffort({organizationId,eventType:'workforce.queue.cleared',category:'workforce',severity:'warning',actor:{type:'human',id:userId,label:null},resource:{type:'work_queue',id:organizationId,name:'Work Queue'},outcome:'cleared',summary:`Work Queue cleared completely: ${removed} Work Item${removed===1?'':'s'} removed and ${runsTerminated} active Run${runsTerminated===1?'':'s'} ended.`,metadata:{removed,runsTerminated}});return{removed,runsTerminated}}

export async function deleteJobForUser(userId:string,organizationId:string,jobId:string){const job=await getJobForDeletionForUser(userId,organizationId,jobId);const items=await listWorkItemsForDestructionForUser(userId,organizationId,'jobs.manage',{jobId});await removeQuickStartIntentsForDeletion(organizationId,{jobIds:[jobId]});const automation=await removeJobAutomationsForDeletion(userId,organizationId,[jobId]);const runsTerminated=await endWorkItems(userId,organizationId,items,`Job ${job.name} was permanently deleted.`);const workItemsRemoved=await purgeWorkItemsForUser(userId,organizationId,items,'jobs.manage');const deleted=await deleteJobRecordForUser(userId,organizationId,jobId);return{...deleted,automation,workItemsRemoved,runsTerminated}}

export async function deleteWorkerForUser(userId:string,organizationId:string,workerId:string){const worker=await getWorkerForUser(userId,organizationId,workerId);const jobs=await listWorkerJobsForDeletionForUser(userId,organizationId,workerId);const items=await listWorkItemsForDestructionForUser(userId,organizationId,'workforce.manage',{workerId});const agent=await getAgentForRuntime(organizationId,worker.agentIdentityId);const automaticallyProvisioned=worker.agentIdentityProvisioning==='automatic'||agent.description.startsWith('Dedicated Agent Identity for managed worker ');await removeQuickStartIntentsForDeletion(organizationId,{workerId,jobIds:jobs.map((job)=>job.id)});if(automaticallyProvisioned)await disableManagedAgentForWorkerDeletion(organizationId,agent.id,userId);const automation=await removeJobAutomationsForDeletion(userId,organizationId,jobs.map((job)=>job.id),'workforce.manage');const runsTerminated=await endWorkItems(userId,organizationId,items,`Worker ${worker.name} was permanently deleted.`);const workItemsRemoved=await purgeWorkItemsForUser(userId,organizationId,items,'workforce.manage');const jobCleanup=await deleteWorkerJobRecordsForUser(userId,organizationId,workerId);await deleteWorkerRecordForUser(userId,organizationId,workerId);return{workerId,name:worker.name,...jobCleanup,automation,workItemsRemoved,runsTerminated,agentIdentity:{id:agent.id,automaticallyProvisioned,disabled:automaticallyProvisioned}}}
