import { disableManagedAgentForWorkerDeletion,getAgentForRuntime } from './agents';
import { appendAuditEventBestEffort } from './audit';
import { cancelWorkItemForSupervision,deleteJobRecordForUser,deleteWorkerJobRecordsForUser,getJobForDeletionForUser,listWorkerJobsForDeletionForUser,listWorkItemsForDestructionForUser,purgeWorkItemsForUser,setJobStatusForUser,type DestructiveWorkItemRef } from './jobs';
import { removeQuickStartIntentsForDeletion } from './quickStart';
import { forceCancelRunForDeletion } from './runtime';
import { markRuntimeCorrelationCancelled } from './runtimeInterventions';
import { removeJobAutomationsForDeletion } from './scheduler';
import { deleteWorkerRecordForUser,getWorkerForUser,setWorkerStatusForUser } from './workforce';

const TERMINAL=new Set(['completed','failed','dead_letter','cancelled']);
function cursorOf(raw:unknown){return typeof raw==='string'&&raw.trim()?raw.trim():null}
async function endWorkItems(userId:string,organizationId:string,items:DestructiveWorkItemRef[],reason:string){let runsTerminated=0;for(const item of items){if(TERMINAL.has(item.status))continue;await markRuntimeCorrelationCancelled(organizationId,item.correlationId,item.runId??`workitem:${item.id}`,userId,reason);if(item.runId){try{const run=await forceCancelRunForDeletion(organizationId,item.runId,userId,reason);if(run.status==='cancelled')runsTerminated+=1}catch(caught){console.warn('Audoryn destructive operation could not load/cancel a referenced Run; the cancellation fence remains authoritative.',item.runId,caught)}}try{await cancelWorkItemForSupervision(organizationId,item.id,userId,reason)}catch(caught){console.warn('Audoryn destructive operation could not checkpoint a Work Item before purge.',item.id,caught)}}return runsTerminated}

export async function clearWorkQueueForUser(userId:string,organizationId:string){const page=await listWorkItemsForDestructionForUser(userId,organizationId,'jobs.run');const runsTerminated=await endWorkItems(userId,organizationId,page.items,'Work Queue cleared by human operator.');const removed=await purgeWorkItemsForUser(userId,organizationId,page.items,'jobs.run');const complete=!page.nextToken;await appendAuditEventBestEffort({organizationId,eventType:'workforce.queue.clear_batch',category:'workforce',severity:'warning',actor:{type:'human',id:userId,label:null},resource:{type:'work_queue',id:organizationId,name:'Work Queue'},outcome:complete?'cleared':'clearing',summary:`Work Queue clear batch removed ${removed} Work Item${removed===1?'':'s'} and ended ${runsTerminated} active Run${runsTerminated===1?'':'s'}.`,metadata:{removed,runsTerminated,complete}});return{removed,runsTerminated,complete}}

export async function deleteJobForUser(userId:string,organizationId:string,jobId:string,rawCursor?:unknown){const cursor=cursorOf(rawCursor);const job=await getJobForDeletionForUser(userId,organizationId,jobId);if(!cursor){if(job.status!=='archived')await setJobStatusForUser(userId,organizationId,jobId,'archived');await removeQuickStartIntentsForDeletion(organizationId,{jobIds:[jobId]});await removeJobAutomationsForDeletion(userId,organizationId,[jobId])}const page=await listWorkItemsForDestructionForUser(userId,organizationId,'jobs.manage',{jobId},cursor);const runsTerminated=await endWorkItems(userId,organizationId,page.items,`Job ${job.name} was permanently deleted.`);const workItemsRemoved=await purgeWorkItemsForUser(userId,organizationId,page.items,'jobs.manage');if(page.nextToken)return{jobId,name:job.name,complete:false,nextToken:page.nextToken,workItemsRemoved,runsTerminated};const deleted=await deleteJobRecordForUser(userId,organizationId,jobId);return{...deleted,complete:true,nextToken:null,workItemsRemoved,runsTerminated}}

export async function deleteWorkerForUser(userId:string,organizationId:string,workerId:string,rawCursor?:unknown){const cursor=cursorOf(rawCursor);let worker=await getWorkerForUser(userId,organizationId,workerId);const jobs=await listWorkerJobsForDeletionForUser(userId,organizationId,workerId);const agent=await getAgentForRuntime(organizationId,worker.agentIdentityId);const automaticallyProvisioned=worker.agentIdentityProvisioning==='automatic'||agent.description.startsWith('Dedicated Agent Identity for managed worker ');if(!cursor){if(worker.status!=='archived')worker=await setWorkerStatusForUser(userId,organizationId,workerId,'archived');await removeQuickStartIntentsForDeletion(organizationId,{workerId,jobIds:jobs.map((job)=>job.id)});if(automaticallyProvisioned)await disableManagedAgentForWorkerDeletion(organizationId,agent.id,userId);await removeJobAutomationsForDeletion(userId,organizationId,jobs.map((job)=>job.id),'workforce.manage')}const page=await listWorkItemsForDestructionForUser(userId,organizationId,'workforce.manage',{workerId},cursor);const runsTerminated=await endWorkItems(userId,organizationId,page.items,`Worker ${worker.name} was permanently deleted.`);const workItemsRemoved=await purgeWorkItemsForUser(userId,organizationId,page.items,'workforce.manage');if(page.nextToken)return{workerId,name:worker.name,complete:false,nextToken:page.nextToken,jobsDeleted:0,workItemsRemoved,runsTerminated,agentIdentity:{id:agent.id,automaticallyProvisioned,disabled:automaticallyProvisioned}};const jobCleanup=await deleteWorkerJobRecordsForUser(userId,organizationId,workerId);await deleteWorkerRecordForUser(userId,organizationId,workerId);return{workerId,name:worker.name,...jobCleanup,complete:true,nextToken:null,workItemsRemoved,runsTerminated,agentIdentity:{id:agent.id,automaticallyProvisioned,disabled:automaticallyProvisioned}}}
