import { Copy, KeyRound, Play, RefreshCw, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import type { AgentIdentity } from '../../lib/agentApi';
import type { ActionRecord } from '../../lib/actionApi';
import type { CapabilityCatalog } from '../../lib/capabilityApi';
import type { ApiVersion } from '../../lib/systemApi';
import { visibleActions } from './operationModel';

export default function ActivityStage({ actions, agents, catalog, scopes, selected, agentId, resourceId, scope, credential, idempotencyKey, loading, running, error, canManage, apiVersion, onVersion, onRefresh, onSelect, onAgent, onResource, onScope, onCredential, onKey, onNewKey, onRun }: {
  actions: ActionRecord[]; agents: AgentIdentity[]; catalog: CapabilityCatalog | null; scopes: CapabilityCatalog['resources'][number]['actions']; selected: ActionRecord | null;
  agentId: string; resourceId: string; scope: string; credential: string; idempotencyKey: string; loading: boolean; running: boolean; error: string | null; canManage: boolean; apiVersion: ApiVersion;
  onVersion: (v: ApiVersion) => void; onRefresh: () => void; onSelect: (item: ActionRecord) => void; onAgent: (v: string) => void; onResource: (v: string) => void; onScope: (v: string) => void; onCredential: (v: string) => void; onKey: (v: string) => void; onNewKey: () => void; onRun: () => void;
}) {
  const [filter, setFilter] = useState<'all' | 'executed' | 'held' | 'blocked' | 'failed'>('all');
  const visible = visibleActions(actions, filter);
  const counts = { executed: actions.filter((item) => item.status === 'executed').length, held: actions.filter((item) => item.status === 'held').length, blocked: actions.filter((item) => item.status === 'blocked').length, failed: actions.filter((item) => item.status === 'failed').length };
  return <div className='op-page op-activity'><header className='op-heading'><div><span className='op-index'>OPERATIONS / 06 — ACTIVITY</span><h1>Every crossing leaves a trace.</h1><p>See what an agent attempted, what policy decided, and whether the provider was reached.</p></div><div className='op-heading-controls'><button type='button' onClick={onRefresh} disabled={loading}><RefreshCw size={14}/> Refresh</button><div className='op-version'><button className={apiVersion === 'v1' ? 'active' : ''} onClick={() => onVersion('v1')}>v1</button><button className={apiVersion === 'v2' ? 'active' : ''} onClick={() => onVersion('v2')}>v2</button></div></div></header>
    {error && <div className='inline-error' role='alert'>{error}</div>}
    <div className='op-gateway-line'><span>IDENTITY</span><i/><span>CAPABILITY</span><i/><span>POLICY</span><i/><span>PROVIDER</span></div><div className='op-activity-counts'>{(['executed', 'held', 'blocked', 'failed'] as const).map((status) => <button key={status} type='button' className={filter === status ? 'active' : ''} onClick={() => setFilter(filter === status ? 'all' : status)}><strong>{counts[status]}</strong><span>{status}</span></button>)}</div>
    <div className='op-activity-layout'><aside className='op-action-index'><div className='op-section-label'><span>ACTION LEDGER</span><small>{visible.length} visible</small></div>{loading ? <p className='op-empty'>Loading actions…</p> : visible.length ? visible.map((item, index) => <button type='button' className={`op-action-row ${selected?.id === item.id ? 'selected' : ''}`} key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 28}ms` }} onClick={() => onSelect(item)}><span className={`op-status-dot ${item.status}`}/><span><strong>{item.agent.name}</strong><small>{item.request.providerOperation ?? item.request.scope}</small><em>{new Date(item.requestedAt).toLocaleString()}</em></span><b>{item.status}</b></button>) : <p className='op-empty'>No action attempts in this view.</p>}</aside><main className='op-trace-detail' key={selected?.id ?? 'empty'}>{selected ? <><div className='op-section-label'><span>TRACE / {selected.correlationId.slice(0, 12)}</span><small>{selected.status.toUpperCase()}</small></div><h2>{selected.request.providerOperation || selected.request.action || 'Agent action'}</h2><p>{selected.agent.name} attempted {selected.request.scope} on {selected.request.resourceName ?? selected.request.resourceId}.</p><div className='op-trace-phases'><div><span>01</span><strong>Identity</strong><small>{selected.agent.name}</small></div><div><span>02</span><strong>Capability</strong><small>{selected.request.scope}</small></div><div><span>03</span><strong>Policy</strong><small>{selected.policy.outcome.replaceAll('_', ' ')}</small></div><div><span>04</span><strong>Outcome</strong><small>{selected.status === 'executed' ? 'Provider executed' : selected.status === 'held' ? 'Held for approval' : 'Provider not executed'}</small></div></div><div className='op-trace-reason'><ShieldCheck size={18}/><div><strong>{selected.status.toUpperCase()}</strong><p>{selected.error || selected.policy.reason}</p></div></div><dl className='op-trace-facts'><div><dt>Policy</dt><dd>{selected.policy.winningPolicy?.name ?? 'Default deny / precondition'}</dd></div><div><dt>Target</dt><dd>{selected.request.target ?? '—'}</dd></div><div><dt>Correlation</dt><dd>{selected.correlationId}</dd></div><div><dt>Idempotency</dt><dd>{selected.idempotencyHash}</dd></div></dl>{selected.result && <div className='op-trace-result'><div><strong>{selected.result.summary}</strong><button type='button' aria-label='Copy result JSON' onClick={() => void navigator.clipboard.writeText(JSON.stringify(selected.result?.data ?? null, null, 2))}><Copy size={14}/></button></div><pre>{JSON.stringify(selected.result.data, null, 2)}</pre></div>}</> : <div className='op-empty'><ShieldCheck size={22}/><strong>Select an action</strong><p>Its enforcement path will appear here.</p></div>}</main></div>
    <details className='op-gateway-harness'><summary><span>OPERATOR TOOL / GATEWAY TEST</span><strong>Send a controlled test action</strong><small>Uses a real agent credential and the full enforcement pipeline.</small></summary>{canManage ? <div className='op-harness-body'><p><KeyRound size={16}/> The agent secret is sent for this request and is not persisted here.</p><div className='op-harness-fields'><label>Agent<select value={agentId} onChange={(event) => onAgent(event.target.value)}><option value=''>Select agent</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name} · {agent.status}</option>)}</select></label><label>Resource<select value={resourceId} onChange={(event) => onResource(event.target.value)}><option value=''>Select resource</option>{catalog?.resources.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Scope<select value={scope} onChange={(event) => onScope(event.target.value)}><option value=''>Select scope</option>{scopes.map((item) => <option key={item.scope} value={item.scope}>{item.scope}</option>)}</select></label><label>Agent credential<input type='password' autoComplete='off' value={credential} onChange={(event) => onCredential(event.target.value)} placeholder='Agent secret' /></label><label>Idempotency key<div><input value={idempotencyKey} onChange={(event) => onKey(event.target.value)}/><button type='button' aria-label='Generate new key' onClick={onNewKey}><RefreshCw size={14}/></button></div></label></div><button type='button' className='op-primary' disabled={running || !agentId || !resourceId || !scope || !credential} onClick={onRun}><Play size={15}/> {running ? 'Running…' : 'Run through gateway'}</button></div> : <p className='op-empty'>Your role can inspect action history but cannot run gateway tests.</p>}</details><p className='op-footnote'>Every test remains bound by capabilities, policy, approval, and incident controls.</p>
  </div>;
}
