import { Bell, Check, ChevronRight, Clock3, RefreshCw, ShieldCheck, X } from 'lucide-react';
import type { ApprovalNotificationState, ApprovalRecord } from '../../lib/approvalApi';
import type { ApiVersion } from '../../lib/systemApi';

export default function ApprovalStage({ approvals, selected, note, loading, deciding, error, push, apiVersion, onVersion, onRefresh, onSelect, onNote, onDecide, onEnablePush }: {
  approvals: ApprovalRecord[]; selected: ApprovalRecord | null; note: string; loading: boolean; deciding: boolean; error: string | null; push: ApprovalNotificationState | null; apiVersion: ApiVersion;
  onVersion: (version: ApiVersion) => void; onRefresh: () => void; onSelect: (id: string) => void; onNote: (note: string) => void; onDecide: (decision: 'approve' | 'reject') => void; onEnablePush: () => void;
}) {
  const pending = approvals.filter((item) => item.status === 'pending');
  const decided = approvals.filter((item) => item.status !== 'pending');
  return <div className='op-page op-approvals'>
    <header className='op-heading'><div><span className='op-index'>OPERATIONS / 03 — APPROVALS</span><h1>At the threshold.</h1><p>Review the action and its authority before it can cross into execution.</p></div><div className='op-heading-controls'><button type='button' onClick={onRefresh} disabled={loading}><RefreshCw size={14}/> Refresh</button><div className='op-version'><button type='button' className={apiVersion === 'v1' ? 'active' : ''} onClick={() => onVersion('v1')}>v1</button><button type='button' className={apiVersion === 'v2' ? 'active' : ''} onClick={() => onVersion('v2')}>v2</button></div></div></header>
    {error && <div className='inline-error' role='alert'>{error}</div>}
    <div className='op-threshold' aria-label='Approval flow'><span>AGENT REQUEST</span><i/><span>HUMAN DECISION</span><i/><span>REVALIDATION</span><i/><span>EXECUTION</span></div>
    <div className='op-approval-ledger'><section><span>AWAITING DECISION</span><strong>{pending.length}</strong></section><section><span>DECIDED</span><strong>{decided.length}</strong></section><section><span>EXECUTION FAILED</span><strong>{approvals.filter((item) => item.execution.state === 'failed').length}</strong></section><button type='button' onClick={onEnablePush} disabled={!push?.isSupported || push.permission === 'granted'}><Bell size={15}/><span>{push?.permission === 'granted' ? 'Alerts active' : push?.isSupported ? 'Enable alerts' : 'Alerts unavailable'}</span></button></div>
    <div className='op-approval-workbench'>
      <aside className='op-approval-queue'><div className='op-section-label'><span>HELD ACTIONS</span><small>{approvals.length} records</small></div>{loading ? <p className='op-empty'>Loading approvals…</p> : approvals.length ? approvals.map((item, index) => <button type='button' key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 35}ms` }} className={`op-approval-row ${selected?.id === item.id ? 'selected' : ''}`} onClick={() => onSelect(item.id)}><span className={`op-status-dot ${item.status}`}/><span><strong>{item.agentName}</strong><small>{item.request.providerOperation || item.request.action} · {item.request.resourceName}</small><em>{item.status}</em></span><ChevronRight size={15}/></button>) : <p className='op-empty'>No held actions. New approval requests enter here automatically.</p>}</aside>
      <main className='op-approval-decision' key={selected?.id ?? 'empty'}>{selected ? <><div className='op-section-label'><span>DECISION FILE / {selected.id.slice(0, 8)}</span><small>{new Date(selected.requestedAt).toLocaleString()}</small></div><div className='op-approval-subject'><span className={`op-kicker ${selected.status}`}>{selected.status.toUpperCase()}</span><h2>{selected.request.providerOperation || selected.request.action}</h2><p>{selected.agentName} requests access to <strong>{selected.request.resourceName || selected.request.target}</strong>.</p></div><div className='op-approval-evidence'><div><span>CAPABILITY</span><strong>{selected.request.scope}</strong></div><div><span>RISK</span><strong>{selected.request.risk.toUpperCase()}</strong></div><div><span>POLICY</span><strong>{selected.policy.winningPolicy?.name ?? 'Approval policy'}</strong></div></div><div className='op-approval-reason'><ShieldCheck size={18}/><div><strong>Why this action stopped</strong><p>{selected.policy.reason}</p></div></div>{selected.status === 'pending' ? <div className='op-approval-form'><label>Decision note <span>Optional, recorded with your decision</span><textarea value={note} maxLength={500} onChange={(event) => onNote(event.target.value)} placeholder='Add context for the record' /></label><div><button type='button' className='reject' onClick={() => onDecide('reject')} disabled={deciding}><X size={15}/> Reject</button><button type='button' className='approve' onClick={() => onDecide('approve')} disabled={deciding}><Check size={15}/> Approve & revalidate</button></div></div> : <div className='op-approval-outcome'><span>DECISION RECORDED</span><strong>{selected.decision?.decision ?? selected.status}</strong><p>{selected.execution.summary || `Execution: ${selected.execution.state.replaceAll('_', ' ')}`}</p>{selected.execution.reauthorization && <small>Revalidation: {selected.execution.reauthorization.reason}</small>}</div>}</> : <div className='op-empty'><Clock3 size={23}/><strong>Choose a held action</strong><p>Its request, policy, and human decision will appear here.</p></div>}</main>
    </div><p className='op-footnote'>Approval records a human decision. Audoryn checks current authority again before provider execution.</p>
  </div>;
}
