import { ArrowUpRight, ShieldCheck, TriangleAlert } from 'lucide-react';
import type { PerformanceWorkspace } from '../../lib/performanceApi';
import type { ApiVersion } from '../../lib/systemApi';

function elapsed(ms: number) { if (!ms) return '—'; return ms < 60000 ? `${Math.max(1, Math.round(ms / 1000))}s` : `${Math.round(ms / 60000)}m`; }

export default function PerformanceStage({ data, selectedWorker, loading, error, apiVersion, onVersion, onWorker }: {
  data: PerformanceWorkspace | null; selectedWorker: string; loading: boolean; error: string | null; apiVersion: ApiVersion; onVersion: (v: ApiVersion) => void; onWorker: (id: string) => void;
}) {
  const summary = data?.summary;
  const activity = selectedWorker === 'all' ? data?.activity ?? [] : (data?.activity ?? []).filter((item) => item.workerId === selectedWorker);
  const truncated = Object.values(data?.window ?? {}).some((item) => item.truncated);
  const trends = data?.trends ?? [];
  const max = Math.max(1, ...trends.map((point) => point.completed + point.failed + point.cancelled));
  return <div className='op-page op-performance'><header className='op-heading'><div><span className='op-index'>OPERATIONS / 04 — PERFORMANCE</span><h1>An operating picture.</h1><p>See throughput, reliability, and intervention across the scanned work window.</p></div><div className='op-version'><button className={apiVersion === 'v1' ? 'active' : ''} onClick={() => onVersion('v1')}>v1</button><button className={apiVersion === 'v2' ? 'active' : ''} onClick={() => onVersion('v2')}>v2</button></div></header>
    {error && <div className='inline-error' role='alert'>{error}</div>}{truncated && <div className='op-warning'><TriangleAlert size={15}/> Some source windows are truncated. Rates describe scanned data only.</div>}
    <div className='op-performance-axis'><div><span>RUNS OBSERVED</span><strong>{summary?.runs ?? 0}</strong></div><div><span>COMPLETED</span><strong>{summary?.completed ?? 0}</strong></div><div><span>FAILED</span><strong>{summary?.failed ?? 0}</strong></div><div><span>MEDIAN RUN</span><strong>{elapsed(summary?.medianRunDurationMs ?? 0)}</strong></div><div><span>BLOCKED ACTIONS</span><strong>{summary?.blockedActions ?? 0}</strong></div></div>
    <section className='op-performance-landscape'><div className='op-section-label'><span>EXECUTION LANDSCAPE / 14 DAYS</span><small>Completed · failed · cancelled</small></div><div className='op-trend-chart' role='img' aria-label='Daily run outcomes for the last fourteen days'>{loading ? <div className='op-empty'>Loading trend…</div> : trends.map((point, index) => <div className='op-trend-day' key={point.date} style={{ animationDelay: `${Math.min(index, 14) * 30}ms` }} title={`${point.date}: ${point.completed} completed, ${point.failed} failed, ${point.cancelled} cancelled`}><div className='op-trend-bars'><span className='complete' style={{ height: `${point.completed / max * 100}%` }}/><span className='failed' style={{ height: `${point.failed / max * 100}%` }}/><span className='cancelled' style={{ height: `${point.cancelled / max * 100}%` }}/></div><small>{point.date.slice(5)}</small></div>)}</div><div className='op-trend-legend'><span><i className='complete'/> Completed</span><span><i className='failed'/> Failed</span><span><i className='cancelled'/> Cancelled</span></div></section>
    <div className='op-performance-split'><section className='op-performance-rates'><div className='op-section-label'><span>INTERPRET THE SIGNAL</span><small>Operational rates</small></div><div><strong>{summary?.successRate ?? 0}%</strong><span>Run success</span><small>{summary?.completed ?? 0} completed / terminal runs</small></div><div><strong>{summary?.approvalRate ?? 0}%</strong><span>Approval rate</span><small>Decided approvals</small></div><div><strong>{summary?.escalationsPer100Runs ?? 0}</strong><span>Escalations per 100 runs</span><small>{summary?.escalations ?? 0} escalations observed</small></div></section><aside className='op-methodology'><ShieldCheck size={21}/><span>READING THESE NUMBERS</span><h2>Signals, not a worker score.</h2><p>These measures describe observable run and governance outcomes. They do not grade people or authorize an action.</p><dl><div><dt>Run success</dt><dd>{data?.methodology.successRate ?? '—'}</dd></div><div><dt>Tool reliability</dt><dd>{data?.methodology.toolReliability ?? '—'}</dd></div><div><dt>Escalations</dt><dd>{data?.methodology.escalationRate ?? '—'}</dd></div></dl></aside></div>
    <section className='op-performance-roster'><div className='op-section-label'><span>WORKFORCE DISTRIBUTION</span><small>{data?.workers.length ?? 0} workers</small></div>{(data?.workers ?? []).length ? <div className='op-worker-rows'>{data!.workers.map((worker, index) => <div key={worker.id} style={{ animationDelay: `${Math.min(index, 8) * 30}ms` }}><span><strong>{worker.name}</strong><small>{worker.department} · {worker.status}</small></span><span><strong>{worker.runs}</strong><small>runs</small></span><span><strong>{worker.successRate}%</strong><small>success</small></span><span><strong>{worker.blockedActions}</strong><small>blocked</small></span><span><strong>{worker.escalations}</strong><small>escalations</small></span></div>)}</div> : <p className='op-empty'>Worker activity will appear after managed runs.</p>}</section>
    <div className='op-performance-bottom'><section><div className='op-section-label'><span>PROVIDER RELIABILITY</span><small>Execution attempts only</small></div>{(data?.tools ?? []).map((tool) => <div className='op-tool-row' key={tool.id}><strong>{tool.name}</strong><span>{tool.provider}</span><b>{tool.providerAttempts ? `${tool.reliabilityRate}%` : '—'}</b><small>{tool.failed} failed · {tool.blocked} blocked · {tool.held} held</small></div>)}{!data?.tools.length && <p className='op-empty'>Tool reliability appears after provider actions run.</p>}</section><section><div className='op-section-label'><span>RECENT SIGNALS</span><select aria-label='Filter activity by worker' value={selectedWorker} onChange={(event) => onWorker(event.target.value)}><option value='all'>All workers</option>{(data?.workers ?? []).map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></div>{activity.slice(0, 8).map((item) => <div className='op-activity-signal' key={item.id}><i className={item.kind}/><span><strong>{item.label}</strong><small>{item.workerName} · {new Date(item.occurredAt).toLocaleDateString()}</small></span><ArrowUpRight size={14}/></div>)}{!activity.length && <p className='op-empty'>No activity in this view.</p>}</section></div><p className='op-footnote'>Blocks and approval holds are governance outcomes; they are not provider failures.</p>
  </div>;
}
