import { ArrowRight, FileText, Search, SlidersHorizontal } from 'lucide-react';
import type { FormEvent } from 'react';
import type { ResultSummary, ResultsWorkspace } from '../../lib/resultsApi';
import { attentionResults, featuredResult } from './operationModel';

type Page = 'overview' | 'workers' | 'jobs';
function when(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); }

export default function ResultsStage({ data, page, search, appliedSearch, workerId, jobId, status, department, dateRange, schedules, loading, error, onPage, onSearch, onSubmit, onWorkerFilter, onJobFilter, onStatus, onDepartment, onDateRange, onOpenResult, onOpenWorker, onOpenJob }: {
  data: ResultsWorkspace; page: Page; search: string; appliedSearch: string; workerId: string; jobId: string; status: string; department: string; dateRange: string; schedules: Record<string, string>; loading: boolean; error: string | null;
  onPage: (page: Page) => void; onSearch: (value: string) => void; onSubmit: (event: FormEvent) => void; onWorkerFilter: (value: string) => void; onJobFilter: (value: string) => void; onStatus: (value: string) => void; onDepartment: (value: string) => void; onDateRange: (value: string) => void; onOpenResult: (id: string) => void; onOpenWorker: (id: string) => void; onOpenJob: (id: string) => void;
}) {
  const featured = featuredResult(data.items);
  const next = data.items.filter((item) => item.id !== featured?.id).slice(0, 5);
  const needsAttention = attentionResults(data.items).length;
  return <div className='op-page op-results'><header className='op-heading'><div><span className='op-index'>OPERATIONS / 01 — RESULTS</span><h1>Work, made reviewable.</h1><p>Finished work arrives as a deliverable, with its worker, job, and execution record close by.</p></div><div className='op-results-new'><strong>{data.summary.new}</strong><span>new since last visit</span></div></header>
    {error && <div className='inline-error' role='alert'>{error}</div>}
    <div className='op-results-index'><button type='button' className={page === 'overview' ? 'active' : ''} onClick={() => onPage('overview')}><span>01</span> Deliverables <b>{data.summary.total}</b></button><button type='button' className={page === 'workers' ? 'active' : ''} onClick={() => onPage('workers')}><span>02</span> By worker <b>{data.workers.length}</b></button><button type='button' className={page === 'jobs' ? 'active' : ''} onClick={() => onPage('jobs')}><span>03</span> By job <b>{data.jobs.length}</b></button><div><strong>{needsAttention}</strong><span>need attention</span></div></div>
    {page === 'overview' && <><form className='op-results-search' onSubmit={onSubmit}><Search size={17}/><input aria-label='Search results' value={search} onChange={(event) => onSearch(event.target.value)} placeholder='Find a deliverable, worker, or job' /><button type='submit'>Search <ArrowRight size={15}/></button></form><div className='op-results-filters'><SlidersHorizontal size={15}/><select aria-label='Worker' value={workerId} onChange={(event) => onWorkerFilter(event.target.value)}><option value=''>All workers</option>{data.workers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label='Job' value={jobId} onChange={(event) => onJobFilter(event.target.value)}><option value=''>All jobs</option>{data.jobs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label='Status' value={status} onChange={(event) => onStatus(event.target.value)}><option value=''>All statuses</option><option value='completed'>Completed</option><option value='attention'>With attention</option><option value='failed'>Failed</option><option value='cancelled'>Cancelled</option></select><select aria-label='Date range' value={dateRange} onChange={(event) => onDateRange(event.target.value)}><option value='7'>7 days</option><option value='30'>30 days</option><option value='90'>90 days</option><option value='all'>Loaded history</option></select><select aria-label='Department' value={department} onChange={(event) => onDepartment(event.target.value)}><option value=''>All departments</option>{data.filters.departments.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>
      {loading ? <p className='op-empty'>Loading deliverables…</p> : featured ? <><div className='op-results-showcase'><button type='button' className='op-featured-result' onClick={() => onOpenResult(featured.id)}><span className='op-section-label'>FEATURED DELIVERABLE / {featured.isNew ? 'NEW' : 'LATEST'}</span><FileText size={25}/><h2>{featured.title}</h2><p>{featured.summary}</p><div><span>{featured.workerName} · {featured.jobName}</span><strong>Read result <ArrowRight size={16}/></strong></div></button><aside className='op-results-up-next'><div className='op-section-label'><span>FOLLOWING IN THE INDEX</span><small>{next.length} shown</small></div>{next.length ? next.map((item, index) => <ResultEntry key={item.id} item={item} index={index} onOpen={onOpenResult}/>) : <p className='op-empty'>More completed work will appear here.</p>}</aside></div><section className='op-results-attention'><div className='op-section-label'><span>REVIEW SIGNAL</span><small>Exceptions deserve a closer read</small></div><div>{attentionResults(data.items).slice(0, 4).map((item, index) => <ResultEntry key={item.id} item={item} index={index} onOpen={onOpenResult}/>)}{!needsAttention && <p className='op-empty'>No results currently need attention.</p>}</div></section></> : <div className='op-empty'><FileText size={23}/><strong>No deliverables in this view</strong><p>Finished work will enter the Results index automatically.</p></div>}
    </>}
    {page === 'workers' && <section className='op-results-directory'><div className='op-section-label'><span>WORKER INDEX</span><small>{data.workers.length} workers</small></div><form className='op-results-search' onSubmit={onSubmit}><Search size={16}/><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder='Find a worker'/><button type='submit'>Search</button></form>{data.workers.filter((item) => !appliedSearch || `${item.name} ${item.department}`.toLowerCase().includes(appliedSearch.toLowerCase())).map((item, index) => <button type='button' key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 30}ms` }} onClick={() => onOpenWorker(item.id)}><span><strong>{item.name}</strong><small>{item.department}</small></span><span>{item.resultCount} results</span><span>{item.weekCount} this week</span><ArrowRight size={16}/></button>)}{!data.workers.length && <p className='op-empty'>No workers match this index.</p>}</section>}
    {page === 'jobs' && <section className='op-results-directory'><div className='op-section-label'><span>JOB INDEX</span><small>{data.jobs.length} jobs</small></div>{data.jobs.map((item, index) => <button type='button' key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 30}ms` }} onClick={() => onOpenJob(item.id)}><span><strong>{item.name}</strong><small>{item.workerName} · {item.department}</small></span><span>{item.resultCount} results</span><span>{schedules[item.id] ?? 'Manual / event'}</span><ArrowRight size={16}/></button>)}{!data.jobs.length && <p className='op-empty'>No job results yet.</p>}</section>}
    {data.window.truncated && <p className='op-footnote'>This is a bounded recent index. Older results require archive pagination.</p>}
  </div>;
}

function ResultEntry({ item, index, onOpen }: { item: ResultSummary; index: number; onOpen: (id: string) => void }) {
  return <button type='button' className='op-result-entry' style={{ animationDelay: `${Math.min(index, 8) * 32}ms` }} onClick={() => onOpen(item.id)}><span className={`op-status-dot ${item.status}`}/><span><strong>{item.title}</strong><small>{item.workerName} · {when(item.completedAt)}</small></span><em>{item.status === 'attention' ? 'Needs attention' : item.status}</em><ArrowRight size={15}/></button>;
}
