import { ArrowLeft, ArrowRight, FileText } from 'lucide-react';
import type { ResultSummary, ResultsWorkspace } from '../../lib/resultsApi';

type WorkerMode = 'all' | 'jobs' | 'recent' | 'attention';
export default function ResultsArchiveStage({ worker, job, results, jobs, schedules, workerMode, onWorkerMode, onBack, onOpenResult, onOpenJob }: {
  worker?: ResultsWorkspace['workers'][number]; job?: ResultsWorkspace['jobs'][number]; results: ResultSummary[]; jobs: ResultsWorkspace['jobs']; schedules: Record<string, string>; workerMode: WorkerMode;
  onWorkerMode: (mode: WorkerMode) => void; onBack: () => void; onOpenResult: (id: string) => void; onOpenJob: (id: string) => void;
}) {
  const isWorker = Boolean(worker);
  return <div className='op-page op-result-archive'><button type='button' className='op-archive-back' onClick={onBack}><ArrowLeft size={15}/> Results index</button><div className='op-archive-layout'><aside className='op-archive-identity'><span className='op-index'>RESULTS / {isWorker ? 'WORKER' : 'JOB'} ARCHIVE</span><h1>{worker?.name ?? job?.name ?? 'Results'}</h1><p>{worker ? `${worker.department} · ${worker.resultCount} recorded results` : `${job?.workerName ?? 'Worker'} · ${job?.department ?? ''}`}</p><div className='op-archive-signal'><strong>{worker?.weekCount ?? job?.resultCount ?? 0}</strong><span>{worker ? 'results this week' : 'results for this job'}</span></div>{job && <div className='op-archive-schedule'><span>TRIGGER</span><strong>{schedules[job.id] ?? 'Manual / event driven'}</strong></div>}</aside><main className='op-archive-content'><div className='op-section-label'><span>{isWorker ? 'WORKER OUTPUTS' : 'JOB HISTORY'}</span><small>{results.length} in current view</small></div>{worker && <nav className='op-archive-modes' aria-label='Worker result views'>{(['all', 'jobs', 'recent', 'attention'] as const).map((mode) => <button type='button' key={mode} className={workerMode === mode ? 'active' : ''} onClick={() => onWorkerMode(mode)}>{mode === 'all' ? 'All work' : mode === 'attention' ? 'Attention' : mode === 'recent' ? 'Recent' : 'Jobs'}</button>)}</nav>}{workerMode === 'jobs' && worker ? jobs.length ? jobs.map((item, index) => <button type='button' className='op-archive-row' key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 35}ms` }} onClick={() => onOpenJob(item.id)}><span className='op-archive-row-number'>{String(index + 1).padStart(2, '0')}</span><span><strong>{item.name}</strong><small>{schedules[item.id] ?? 'Manual / event'} · {item.resultCount} results</small></span><ArrowRight size={16}/></button>) : <p className='op-empty'>No jobs have results yet.</p> : results.length ? results.map((item, index) => <button type='button' className='op-archive-row' key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 35}ms` }} onClick={() => onOpenResult(item.id)}><span className='op-archive-row-number'>{String(index + 1).padStart(2, '0')}</span><span><strong>{item.title}</strong><small>{item.summary}</small><em>{item.status} · {new Date(item.completedAt).toLocaleDateString()}</em></span><FileText size={16}/></button>) : <p className='op-empty'>No results in this view.</p>}</main></div></div>;
}
