import { AlertTriangle, Bell, Check, Pause, RotateCcw, Send, ShieldAlert, Square } from 'lucide-react';
import type { Escalation, EscalationRule, EscalationSeverity, EscalationTrigger, SupervisionWorkspace } from '../../lib/supervisionApi';
import type { ApiVersion } from '../../lib/systemApi';

const names: Record<EscalationTrigger, string> = { job_failure: 'Job failure', policy_decision: 'Policy decision', risk_high: 'High risk', risk_critical: 'Critical risk' };
const allowed: Record<EscalationTrigger, EscalationSeverity[]> = { job_failure: ['high', 'critical'], policy_decision: ['medium', 'high', 'critical'], risk_high: ['high', 'critical'], risk_critical: ['critical'] };

export default function SupervisionStage({ data, list, selected, filter, note, assignee, reason, loading, working, error, notice, canManage, canIncident, apiVersion, onVersion, onAlerts, onFilter, onSelect, onStatus, onNote, onNoteSubmit, onAssignee, onReassign, onReason, onIntervene, onRule }: {
  data: SupervisionWorkspace | null; list: Escalation[]; selected: Escalation | null; filter: 'mine' | 'all'; note: string; assignee: string; reason: string; loading: boolean; working: boolean; error: string | null; notice: string | null; canManage: boolean; canIncident: boolean; apiVersion: ApiVersion;
  onVersion: (v: ApiVersion) => void; onAlerts: () => void; onFilter: (v: 'mine' | 'all') => void; onSelect: (id: string) => void; onStatus: (v: 'acknowledged' | 'resolved') => void; onNote: (v: string) => void; onNoteSubmit: () => void; onAssignee: (v: string) => void; onReassign: () => void; onReason: (v: string) => void; onIntervene: (v: 'cancel_run' | 'pause_worker' | 'create_incident') => void; onRule: (rule: EscalationRule, patch: Partial<EscalationRule>) => void;
}) {
  return <div className='op-page op-supervision'><header className='op-heading'><div><span className='op-index'>OPERATIONS / 02 — SUPERVISION</span><h1>The signal desk.</h1><p>Exceptions arrive with their source, assigned person, and available intervention.</p></div><div className='op-heading-controls'><button type='button' onClick={onAlerts} disabled={working}><Bell size={14}/> Alerts</button><div className='op-version'><button className={apiVersion === 'v1' ? 'active' : ''} onClick={() => onVersion('v1')}>v1</button><button className={apiVersion === 'v2' ? 'active' : ''} onClick={() => onVersion('v2')}>v2</button></div></div></header>
    {error && <div className='inline-error' role='alert'>{error}</div>}{notice && <div className='product-success'>{notice}</div>}
    <div className='op-signal-band'><span>SUPERVISORY SIGNAL</span><div className='op-signal-line'><i/><i/><i/><i/><i/></div><strong>{data?.summary.open ?? 0} open</strong><em>{data?.summary.critical ?? 0} critical</em></div>
    <div className='op-supervision-workbench'><aside className='op-signal-inbox'><div className='op-section-label'><span>INCOMING CASES</span><small>{list.length} visible</small></div><div className='op-signal-filter'><button type='button' className={filter === 'mine' ? 'active' : ''} onClick={() => onFilter('mine')}>Assigned to me</button><button type='button' className={filter === 'all' ? 'active' : ''} onClick={() => onFilter('all')}>All cases</button></div>{loading ? <p className='op-empty'>Loading escalations…</p> : list.length ? list.map((item, index) => <button type='button' key={item.id} style={{ animationDelay: `${Math.min(index, 8) * 35}ms` }} className={`op-signal-row ${selected?.id === item.id ? 'selected' : ''}`} onClick={() => onSelect(item.id)}><span className={`op-signal-marker ${item.severity}`}><AlertTriangle size={15}/></span><span><strong>{item.title}</strong><small>{item.workerName} · {names[item.trigger]}</small></span><em>{item.status}</em></button>) : <p className='op-empty'>No escalations in this view.</p>}</aside>
      <main className='op-case-file' key={selected?.id ?? 'empty'}>{selected ? <><div className='op-section-label'><span>CASE FILE / {selected.id.slice(0, 8)}</span><small>{selected.severity.toUpperCase()}</small></div><h2>{selected.title}</h2><p className='op-case-summary'>{selected.summary}</p><div className='op-case-origin'><span>WHY IT SURFACED</span><p>{selected.reason}</p></div><dl className='op-case-facts'><div><dt>Worker</dt><dd>{selected.workerName}</dd></div><div><dt>Assigned to</dt><dd>{selected.assignedToUserId}</dd></div><div><dt>Run</dt><dd>{selected.runId?.slice(0, 12) ?? '—'}</dd></div><div><dt>Approval</dt><dd>{selected.approvalId?.slice(0, 12) ?? '—'}</dd></div><div><dt>Incident</dt><dd>{selected.incidentId?.slice(0, 12) ?? '—'}</dd></div></dl>{canManage && selected.status !== 'resolved' && <><div className='op-case-decisions'><button type='button' onClick={() => onStatus('acknowledged')} disabled={working || selected.status === 'acknowledged'}><Check size={14}/> Acknowledge</button><button type='button' onClick={() => onStatus('resolved')} disabled={working}><Check size={14}/> Resolve with note</button></div><div className='op-case-fields'><label>Supervisor note<textarea value={note} onChange={(event) => onNote(event.target.value)} placeholder='Record what you observed or decided' /></label><button type='button' onClick={onNoteSubmit} disabled={working || note.trim().length < 2}><Send size={14}/> Add note</button><label>Reassign to user ID<input value={assignee} onChange={(event) => onAssignee(event.target.value)} placeholder='Organization user ID' /></label><button type='button' onClick={onReassign} disabled={working || !assignee.trim()}><RotateCcw size={14}/> Reassign</button></div><details className='op-case-intervention'><summary>Restrictive intervention</summary><label>Reason<textarea value={reason} onChange={(event) => onReason(event.target.value)} placeholder='Why this intervention is necessary' /></label><div><button type='button' onClick={() => onIntervene('cancel_run')} disabled={working || !selected.runId || reason.trim().length < 5}><Square size={14}/> Cancel run</button><button type='button' onClick={() => onIntervene('pause_worker')} disabled={working || reason.trim().length < 5}><Pause size={14}/> Pause worker</button>{canIncident && <button type='button' onClick={() => onIntervene('create_incident')} disabled={working || reason.trim().length < 5}><ShieldAlert size={14}/> Create incident</button>}</div></details></>}
      <div className='op-case-log'><span>CASE HISTORY</span>{[...selected.notes.map((item) => ({ date: item.createdAt, title: `Note · ${item.authorUserId}`, body: item.body })), ...selected.interventions.map((item) => ({ date: item.occurredAt, title: `${item.action.replaceAll('_', ' ')} · ${item.actorUserId}`, body: item.result }))].sort((a, b) => b.date.localeCompare(a.date)).map((item, index) => <div key={`${item.date}-${index}`}><strong>{item.title}</strong><p>{item.body}</p><small>{new Date(item.date).toLocaleString()}</small></div>)}{!selected.notes.length && !selected.interventions.length && <p>No notes or interventions yet.</p>}</div></> : <div className='op-empty'><ShieldAlert size={22}/><strong>Choose an escalation</strong><p>The source, owner, decision, and case history appear here.</p></div>}</main></div>
    <section className='op-rule-console'><div className='op-section-label'><span>AUTONOMOUS HANDOFF RULES</span><small>Rules route attention; they do not grant authority.</small></div><div className='op-rule-grid'>{(data?.rules ?? []).map((rule) => <div key={rule.trigger}><strong>{names[rule.trigger]}</strong><button type='button' className={rule.enabled ? 'active' : ''} disabled={!canManage || working} onClick={() => onRule(rule, { enabled: !rule.enabled })}>{rule.enabled ? 'On' : 'Off'}</button><select aria-label={`${names[rule.trigger]} severity`} value={rule.severity} disabled={!canManage || working} onChange={(event) => onRule(rule, { severity: event.target.value as EscalationSeverity })}>{allowed[rule.trigger].map((severity) => <option key={severity} value={severity}>{severity}</option>)}</select><label><input type='checkbox' checked={rule.notifySupervisor} disabled={!canManage || working} onChange={(event) => onRule(rule, { notifySupervisor: event.target.checked })}/> Push</label></div>)}</div></section>{data?.window.truncated && <p className='op-footnote'>The case index is bounded to its current read window.</p>}
  </div>;
}
