from ..catalog import BODY, NUMBER, SHA, STRING, action, paged

ACTIONS = (
    action(
        "repository.workflows.read",
        "List repository workflows.",
        "actions:read",
        "/actions/workflows",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.workflow.runs.read",
        "List workflow runs, states and head revisions.",
        "actions:read",
        "/actions/runs",
        fields=paged(branch=STRING, event=STRING),
        query=("page", "per_page", "branch", "event"),
    ),
    action(
        "repository.workflow.run.read",
        "Inspect a workflow run.",
        "actions:read",
        "/actions/runs/{runId}",
        fields={"runId": NUMBER},
        required=("runId",),
    ),
    action(
        "repository.workflow.jobs.read",
        "Inspect workflow jobs and step outcomes.",
        "actions:read",
        "/actions/runs/{runId}/jobs",
        fields=paged(runId=NUMBER),
        required=("runId",),
        query=("page", "per_page"),
    ),
    action(
        "repository.workflow.logs.read",
        "Read bounded sanitized job logs.",
        "actions:read",
        "/actions/jobs/{jobId}/logs",
        fields={"jobId": NUMBER},
        required=("jobId",),
    ),
    action(
        "repository.workflow.artifacts.read",
        "List workflow artifacts and their expiry state.",
        "actions:read",
        "/actions/runs/{runId}/artifacts",
        fields=paged(runId=NUMBER),
        required=("runId",),
        query=("page", "per_page"),
    ),
    action(
        "repository.workflow.artifact.read",
        "Download a bounded workflow artifact into private task evidence.",
        "actions:read",
        "/actions/artifacts/{artifactId}/zip",
        fields={"artifactId": NUMBER},
        required=("artifactId",),
    ),
    action(
        "repository.workflow.dispatch",
        "Start an explicitly approved workflow on an exact authorized revision; acceptance is not test success.",
        "actions:write",
        "/actions/workflows/{workflowId}/dispatches",
        method="POST",
        fields={
            "workflowId": STRING,
            "ref": STRING,
            "expectedSha": SHA,
            "inputs": {
                "type": "object",
                "maxProperties": 25,
                "additionalProperties": {"type": "string", "maxLength": 1000},
            },
        },
        required=("workflowId", "ref", "expectedSha"),
        approval=True,
        reconciliation="workflow_run",
    ),
    action(
        "repository.workflow.rerun",
        "Rerun a workflow after exact approval.",
        "actions:write",
        "/actions/runs/{runId}/rerun",
        method="POST",
        fields={"runId": NUMBER, "expectedSha": SHA, "expectedAttempt": NUMBER},
        required=("runId", "expectedSha", "expectedAttempt"),
        approval=True,
        reconciliation="run_attempt",
    ),
    action(
        "repository.workflow.cancel",
        "Cancel a workflow after exact approval.",
        "actions:write",
        "/actions/runs/{runId}/cancel",
        method="POST",
        fields={"runId": NUMBER, "expectedSha": SHA, "expectedAttempt": NUMBER},
        required=("runId", "expectedSha", "expectedAttempt"),
        approval=True,
        reconciliation="run_state",
    ),
    action(
        "repository.checks.read",
        "Inspect checks for a commit.",
        "checks:read",
        "/commits/{sha}/check-runs",
        fields=paged(sha=SHA),
        required=("sha",),
        query=("page", "per_page"),
    ),
    action(
        "repository.status.read",
        "Read combined commit status.",
        "statuses:read",
        "/commits/{sha}/status",
        fields={"sha": SHA},
        required=("sha",),
    ),
    action(
        "repository.check.create",
        "Publish an Aduoryn-owned check with grounded test evidence.",
        "checks:write",
        "/check-runs",
        method="POST",
        fields={
            "name": STRING,
            "head_sha": SHA,
            "status": {"enum": ["queued", "in_progress", "completed"]},
            "conclusion": {
                "enum": [
                    "success",
                    "failure",
                    "neutral",
                    "cancelled",
                    "timed_out",
                    "action_required",
                ]
            },
            "output": {
                "type": "object",
                "properties": {"title": STRING, "summary": BODY},
                "required": ["title", "summary"],
                "additionalProperties": False,
            },
        },
        required=("name", "head_sha", "status", "output"),
        reconciliation="external_id",
    ),
    action(
        "repository.releases.read",
        "List releases.",
        "contents:read",
        "/releases",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.release.read",
        "Read a release and its assets.",
        "contents:read",
        "/releases/{releaseId}",
        fields={"releaseId": NUMBER},
        required=("releaseId",),
    ),
    action(
        "repository.release.create",
        "Create a draft release pinned to an observed commit.",
        "contents:write",
        "/releases",
        method="POST",
        fields={
            "tag_name": STRING,
            "target_commitish": SHA,
            "name": STRING,
            "body": BODY,
            "prerelease": {"type": "boolean"},
        },
        required=("tag_name", "target_commitish", "name"),
        reconciliation="tag_marker",
    ),
    action(
        "repository.release.update",
        "Update an unpublished release draft.",
        "contents:write",
        "/releases/{releaseId}",
        method="PATCH",
        fields={"releaseId": NUMBER, "name": STRING, "body": BODY},
        required=("releaseId",),
        reconciliation="exact_fields",
    ),
    action(
        "repository.release.publish",
        "Publish an exactly approved release draft.",
        "contents:write",
        "/releases/{releaseId}",
        method="PATCH",
        fields={
            "releaseId": NUMBER,
            "expectedTag": STRING,
            "expectedBodyHash": {"type": "string", "pattern": "^[a-f0-9]{64}$"},
        },
        required=("releaseId", "expectedTag", "expectedBodyHash"),
        approval=True,
        reconciliation="release_state",
    ),
    action(
        "repository.release.asset.upload",
        "Attach a validated task artifact to a draft release.",
        "contents:write",
        method="POST",
        fields={
            "releaseId": NUMBER,
            "artifactId": STRING,
            "sha256": {"type": "string", "pattern": "^[a-f0-9]{64}$"},
            "name": STRING,
        },
        required=("releaseId", "artifactId", "sha256", "name"),
        reconciliation="asset_digest",
    ),
    action(
        "repository.dependabot.read",
        "Read redacted Dependabot findings; never change security settings.",
        "dependabot_alerts:read",
        "/dependabot/alerts",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.code_scanning.read",
        "Read code scanning summaries without changing alerts.",
        "security_events:read",
        "/code-scanning/alerts",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.deployments.read",
        "Read deployment records; this does not deploy infrastructure.",
        "deployments:read",
        "/deployments",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.deployment.statuses.read",
        "Read deployment status history.",
        "deployments:read",
        "/deployments/{deploymentId}/statuses",
        fields=paged(deploymentId=NUMBER),
        required=("deploymentId",),
        query=("page", "per_page"),
    ),
)
