from ..catalog import BODY, NUMBER, STRING, action

NODE = {"type": "string", "minLength": 1, "maxLength": 255}
CURSOR = {"type": "string", "maxLength": 255}
ACTIONS = (
    action(
        "repository.discussions.search",
        "Search Discussions only in the bound repository.",
        "discussions:read",
        fields={"query": STRING, "after": CURSOR},
        required=("query",),
        graphql="discussions_search",
    ),
    action(
        "project.read",
        "Read a bound Project's fields and paginated items.",
        "organization_projects:read",
        fields={"after": CURSOR},
        resource_type="project",
        graphql="project_read",
    ),
    action(
        "project.item.add",
        "Add an authorized repository issue or PR to this exact Project.",
        "organization_projects:write",
        method="POST",
        fields={"contentId": NODE},
        required=("contentId",),
        resource_type="project",
        graphql="project_add",
        reconciliation="project_content",
    ),
    action(
        "project.item.update",
        "Update a Project item's exact field value.",
        "organization_projects:write",
        method="POST",
        fields={
            "itemId": NODE,
            "fieldId": NODE,
            "value": {
                "type": "object",
                "properties": {
                    "text": BODY,
                    "number": {"type": "number"},
                    "date": STRING,
                    "singleSelectOptionId": NODE,
                    "iterationId": NODE,
                },
                "minProperties": 1,
                "maxProperties": 1,
                "additionalProperties": False,
            },
        },
        required=("itemId", "fieldId", "value"),
        resource_type="project",
        graphql="project_update",
        reconciliation="exact_fields",
    ),
    action(
        "project.item.archive",
        "Archive an item on this exact Project.",
        "organization_projects:write",
        method="POST",
        fields={"itemId": NODE},
        required=("itemId",),
        resource_type="project",
        graphql="project_archive",
        reconciliation="exact_fields",
    ),
    action(
        "repository.discussions.read",
        "Read repository Discussions with pagination.",
        "discussions:read",
        fields={"after": CURSOR},
        graphql="discussions_read",
    ),
    action(
        "repository.discussion.read",
        "Read a Discussion and its comments.",
        "discussions:read",
        fields={"number": NUMBER, "after": CURSOR},
        required=("number",),
        graphql="discussion_read",
    ),
    action(
        "repository.discussion.categories.read",
        "Read available Discussion categories.",
        "discussions:read",
        graphql="discussion_categories",
    ),
    action(
        "repository.discussion.create",
        "Create an authorized Discussion in an observed category.",
        "discussions:write",
        method="POST",
        fields={"categoryId": NODE, "title": STRING, "body": BODY},
        required=("categoryId", "title", "body"),
        graphql="discussion_create",
        reconciliation="body_marker",
    ),
    action(
        "repository.discussion.comment.create",
        "Comment on an observed Discussion.",
        "discussions:write",
        method="POST",
        fields={"discussionId": NODE, "body": BODY},
        required=("discussionId", "body"),
        graphql="discussion_comment",
        reconciliation="body_marker",
    ),
    action(
        "repository.discussion.update",
        "Update only an Aduoryn-authored Discussion.",
        "discussions:write",
        method="POST",
        fields={"discussionId": NODE, "title": STRING, "body": BODY},
        required=("discussionId", "title", "body"),
        graphql="discussion_update",
        reconciliation="exact_fields",
    ),
)
