from ..catalog import BODY, NUMBER, STRING, STRINGS, action, paged

ACTIONS = (
    action(
        "repository.issues.read",
        "Read open repository issues (legacy compatible).",
        "issues:read",
        "/issues",
    ),
    action(
        "repository.issues.list",
        "List paginated issues with state and labels.",
        "issues:read",
        "/issues",
        fields=paged(state={"enum": ["open", "closed", "all"]}, labels=STRING),
        query=("page", "per_page", "state", "labels"),
    ),
    action(
        "repository.issues.search",
        "Search issues only in the authorized repository.",
        "issues:read",
        fields=paged(query=STRING),
        required=("query",),
    ),
    action(
        "repository.issue.read",
        "Read an issue with body and completion state.",
        "issues:read",
        "/issues/{number}",
        fields={"number": NUMBER},
        required=("number",),
    ),
    action(
        "repository.issue.create",
        "Create an issue within the explicit task grant.",
        "issues:write",
        "/issues",
        method="POST",
        fields={
            "title": {**STRING, "maxLength": 256},
            "body": BODY,
            "labels": {
                "type": "array",
                "maxItems": 10,
                "items": {"type": "string", "maxLength": 50},
            },
        },
        required=("title",),
        scope_alias="github.repository.issues.create",
        reconciliation="body_marker",
    ),
    action(
        "repository.issue.update",
        "Update an issue, including close/reopen, within the task objective.",
        "issues:write",
        "/issues/{number}",
        method="PATCH",
        fields={
            "number": NUMBER,
            "title": STRING,
            "body": BODY,
            "state": {"enum": ["open", "closed"]},
            "labels": STRINGS,
            "assignees": STRINGS,
            "milestone": NUMBER,
        },
        required=("number",),
        reconciliation="exact_fields",
    ),
    action(
        "repository.issue.comments.read",
        "Read paginated issue or PR conversation comments.",
        "issues:read",
        "/issues/{number}/comments",
        fields=paged(number=NUMBER),
        required=("number",),
        query=("page", "per_page"),
    ),
    action(
        "repository.issue.comment.create",
        "Post a task-authorized issue or PR comment.",
        "issues:write",
        "/issues/{number}/comments",
        method="POST",
        fields={"number": NUMBER, "body": BODY},
        required=("number", "body"),
        reconciliation="body_marker",
    ),
    action(
        "repository.issue.labels.set",
        "Set the issue's labels.",
        "issues:write",
        "/issues/{number}/labels",
        method="PUT",
        fields={"number": NUMBER, "labels": STRINGS},
        required=("number", "labels"),
        reconciliation="exact_fields",
    ),
    action(
        "repository.labels.read",
        "List repository labels.",
        "issues:read",
        "/labels",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.label.create",
        "Create a repository label.",
        "issues:write",
        "/labels",
        method="POST",
        fields={
            "name": STRING,
            "color": {"type": "string", "pattern": "^[a-fA-F0-9]{6}$"},
            "description": BODY,
        },
        required=("name", "color"),
        reconciliation="named_object",
    ),
    action(
        "repository.label.update",
        "Update a repository label.",
        "issues:write",
        "/labels/{name}",
        method="PATCH",
        fields={
            "name": STRING,
            "new_name": STRING,
            "color": {"type": "string", "pattern": "^[a-fA-F0-9]{6}$"},
            "description": BODY,
        },
        required=("name",),
        reconciliation="exact_fields",
    ),
    action(
        "repository.milestones.read",
        "List milestones.",
        "issues:read",
        "/milestones",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.milestone.create",
        "Create a milestone.",
        "issues:write",
        "/milestones",
        method="POST",
        fields={"title": STRING, "description": BODY, "due_on": STRING},
        required=("title",),
        reconciliation="body_marker",
    ),
    action(
        "repository.milestone.update",
        "Update milestone state or details.",
        "issues:write",
        "/milestones/{number}",
        method="PATCH",
        fields={
            "number": NUMBER,
            "title": STRING,
            "description": BODY,
            "state": {"enum": ["open", "closed"]},
            "due_on": STRING,
        },
        required=("number",),
        reconciliation="exact_fields",
    ),
)
