from ..catalog import BODY, NUMBER, SHA, STRING, STRINGS, action, paged

NODE = {"type": "string", "minLength": 1, "maxLength": 255}
ACTIONS = (
    action(
        "repository.pull_requests.read",
        "Read open pull requests (legacy compatible).",
        "pull_requests:read",
        "/pulls",
    ),
    action(
        "repository.pull_requests.list",
        "List paginated pull requests.",
        "pull_requests:read",
        "/pulls",
        fields=paged(state={"enum": ["open", "closed", "all"]}, head=STRING, base=STRING),
        query=("page", "per_page", "state", "head", "base"),
    ),
    action(
        "repository.pull_request.read",
        "Read PR details, head SHA, mergeability and review state.",
        "pull_requests:read",
        "/pulls/{number}",
        fields={"number": NUMBER},
        required=("number",),
    ),
    action(
        "repository.pull_request.files.read",
        "Read PR file patches; pagination and missing patches are explicit.",
        "pull_requests:read",
        "/pulls/{number}/files",
        fields=paged(number=NUMBER),
        required=("number",),
        query=("page", "per_page"),
    ),
    action(
        "repository.pull_request.create",
        "Open a draft pull request from an authorized task branch.",
        "pull_requests:write",
        "/pulls",
        method="POST",
        fields={"title": STRING, "body": BODY, "head": STRING, "base": STRING},
        required=("title", "head", "base"),
        reconciliation="body_marker",
    ),
    action(
        "repository.pull_request.update",
        "Update PR title, body, or open/closed state.",
        "pull_requests:write",
        "/pulls/{number}",
        method="PATCH",
        fields={
            "number": NUMBER,
            "title": STRING,
            "body": BODY,
            "state": {"enum": ["open", "closed"]},
        },
        required=("number",),
        reconciliation="exact_fields",
    ),
    action(
        "repository.pull_request.reviewers.request",
        "Request named reviewers or teams.",
        "pull_requests:write",
        "/pulls/{number}/requested_reviewers",
        method="POST",
        fields={"number": NUMBER, "reviewers": STRINGS, "team_reviewers": STRINGS},
        required=("number",),
        reconciliation="exact_fields",
    ),
    action(
        "repository.pull_request.ready",
        "Mark an authorized draft PR ready for review.",
        "pull_requests:write",
        method="POST",
        fields={"nodeId": NODE},
        required=("nodeId",),
        graphql="ready",
        reconciliation="exact_fields",
    ),
    action(
        "repository.pull_request.branch.update",
        "Update a PR branch with the base after checking its exact head SHA.",
        "pull_requests:write",
        "/pulls/{number}/update-branch",
        method="PUT",
        fields={"number": NUMBER, "expected_head_sha": SHA},
        required=("number", "expected_head_sha"),
        reconciliation="pr_head",
    ),
    action(
        "repository.pull_request.merge",
        "Merge only an approved exact head revision when GitHub protections and required checks pass.",
        "contents:write",
        "/pulls/{number}/merge",
        method="PUT",
        fields={
            "number": NUMBER,
            "sha": SHA,
            "merge_method": {"enum": ["merge", "squash", "rebase"]},
        },
        required=("number", "sha"),
        approval=True,
        reconciliation="merged_sha",
    ),
    action(
        "repository.reviews.read",
        "Read PR reviews.",
        "pull_requests:read",
        "/pulls/{number}/reviews",
        fields=paged(number=NUMBER),
        required=("number",),
        query=("page", "per_page"),
    ),
    action(
        "repository.review.comments.read",
        "Read file/line review comments.",
        "pull_requests:read",
        "/pulls/{number}/comments",
        fields=paged(number=NUMBER),
        required=("number",),
        query=("page", "per_page"),
    ),
    action(
        "repository.review.comment.create",
        "Add a review comment grounded in an observed file and commit.",
        "pull_requests:write",
        "/pulls/{number}/comments",
        method="POST",
        fields={
            "number": NUMBER,
            "body": BODY,
            "commit_id": SHA,
            "path": STRING,
            "line": NUMBER,
            "side": {"enum": ["LEFT", "RIGHT"]},
        },
        required=("number", "body", "commit_id", "path", "line", "side"),
        reconciliation="body_marker",
    ),
    action(
        "repository.review.submit",
        "Submit a formal review against an exact PR commit.",
        "pull_requests:write",
        "/pulls/{number}/reviews",
        method="POST",
        fields={
            "number": NUMBER,
            "commit_id": SHA,
            "body": BODY,
            "event": {"enum": ["COMMENT", "APPROVE", "REQUEST_CHANGES"]},
        },
        required=("number", "commit_id", "body", "event"),
        approval=True,
        reconciliation="body_marker",
    ),
    action(
        "repository.review.thread.resolve",
        "Resolve an observed review thread on this repository.",
        "pull_requests:write",
        method="POST",
        fields={"threadId": NODE},
        required=("threadId",),
        graphql="resolve",
        reconciliation="exact_fields",
    ),
)
