from ..catalog import BODY, SHA, STRING, action, paged

ACTIONS = (
    action(
        "repository.metadata.read",
        "Read repository identity, default branch and access state.",
        "metadata:read",
        "",
    ),
    action(
        "repository.readme.read",
        "Read the repository README at an observed revision.",
        "contents:read",
        "/readme",
        fields={"ref": STRING},
        query=("ref",),
    ),
    action(
        "repository.contents.read",
        "Inspect exactly one file or directory path at a revision. Confirmed absence is evidence, not a task failure; additional paths require separate actions.",
        "contents:read",
        "/contents/{path}",
        fields={"path": STRING, "ref": STRING},
        required=("path",),
        query=("ref",),
    ),
    action(
        "repository.tree.read",
        "Read a Git tree; truncated trees require inspecting subtrees.",
        "contents:read",
        "/git/trees/{sha}",
        prerequisites=("github.repository.branch.read",),
        fields={"sha": SHA, "recursive": {"type": "boolean"}},
        required=("sha",),
        query=("recursive",),
    ),
    action(
        "repository.branches.read",
        "List branches with protection information.",
        "contents:read",
        "/branches",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.branch.read",
        "Inspect one branch and its current commit.",
        "contents:read",
        "/branches/{branch}",
        prerequisites=("github.repository.metadata.read",),
        fields={"branch": STRING},
        required=("branch",),
    ),
    action(
        "repository.tags.read",
        "List tags and their commit identities.",
        "contents:read",
        "/tags",
        fields=paged(),
        query=("page", "per_page"),
    ),
    action(
        "repository.commits.read",
        "Inspect paginated commit history.",
        "contents:read",
        "/commits",
        fields=paged(sha=STRING, path=STRING),
        query=("page", "per_page", "sha", "path"),
    ),
    action(
        "repository.commit.read",
        "Read an exact commit and its file changes.",
        "contents:read",
        "/commits/{sha}",
        prerequisites=("github.repository.branch.read",),
        fields={"sha": SHA},
        required=("sha",),
    ),
    action(
        "repository.compare.read",
        "Compare two observed revisions.",
        "contents:read",
        "/compare/{base}...{head}",
        fields={"base": STRING, "head": STRING},
        required=("base", "head"),
    ),
    action(
        "repository.code.search",
        "Search code only inside this authorized repository.",
        "contents:read",
        fields=paged(query=STRING),
        required=("query",),
    ),
    action(
        "repository.branch.create",
        "Create a task branch from an observed commit.",
        "contents:write",
        "/git/refs",
        method="POST",
        fields={"branch": STRING, "sha": SHA},
        required=("branch", "sha"),
        reconciliation="branch_sha",
        prerequisites=("github.repository.branch.read",),
    ),
    action(
        "repository.commit.create",
        "Publish validated file changes atomically on a task branch; never force-push.",
        "contents:write",
        method="POST",
        fields={
            "branch": STRING,
            "baseSha": SHA,
            "message": BODY,
            "changes": {
                "type": "array",
                "minItems": 1,
                "maxItems": 100,
                "items": {
                    "type": "object",
                    "properties": {
                        "path": STRING,
                        "content": {"type": "string", "maxLength": 1000000},
                        "delete": {"type": "boolean"},
                    },
                    "required": ["path"],
                    "additionalProperties": False,
                },
            },
        },
        required=("branch", "baseSha", "message", "changes"),
        reconciliation="commit_marker",
        prerequisites=("github.repository.branch.read",),
    ),
    action(
        "repository.branch.update",
        "Fast-forward a task branch to an observed descendant commit.",
        "contents:write",
        "/git/refs/heads/{branch}",
        method="PATCH",
        fields={"branch": STRING, "sha": SHA, "expectedSha": SHA},
        required=("branch", "sha", "expectedSha"),
        reconciliation="branch_sha",
    ),
)
