import { error, json, requireAuth, router } from '@appdeploy/sdk';
import { AgentDomainError, createAgent, listAgentsForUser, revokeAgentCredential, rotateAgentCredential, serializeAgentV2, setAgentStatus } from './core/agents';
import { CapabilityDomainError, getAgentCapabilityProfile, listCapabilityCatalog, serializeCapabilityCatalogV2, serializeCapabilityProfileV2, setAgentCapabilityProfile } from './core/capabilities';
import { createPolicy, evaluatePolicyForUser, listPoliciesForUser, PolicyDomainError, serializePolicyDecisionV2, serializePolicyV2, setPolicyStatus, updatePolicy } from './core/policies';
import { checkIntegrationHealth, connectGitHub, disconnectIntegration, getIntegrationSecurityStatus, IntegrationDomainError, listIntegrationsForUser, serializeIntegrationV2 } from './core/integrations';
import { createOrganization, listOrganizationsForUser, serializeOrganizationsV1, serializeOrganizationsV2 } from './core/organizations';
import { readCanonicalSystemStatus, serializeV1, serializeV2 } from './core/system';
import { ActionGatewayDomainError, executeActionForAgent, extractAgentCredential, listActionsForUser, serializeActionV2, testActionForUser } from './core/actionGateway';
import { realtimeSubscriptionRoutes } from './realtime-subscribers';
function messageOf(value: unknown) { return value instanceof Error ? value.message : 'Unexpected error.'; }
function statusOf(value: unknown) { return value instanceof AgentDomainError || value instanceof IntegrationDomainError || value instanceof CapabilityDomainError || value instanceof PolicyDomainError || value instanceof ActionGatewayDomainError ? value.statusCode : 400; }
function runtimeStatus(status: string) { return status === 'held' || status === 'processing' ? 202 : status === 'blocked' ? 403 : status === 'failed' ? 502 : 200; }
export const handler = router({
'GET /api/_healthcheck':[async()=>json({message:'Success'})],
'GET /api/v1/system/status':[async()=>json(serializeV1(readCanonicalSystemStatus()))],
'GET /api/v2/system/status':[async()=>json(serializeV2(readCanonicalSystemStatus()))],
'GET /api/v1/me':[requireAuth(),async(ctx)=>json({user:{id:ctx.user!.userId,email:ctx.user!.email??null,name:ctx.user!.name??null}})],
'GET /api/v2/me':[requireAuth(),async(ctx)=>json({identity:{subject:ctx.user!.userId,email:ctx.user!.email??null,displayName:ctx.user!.name??null,type:'human'}})],
'GET /api/v1/organizations':[requireAuth(),async(ctx)=>json(serializeOrganizationsV1(await listOrganizationsForUser(ctx.user!.userId)))],
'GET /api/v2/organizations':[requireAuth(),async(ctx)=>json(serializeOrganizationsV2(await listOrganizationsForUser(ctx.user!.userId)))],
'POST /api/v1/organizations':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{name?:unknown};return json({organization:await createOrganization(ctx.user!.userId,body?.name)},201)}catch(caught){return error(messageOf(caught),400)}}],
'POST /api/v2/organizations':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{name?:unknown};const organization=await createOrganization(ctx.user!.userId,body?.name);return json({data:{organization:{id:organization.id,name:organization.name,createdAt:organization.createdAt},membership:{role:organization.role,permissions:organization.permissions}}},201)}catch(caught){return error(messageOf(caught),400)}}],
'GET /api/v1/organizations/:organizationId/agents':[requireAuth(),async(ctx)=>{try{const agents=await listAgentsForUser(ctx.user!.userId,ctx.params.organizationId);return json({agents,count:agents.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/agents':[requireAuth(),async(ctx)=>{try{const agents=await listAgentsForUser(ctx.user!.userId,ctx.params.organizationId);return json({items:agents.map(serializeAgentV2),total:agents.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/agents':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{name?:unknown;description?:unknown};return json(await createAgent(ctx.user!.userId,ctx.params.organizationId,body?.name,body?.description),201)}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/agents':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{name?:unknown;description?:unknown};const result=await createAgent(ctx.user!.userId,ctx.params.organizationId,body?.name,body?.description);return json({data:{agent:serializeAgentV2(result.agent),credential:result.credential}},201)}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'PUT /api/v1/organizations/:organizationId/agents/:agentId/lifecycle':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{status?:unknown};return json({agent:await setAgentStatus(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId,body?.status)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'PUT /api/v2/organizations/:organizationId/agents/:agentId/lifecycle':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{status?:unknown};return json({data:{agent:serializeAgentV2(await setAgentStatus(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId,body?.status))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/agents/:agentId/credentials/rotate':[requireAuth(),async(ctx)=>{try{return json(await rotateAgentCredential(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId))}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/agents/:agentId/credentials/rotate':[requireAuth(),async(ctx)=>{try{const result=await rotateAgentCredential(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId);return json({data:{agent:serializeAgentV2(result.agent),credential:result.credential}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/agents/:agentId/credentials/revoke':[requireAuth(),async(ctx)=>{try{return json({agent:await revokeAgentCredential(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/agents/:agentId/credentials/revoke':[requireAuth(),async(ctx)=>{try{return json({data:{agent:serializeAgentV2(await revokeAgentCredential(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v1/organizations/:organizationId/integrations/security':[requireAuth(),async(ctx)=>{try{return json({security:await getIntegrationSecurityStatus(ctx.user!.userId,ctx.params.organizationId)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/integrations/security':[requireAuth(),async(ctx)=>{try{return json({data:{security:await getIntegrationSecurityStatus(ctx.user!.userId,ctx.params.organizationId)}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v1/organizations/:organizationId/integrations':[requireAuth(),async(ctx)=>{try{const integrations=await listIntegrationsForUser(ctx.user!.userId,ctx.params.organizationId);return json({integrations,count:integrations.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/integrations':[requireAuth(),async(ctx)=>{try{const integrations=await listIntegrationsForUser(ctx.user!.userId,ctx.params.organizationId);return json({items:integrations.map(serializeIntegrationV2),total:integrations.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/integrations/github':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{repository?:unknown;token?:unknown};return json({integration:await connectGitHub(ctx.user!.userId,ctx.params.organizationId,body?.repository,body?.token)},201)}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/integrations/github':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{repository?:unknown;token?:unknown};return json({data:{integration:serializeIntegrationV2(await connectGitHub(ctx.user!.userId,ctx.params.organizationId,body?.repository,body?.token))}},201)}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/integrations/:integrationId/check':[requireAuth(),async(ctx)=>{try{return json({integration:await checkIntegrationHealth(ctx.user!.userId,ctx.params.organizationId,ctx.params.integrationId)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/integrations/:integrationId/check':[requireAuth(),async(ctx)=>{try{return json({data:{integration:serializeIntegrationV2(await checkIntegrationHealth(ctx.user!.userId,ctx.params.organizationId,ctx.params.integrationId))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'DELETE /api/v1/organizations/:organizationId/integrations/:integrationId':[requireAuth(),async(ctx)=>{try{return json({integration:await disconnectIntegration(ctx.user!.userId,ctx.params.organizationId,ctx.params.integrationId)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'DELETE /api/v2/organizations/:organizationId/integrations/:integrationId':[requireAuth(),async(ctx)=>{try{return json({data:{integration:serializeIntegrationV2(await disconnectIntegration(ctx.user!.userId,ctx.params.organizationId,ctx.params.integrationId))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v1/organizations/:organizationId/capabilities':[requireAuth(),async(ctx)=>{try{const catalog=await listCapabilityCatalog(ctx.user!.userId,ctx.params.organizationId);return json({resources:catalog.resources,scopes:catalog.scopes,summary:catalog.summary})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/capabilities':[requireAuth(),async(ctx)=>{try{return json({data:serializeCapabilityCatalogV2(await listCapabilityCatalog(ctx.user!.userId,ctx.params.organizationId))})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v1/organizations/:organizationId/agents/:agentId/capabilities':[requireAuth(),async(ctx)=>{try{return json({profile:await getAgentCapabilityProfile(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/agents/:agentId/capabilities':[requireAuth(),async(ctx)=>{try{return json({data:serializeCapabilityProfileV2(await getAgentCapabilityProfile(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId))})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'PUT /api/v1/organizations/:organizationId/agents/:agentId/capabilities':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{scopes?:unknown};return json({profile:await setAgentCapabilityProfile(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId,body?.scopes)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'PUT /api/v2/organizations/:organizationId/agents/:agentId/capabilities':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{scopes?:unknown};return json({data:serializeCapabilityProfileV2(await setAgentCapabilityProfile(ctx.user!.userId,ctx.params.organizationId,ctx.params.agentId,body?.scopes))})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v1/organizations/:organizationId/policies':[requireAuth(),async(ctx)=>{try{const policies=await listPoliciesForUser(ctx.user!.userId,ctx.params.organizationId);return json({policies,count:policies.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/policies':[requireAuth(),async(ctx)=>{try{const policies=await listPoliciesForUser(ctx.user!.userId,ctx.params.organizationId);return json({items:policies.map(serializePolicyV2),total:policies.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/policies':[requireAuth(),async(ctx)=>{try{return json({policy:await createPolicy(ctx.user!.userId,ctx.params.organizationId,ctx.body)},201)}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/policies':[requireAuth(),async(ctx)=>{try{return json({data:{policy:serializePolicyV2(await createPolicy(ctx.user!.userId,ctx.params.organizationId,ctx.body))}},201)}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'PUT /api/v1/organizations/:organizationId/policies/:policyId':[requireAuth(),async(ctx)=>{try{return json({policy:await updatePolicy(ctx.user!.userId,ctx.params.organizationId,ctx.params.policyId,ctx.body)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'PUT /api/v2/organizations/:organizationId/policies/:policyId':[requireAuth(),async(ctx)=>{try{return json({data:{policy:serializePolicyV2(await updatePolicy(ctx.user!.userId,ctx.params.organizationId,ctx.params.policyId,ctx.body))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/policies/:policyId/status':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{status?:unknown};return json({policy:await setPolicyStatus(ctx.user!.userId,ctx.params.organizationId,ctx.params.policyId,body?.status)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/policies/:policyId/status':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{status?:unknown};return json({data:{policy:serializePolicyV2(await setPolicyStatus(ctx.user!.userId,ctx.params.organizationId,ctx.params.policyId,body?.status))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/policy-evaluations':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{agentId?:unknown;resourceId?:unknown;scope?:unknown};return json({decision:await evaluatePolicyForUser(ctx.user!.userId,ctx.params.organizationId,body?.agentId,body?.resourceId,body?.scope)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/policy-evaluations':[requireAuth(),async(ctx)=>{try{const body=ctx.body as{agentId?:unknown;resourceId?:unknown;scope?:unknown};return json({data:serializePolicyDecisionV2(await evaluatePolicyForUser(ctx.user!.userId,ctx.params.organizationId,body?.agentId,body?.resourceId,body?.scope))})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v1/organizations/:organizationId/actions':[requireAuth(),async(ctx)=>{try{const actions=await listActionsForUser(ctx.user!.userId,ctx.params.organizationId);return json({actions,count:actions.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'GET /api/v2/organizations/:organizationId/actions':[requireAuth(),async(ctx)=>{try{const actions=await listActionsForUser(ctx.user!.userId,ctx.params.organizationId);return json({items:actions.map(serializeActionV2),total:actions.length})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/organizations/:organizationId/action-gateway/tests':[requireAuth(),async(ctx)=>{try{return json({action:await testActionForUser(ctx.user!.userId,ctx.params.organizationId,ctx.body)})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/organizations/:organizationId/action-gateway/tests':[requireAuth(),async(ctx)=>{try{return json({data:{action:serializeActionV2(await testActionForUser(ctx.user!.userId,ctx.params.organizationId,ctx.body))}})}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v1/runtime/organizations/:organizationId/agents/:agentId/actions':[async(ctx)=>{try{const action=await executeActionForAgent(ctx.params.organizationId,ctx.params.agentId,extractAgentCredential(ctx.event),ctx.body);return json({action},runtimeStatus(action.status))}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
'POST /api/v2/runtime/organizations/:organizationId/agents/:agentId/actions':[async(ctx)=>{try{const action=await executeActionForAgent(ctx.params.organizationId,ctx.params.agentId,extractAgentCredential(ctx.event),ctx.body);return json({data:{action:serializeActionV2(action)}},runtimeStatus(action.status))}catch(caught){return error(messageOf(caught),statusOf(caught))}}],
...realtimeSubscriptionRoutes,
});
