import ActivityStage from './operations/ActivityStage';
import { useEffect,useMemo,useState } from 'react';

import { listActions,runGatewayTest,type ActionRecord } from '../lib/actionApi';
import { listAgents,type AgentIdentity } from '../lib/agentApi';
import { listCapabilityCatalog,type CapabilityCatalog } from '../lib/capabilityApi';
import type { OrganizationAccess } from '../lib/identityApi';
import type { ApiVersion } from '../lib/systemApi';
interface Props{organization:OrganizationAccess;apiVersion:ApiVersion;onApiVersionChange:(version:ApiVersion)=>void}
function newKey(){return `gate_${crypto.randomUUID()}`}
export default function ActionsPanel({organization,apiVersion,onApiVersionChange}:Props){const[actions,setActions]=useState<ActionRecord[]>([]);const[agents,setAgents]=useState<AgentIdentity[]>([]);const[catalog,setCatalog]=useState<CapabilityCatalog|null>(null);const[agentId,setAgentId]=useState('');const[resourceId,setResourceId]=useState('');const[scope,setScope]=useState('');const[credential,setCredential]=useState('');const[idempotencyKey,setIdempotencyKey]=useState(newKey);const[loading,setLoading]=useState(true);const[running,setRunning]=useState(false);const[error,setError]=useState<string|null>(null);const[last,setLast]=useState<ActionRecord|null>(null);const canManage=organization.permissions.includes('actions.manage');const resource=useMemo(()=>catalog?.resources.find((item)=>item.id===resourceId)??null,[catalog,resourceId]);const scopes=resource?.actions??[];
async function hydrate(){setLoading(true);setError(null);try{const[nextActions,nextAgents,nextCatalog]=await Promise.all([listActions(apiVersion,organization.id),listAgents(apiVersion,organization.id),listCapabilityCatalog(apiVersion,organization.id)]);setActions(nextActions);setAgents(nextAgents);setCatalog(nextCatalog);setAgentId((current)=>current&&nextAgents.some((item)=>item.id===current)?current:nextAgents[0]?.id??'');setResourceId((current)=>current&&nextCatalog.resources.some((item)=>item.id===current)?current:nextCatalog.resources[0]?.id??'')}catch(caught){setError(message(caught))}finally{setLoading(false)}}
useEffect(()=>{void hydrate()},[apiVersion,organization.id]);useEffect(()=>{if(!resource){setScope('');return}if(!resource.actions.some((item)=>item.scope===scope))setScope(resource.actions[0]?.scope??'')},[resourceId,catalog]);
async function run(){if(!agentId||!resourceId||!scope||!credential)return;setRunning(true);setError(null);try{const result=await runGatewayTest(apiVersion,organization.id,{agentId,credential,resourceId,scope,idempotencyKey});setLast(result);setCredential('');setActions((current)=>[result,...current.filter((item)=>item.id!==result.id)])}catch(caught){setError(message(caught))}finally{setRunning(false)}}
return <ActivityStage actions={actions} agents={agents} catalog={catalog} scopes={scopes} selected={last} agentId={agentId} resourceId={resourceId} scope={scope} credential={credential} idempotencyKey={idempotencyKey} loading={loading} running={running} error={error} canManage={canManage} apiVersion={apiVersion} onVersion={onApiVersionChange} onRefresh={()=>void hydrate()} onSelect={setLast} onAgent={setAgentId} onResource={setResourceId} onScope={setScope} onCredential={setCredential} onKey={setIdempotencyKey} onNewKey={()=>setIdempotencyKey(newKey())} onRun={()=>void run()}/>}
function message(value:unknown){const data=value as{response?:{data?:{error?:string}};message?:string};return data.response?.data?.error||data.message||'Action Gateway request failed.'}
