import ApprovalStage from './operations/ApprovalStage';
import { useEffect,useMemo,useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { decideApproval,enableApprovalNotifications,getApprovalNotificationState,listApprovals,onApprovalNotification,type ApprovalNotificationState,type ApprovalRecord } from '../lib/approvalApi';
import type { OrganizationAccess } from '../lib/identityApi';
import type { ApiVersion } from '../lib/systemApi';
import { subscribeOrganizationRealtime } from '../platform/realtimeClient';
import '../approvals.css';
interface Props{organization:OrganizationAccess;apiVersion:ApiVersion;onApiVersionChange:(version:ApiVersion)=>void}
export default function ApprovalsPanel({organization,apiVersion,onApiVersionChange}:Props){const canReview=organization.permissions.includes('approvals.review');const[approvals,setApprovals]=useState<ApprovalRecord[]>([]);const[selectedId,setSelectedId]=useState('');const[note,setNote]=useState('');const[loading,setLoading]=useState(true);const[deciding,setDeciding]=useState(false);const[error,setError]=useState<string|null>(null);const[push,setPush]=useState<ApprovalNotificationState|null>(null);const[selected]=[useMemo(()=>approvals.find((item)=>item.id===selectedId)??approvals[0]??null,[approvals,selectedId])];async function hydrate(showLoading=true){if(!canReview){setLoading(false);return}if(showLoading)setLoading(true);setError(null);try{const items=await listApprovals(apiVersion,organization.id);setApprovals(items);setSelectedId((current)=>current&&items.some((item)=>item.id===current)?current:items[0]?.id??'')}catch(caught){setError(message(caught))}finally{if(showLoading)setLoading(false)}}
useEffect(()=>{void hydrate();void getApprovalNotificationState().then(setPush).catch(()=>{});const off=onApprovalNotification(()=>void hydrate(false));return off},[apiVersion,organization.id,canReview]);useEffect(()=>{if(!canReview)return;return subscribeOrganizationRealtime({organizationId:organization.id,eventTypes:['approval.created','approval.decided','action.approved','action.blocked','action.executed','run.waiting_approval'],onEvent:()=>void hydrate(false),poll:()=>hydrate(false)})},[apiVersion,organization.id,canReview]);async function decide(decision:'approve'|'reject'){if(!selected)return;setDeciding(true);setError(null);try{const updated=await decideApproval(apiVersion,organization.id,selected.id,decision,note);setApprovals((current)=>current.map((item)=>item.id===updated.id?updated:item));setSelectedId(updated.id);setNote('')}catch(caught){setError(message(caught))}finally{setDeciding(false)}}async function enablePush(){setError(null);try{setPush(await enableApprovalNotifications())}catch(caught){setError(message(caught))}}if(!canReview)return <><section className="page-heading"><div><p className="eyebrow">HUMAN APPROVALS</p><h1>Approval queue</h1><p className="page-subtitle">Your organization role does not include approval review authority.</p></div></section><section className="panel"><div className="empty-state"><ShieldCheck size={20}/><strong>Reviewer permission required</strong><p>Only roles with approvals.review can inspect or decide held agent actions.</p></div></section></>;return <ApprovalStage approvals={approvals} selected={selected} note={note} loading={loading} deciding={deciding} error={error} push={push} apiVersion={apiVersion} onVersion={onApiVersionChange} onRefresh={()=>void hydrate()} onSelect={setSelectedId} onNote={setNote} onDecide={decision=>void decide(decision)} onEnablePush={()=>void enablePush()}/>}
function message(value:unknown){const data=value as{response?:{data?:{error?:string}};message?:string};return data.response?.data?.error||data.message||'Approval request failed.'}
