import { CapabilitiesStage } from './ConnectionsStages';
import { useEffect, useMemo, useState } from 'react';

import { listAgents, type AgentIdentity } from '../lib/agentApi';
import { getAgentCapabilityProfile, listCapabilityCatalog, saveAgentCapabilityProfile, type AgentCapabilityProfile, type CapabilityCatalog } from '../lib/capabilityApi';
import type { OrganizationAccess } from '../lib/identityApi';
import type { ApiVersion } from '../lib/systemApi';
interface Props { organization: OrganizationAccess; apiVersion: ApiVersion; onApiVersionChange: (version: ApiVersion) => void; }
export default function CapabilitiesPanel({ organization, apiVersion, onApiVersionChange }: Props) { const [catalog,setCatalog]=useState<CapabilityCatalog|null>(null); const [agents,setAgents]=useState<AgentIdentity[]>([]); const [selectedResourceId,setSelectedResourceId]=useState<string|null>(null); const [selectedAgentId,setSelectedAgentId]=useState<string>(''); const [profile,setProfile]=useState<AgentCapabilityProfile|null>(null); const [draftScopes,setDraftScopes]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [profileLoading,setProfileLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const canManage=organization.permissions.includes('capabilities.manage'); const selectedResource=useMemo(()=>catalog?.resources.find((resource)=>resource.id===selectedResourceId)??null,[catalog,selectedResourceId]);
async function hydrate(){setLoading(true);setError(null);try{const [nextCatalog,nextAgents]=await Promise.all([listCapabilityCatalog(apiVersion,organization.id),listAgents(apiVersion,organization.id)]);setCatalog(nextCatalog);setAgents(nextAgents);setSelectedResourceId((current)=>current&&nextCatalog.resources.some((item)=>item.id===current)?current:nextCatalog.resources[0]?.id??null);setSelectedAgentId((current)=>current&&nextAgents.some((item)=>item.id===current)?current:nextAgents[0]?.id??'')}catch(caught){setError(message(caught))}finally{setLoading(false)}}
useEffect(()=>{void hydrate()},[apiVersion,organization.id]);
useEffect(()=>{if(!selectedAgentId){setProfile(null);setDraftScopes([]);return}let current=true;setProfile(null);setDraftScopes([]);setProfileLoading(true);setError(null);void getAgentCapabilityProfile(apiVersion,organization.id,selectedAgentId).then(next=>{if(!current)return;setProfile(next);setDraftScopes(next.declaredScopes)}).catch(caught=>{if(!current)return;setError(message(caught));setProfile(null);setDraftScopes([])}).finally(()=>{if(current)setProfileLoading(false)});return()=>{current=false}},[selectedAgentId,apiVersion,organization.id]);
function toggle(scope:string){setDraftScopes((current)=>current.includes(scope)?current.filter((item)=>item!==scope):[...current,scope].sort())}
async function save(){if(!selectedAgentId)return;setSaving(true);setError(null);try{const next=await saveAgentCapabilityProfile(apiVersion,organization.id,selectedAgentId,draftScopes);setProfile(next);setDraftScopes(next.declaredScopes)}catch(caught){setError(message(caught))}finally{setSaving(false)}}
return <CapabilitiesStage apiVersion={apiVersion} onApiVersionChange={onApiVersionChange} catalog={catalog} agents={agents} selectedResource={selectedResource} selectResource={setSelectedResourceId} selectedAgentId={selectedAgentId} selectAgent={setSelectedAgentId} profile={profile} draftScopes={draftScopes} toggleScope={toggle} discard={()=>setDraftScopes(profile?.declaredScopes??[])} save={()=>void save()} canManage={canManage} loading={loading} profileLoading={profileLoading} saving={saving} error={error}/>}
function message(value:unknown){const data=value as{response?:{data?:{error?:string}};message?:string};return data.response?.data?.error||data.message||'Capability request failed.'}
