import type { ReactNode } from 'react';
import { Activity, ArrowDownRight, ArrowRight, Check, ChevronRight, CirclePause, FileSearch, Fingerprint, Loader2, Plus, RotateCcw, Search, Shield, ShieldAlert, ShieldCheck, SlidersHorizontal, X } from 'lucide-react';
import type { AgentIdentity } from '../lib/agentApi';
import type { CapabilityCatalog } from '../lib/capabilityApi';
import type { AuditCategory, AuditEvent, AuditResult, AuditSeverity } from '../lib/auditApi';
import type { ExecutionControl, IncidentRecord } from '../lib/incidentApi';
import type { PolicyDecision, PolicyRecord } from '../lib/policyApi';
import type { RiskAssessment, RiskOverview, RiskOverviewItem } from '../lib/riskApi';
import type { ApiVersion } from '../lib/systemApi';
import { policyOrder } from './governanceOrder';

function Version({ value, change }: { value: ApiVersion; change: (value: ApiVersion) => void }) {
  return <div className="gov-version" aria-label="API compatibility view"><span>API VIEW</span>{(['v1', 'v2'] as const).map(version => <button key={version} type="button" className={value === version ? 'active' : ''} onClick={() => change(version)}>{version}</button>)}</div>;
}
function Header({ number, label, title, detail, apiVersion, onApiVersionChange, action }: { number: string; label: string; title: string; detail: string; apiVersion: ApiVersion; onApiVersionChange: (value: ApiVersion) => void; action?: ReactNode }) {
  return <header className="gov-header"><div className="gov-header-text"><div className="gov-overline"><span>{number} / GOVERNANCE</span><span>{label}</span></div><h1>{title}</h1><p>{detail}</p></div><div className="gov-header-tools"><Version value={apiVersion} change={onApiVersionChange}/>{action}</div></header>;
}
function Empty({ icon, title, detail }: { icon: ReactNode; title: string; detail: string }) { return <div className="gov-empty">{icon}<strong>{title}</strong><p>{detail}</p></div>; }
function date(value: string | null) { return value ? new Date(value).toLocaleString() : '—'; }
function label(value: string) { return value.replace(/_/g, ' '); }

export function PoliciesStage(props: {
  apiVersion: ApiVersion; onApiVersionChange: (value: ApiVersion) => void; policies: PolicyRecord[]; agents: AgentIdentity[]; catalog: CapabilityCatalog | null;
  selected: PolicyRecord | null; select: (id: string) => void; canManage: boolean; loading: boolean; error: string | null;
  openCreate: () => void; openEdit: (policy: PolicyRecord) => void; toggleStatus: () => void;
  evalAgentId: string; setEvalAgentId: (value: string) => void; evalResourceId: string; setEvalResourceId: (value: string) => void;
  evalScope: string; setEvalScope: (value: string) => void; scopeOptions: Array<{ scope: string }>;
  runEvaluation: () => void; evaluating: boolean; decision: PolicyDecision | null; clearDecision: () => void;
}) {
  const p = props;
  const ranked = policyOrder(p.policies);
  const names = (ids: string[], choices: Array<{ id: string; name: string }>, fallback: string) => ids.length ? ids.map(id => choices.find(item => item.id === id)?.name ?? id).join(', ') : fallback;
  return <section className="gov-page gov-policies">
    <Header number="01" label="POLICY CONTROL" title="The decision order." detail="Every request meets an explicit rule or closes by default. Inspect precedence, then test a request without execution." apiVersion={p.apiVersion} onApiVersionChange={p.onApiVersionChange} action={p.canManage && <button className="gov-strong-button" onClick={p.openCreate}><Plus size={15}/> New policy</button>}/>
    {p.error && <div className="inline-error">{p.error}</div>}
    <div className="gov-policy-principle"><Shield size={18}/><strong>Default deny</strong><span>Highest priority first. Equal priority resolves DENY → REQUIRE APPROVAL → ALLOW.</span><em>NO PROVIDER EXECUTION</em></div>
    <div className="gov-policy-workbench"><div className="gov-rule-track"><div className="gov-section-title"><span>01 / RULE ORDER</span><strong>{p.policies.filter(item => item.status === 'enabled').length} enabled</strong></div>
      {p.loading ? <Empty icon={<Loader2 className="spin"/>} title="Loading rules" detail="Reading the current policy order."/> : ranked.length ? ranked.map((item, index) => <button key={item.id} type="button" className={`gov-rule ${p.selected?.id === item.id ? 'selected' : ''} ${item.status === 'disabled' ? 'disabled' : ''}`} onClick={() => p.select(item.id)} aria-pressed={p.selected?.id === item.id}>
        <span className="gov-rule-rank">{String(index + 1).padStart(2, '0')}</span><span className={`gov-rule-effect ${item.effect}`}>{item.effect === 'require_approval' ? 'REVIEW' : item.effect.toUpperCase()}</span><span className="gov-rule-name"><strong>{item.name}</strong><small>P{item.priority} · revision {item.revision}</small></span><span className="gov-rule-status">{item.status}</span><ChevronRight size={15}/></button>) : <Empty icon={<ShieldCheck/>} title="No rules defined" detail="All requests currently resolve to default deny."/>}
      <div className="gov-rule-end"><span>NO MATCH</span><ArrowDownRight size={16}/><strong>DENY</strong></div>
    </div><article className="gov-policy-file" key={p.selected?.id ?? 'empty'}><div className="gov-section-title"><span>02 / RULE FILE</span>{p.selected && <span>REV {p.selected.revision}</span>}</div>
      {p.selected ? <><div className="gov-file-intro"><span className={`gov-effect-bar ${p.selected.effect}`}/><div><small>EFFECT / PRIORITY {p.selected.priority}</small><h2>{p.selected.name}</h2><strong className={`gov-effect-word ${p.selected.effect}`}>{label(p.selected.effect)}</strong></div></div><p className="gov-file-description">{p.selected.description || 'No description provided.'}</p>
        <div className="gov-selector-ledger"><div><span>AGENTS</span><strong>{names(p.selected.selectors.agentIds, p.agents, 'Any agent')}</strong></div><div><span>RESOURCES</span><strong>{names(p.selected.selectors.resourceIds, p.catalog?.resources.map(item => ({ id: item.id, name: item.displayName })) ?? [], 'Any resource')}</strong></div><div><span>ACTIONS</span><strong>{p.selected.selectors.actions.join(', ') || 'Any action'}</strong></div><div><span>SCOPES</span><strong>{p.selected.selectors.scopes.join(', ') || 'Any scope'}</strong></div><div><span>RISK</span><strong>{p.selected.selectors.risks.join(', ') || 'Any risk'}</strong></div><div><span>STATE</span><strong>{p.selected.status}</strong></div></div>
        {p.canManage && <div className="gov-file-actions"><button onClick={() => p.openEdit(p.selected!)}>Edit rule <ArrowRight size={14}/></button><button onClick={p.toggleStatus}>{p.selected.status === 'enabled' ? 'Disable rule' : 'Enable rule'} <ArrowRight size={14}/></button></div>}</> : <Empty icon={<FileSearch/>} title="Select a rule" detail="Inspect the exact selectors, effect and revision."/>}</article></div>
    <section className="gov-lab"><div className="gov-section-title"><span>03 / DECISION LAB</span><span>DRY RUN</span></div><div className="gov-lab-body"><div><h2>Test the boundary.</h2><p>The current control plane evaluates this request. No external operation is called.</p></div><div className="gov-lab-fields"><label>Agent<select value={p.evalAgentId} onChange={event => { p.setEvalAgentId(event.target.value); p.clearDecision(); }}><option value="">Select agent</option>{p.agents.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Resource<select value={p.evalResourceId} onChange={event => { p.setEvalResourceId(event.target.value); p.clearDecision(); }}><option value="">Select resource</option>{p.catalog?.resources.map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Scope<select value={p.evalScope} onChange={event => { p.setEvalScope(event.target.value); p.clearDecision(); }}><option value="">Select scope</option>{p.scopeOptions.map(item => <option key={item.scope} value={item.scope}>{item.scope}</option>)}</select></label><button className="gov-strong-button" onClick={p.runEvaluation} disabled={p.evaluating || !p.evalAgentId || !p.evalResourceId || !p.evalScope}>{p.evaluating ? <Loader2 size={15} className="spin"/> : <ArrowRight size={15}/>} Evaluate</button></div></div>
      {p.decision && <div className={`gov-decision ${p.decision.outcome.toLowerCase()}`} key={p.decision.evaluatedAt}><div><small>DECISION / {date(p.decision.evaluatedAt)}</small><h3>{label(p.decision.outcome)}</h3><p>{p.decision.reason}</p></div><div className="gov-decision-proof"><span>{p.decision.winningPolicy ? `Winning rule · ${p.decision.winningPolicy.name} / P${p.decision.winningPolicy.priority}` : 'No winning rule / precondition'}</span><span>{p.decision.riskAssessment ? `Risk ${p.decision.riskAssessment.baselineRisk} → ${p.decision.riskAssessment.effectiveRisk}` : 'Risk unavailable'}</span><span>{Object.entries(p.decision.preconditions).filter(([, good]) => !good).map(([name]) => label(name)).join(' · ') || 'Preconditions satisfied'}</span></div></div>}
    </section>
  </section>;
}

const levels = ['low', 'medium', 'high', 'critical'] as const;
function RiskInstrument({ assessment, correlation }: { assessment: RiskAssessment; correlation?: string }) {
  const baseline = levels.indexOf(assessment.baselineRisk), effective = levels.indexOf(assessment.effectiveRisk);
  return <div className="gov-risk-instrument" key={`${assessment.context.agentId}-${assessment.context.scope}-${assessment.evaluatedAt}`}><div className="gov-risk-meta"><span>BASELINE <strong>{assessment.baselineRisk}</strong></span><ArrowRight size={16}/><span>EFFECTIVE <strong>{assessment.effectiveRisk}</strong></span><em>+{assessment.elevationSteps} LEVEL{assessment.elevationSteps === 1 ? '' : 'S'}</em></div><div className="gov-risk-scale">{levels.map((level, index) => <div key={level} className={`${index <= effective ? 'reached' : ''} ${index >= baseline && index <= effective ? 'elevated' : ''}`} style={{ animationDelay: `${index * 85}ms` }}><i/><span>{level}</span></div>)}</div><div className="gov-risk-context"><span>{assessment.context.agentName}</span><ArrowRight size={14}/><span>{assessment.context.resourceName}</span><ArrowRight size={14}/><span>{assessment.context.scope}</span></div>{correlation && <code>{correlation}</code>}
    <div className="gov-signal-list"><div className="gov-section-title"><span>BEHAVIOR SIGNALS</span><span>{assessment.signals.filter(signal => signal.active).length} ACTIVE</span></div>{assessment.signals.map(signal => <div key={signal.code} className={signal.active ? 'active' : ''}><span className="gov-signal-indicator"/><div><strong>{label(signal.code)}</strong><p>{signal.reason}</p></div><span>{signal.count} / {signal.threshold}{signal.windowMinutes ? ` · ${signal.windowMinutes}m` : ''}</span></div>)}</div></div>;
}
export function RiskStage(p: { apiVersion: ApiVersion; onApiVersionChange: (value: ApiVersion) => void; organizationName: string; overview: RiskOverview; selected: RiskOverviewItem | null; select: (item: RiskOverviewItem) => void; agents: AgentIdentity[]; catalog: CapabilityCatalog | null; resourceId: string; setResourceId: (value: string) => void; agentId: string; setAgentId: (value: string) => void; scope: string; setScope: (value: string) => void; result: RiskAssessment | null; clearResult: () => void; evaluate: () => void; evaluating: boolean; loading: boolean; error: string | null }) {
  const resource = p.catalog?.resources.find(item => item.id === p.resourceId);
  return <section className="gov-page gov-risk"><Header number="02" label="RISK INTELLIGENCE" title="See what raised it." detail={`Capability risk in ${p.organizationName} can hold or rise as behavior changes. Every elevation has an observable reason.`} apiVersion={p.apiVersion} onApiVersionChange={p.onApiVersionChange}/>{p.error && <div className="inline-error">{p.error}</div>}
    <div className="gov-risk-summary"><div><span>ASSESSED</span><strong>{p.overview.summary.assessedActions}</strong></div><div><span>ELEVATED</span><strong>{p.overview.summary.elevated}</strong></div><div><span>HIGH / CRITICAL</span><strong>{p.overview.summary.highOrCritical}</strong></div><div><span>SIGNAL HITS</span><strong>{p.overview.summary.activeSignalHits}</strong></div><p>Behavior can increase the capability baseline. It never silently decreases it.</p></div>
    <div className="gov-risk-body"><div className="gov-risk-history"><div className="gov-section-title"><span>01 / RECENT ASSESSMENTS</span><span>{p.overview.assessments.length} SHOWN</span></div>{p.loading ? <Empty icon={<Loader2 className="spin"/>} title="Loading assessments" detail="Reading bounded action history."/> : p.overview.assessments.length ? p.overview.assessments.map(item => <button key={item.actionId} className={`gov-risk-item ${p.selected?.actionId === item.actionId ? 'selected' : ''}`} onClick={() => p.select(item)} aria-pressed={p.selected?.actionId === item.actionId}><span className={`gov-risk-dot ${item.assessment.effectiveRisk}`}/><div><strong>{item.agent.name}</strong><small>{item.scope}</small></div><span>{item.assessment.baselineRisk} <ArrowRight size={12}/> {item.assessment.effectiveRisk}</span></button>) : <Empty icon={<Activity/>} title="No assessments yet" detail="Gateway actions will leave their risk snapshot here. Older actions are not backfilled."/>}</div><div className="gov-risk-focus"><div className="gov-section-title"><span>02 / ELEVATION RECORD</span><span>{p.selected ? date(p.selected.assessment.evaluatedAt) : 'NO SELECTION'}</span></div>{p.selected ? <RiskInstrument assessment={p.selected.assessment} correlation={p.selected.correlationId}/> : <Empty icon={<ShieldAlert/>} title="Select an action" detail="The risk movement and its signals will appear here."/>}</div></div>
    <div className="gov-risk-lab"><div><span className="gov-section-title"><span>03 / CURRENT ASSESSMENT</span><span>DRY RUN</span></span><h2>Check present risk.</h2><p>Reads bounded behavior. This neither authorizes nor executes an action.</p></div><div className="gov-lab-fields"><label>Agent<select value={p.agentId} onChange={event => {p.setAgentId(event.target.value);p.clearResult();}}><option value="">Select agent</option>{p.agents.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Resource<select value={p.resourceId} onChange={event => {p.setResourceId(event.target.value);p.clearResult();}}><option value="">Select resource</option>{p.catalog?.resources.map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Scope<select value={p.scope} onChange={event => {p.setScope(event.target.value);p.clearResult();}}><option value="">Select scope</option>{resource?.actions.map(item => <option key={item.scope} value={item.scope}>{item.scope}</option>)}</select></label><button className="gov-strong-button" onClick={p.evaluate} disabled={p.evaluating || !p.agentId || !p.resourceId || !p.scope}>{p.evaluating ? <Loader2 className="spin" size={15}/> : <ArrowRight size={15}/>} Assess</button></div>{p.result && <div className="gov-risk-result"><div className="gov-section-title"><span>CURRENT RESULT</span><span>{date(p.result.evaluatedAt)}</span></div><RiskInstrument assessment={p.result}/></div>}</div>
    <div className="gov-threshold-line"><span>THRESHOLDS</span><span>Burst {p.overview.thresholds.burst.count}/{p.overview.thresholds.burst.minutes}m</span><span>Blocks {p.overview.thresholds.blocks.count}/{p.overview.thresholds.blocks.minutes}m</span><span>Failures {p.overview.thresholds.failures.count}/{p.overview.thresholds.failures.minutes}m</span><span>Approvals {p.overview.thresholds.approvals.count}/{p.overview.thresholds.approvals.minutes}m</span><span>Truncated history +1 level</span></div>
  </section>;
}

export function IncidentsStage(p: { apiVersion: ApiVersion; onApiVersionChange: (value: ApiVersion) => void; incidents: IncidentRecord[]; selected: IncidentRecord | null; select: (id: string) => void; summary: { open: number; acknowledged: number; resolved: number; critical: number }; orgControl: ExecutionControl | null; targetControl: ExecutionControl | null; canManage: boolean; loading: boolean; busy: boolean; error: string | null; create: () => void; emergencyToggle: () => void; targetToggle: () => void; transition: (status: 'acknowledged' | 'resolved') => void }) {
  const stages = ['open', 'acknowledged', 'resolved'] as const;
  return <section className="gov-page gov-incidents"><Header number="03" label="INCIDENT RESPONSE" title="Contain. Investigate. Restore." detail="Incident status and execution state are separate controls. A closed case never resumes a suspended target by itself." apiVersion={p.apiVersion} onApiVersionChange={p.onApiVersionChange} action={p.canManage && <button className="gov-strong-button" onClick={p.create}><Plus size={15}/> Open incident</button>}/>{p.error && <div className="inline-error">{p.error}</div>}
    <div className={`gov-control-deck ${p.orgControl?.state === 'suspended' ? 'suspended' : ''}`}><div className="gov-control-icon">{p.orgControl?.state === 'suspended' ? <CirclePause size={23}/> : <ShieldCheck size={23}/>}</div><div><small>ORGANIZATION EXECUTION</small><h2>{p.orgControl ? p.orgControl.state === 'suspended' ? 'Suspended' : 'Active' : 'Checking state'}</h2><p>{p.orgControl?.reason || 'No emergency stop is active.'}</p></div><div className="gov-control-path"><i/><i/><i/></div>{p.canManage && <button className={p.orgControl?.state === 'suspended' ? 'gov-restore-button' : 'gov-stop-button'} disabled={p.busy || !p.orgControl} onClick={p.emergencyToggle}>{p.orgControl?.state === 'suspended' ? <RotateCcw size={15}/> : <CirclePause size={15}/>} {p.orgControl?.state === 'suspended' ? 'Restore organization' : 'Emergency stop'}</button>}</div>
    <div className="gov-case-strip">{stages.map(stage => <div key={stage}><span>{stage.toUpperCase()}</span><strong>{p.summary[stage]}</strong><i/></div>)}<div><span>CRITICAL</span><strong>{p.summary.critical}</strong><i/></div></div>
    <div className="gov-incident-body"><div className="gov-case-index"><div className="gov-section-title"><span>01 / CASE QUEUE</span><span>{p.incidents.length} RECORDS</span></div>{p.loading ? <Empty icon={<Loader2 className="spin"/>} title="Loading incidents" detail="Reading the case queue."/> : p.incidents.length ? p.incidents.map(item => <button key={item.id} className={`gov-case-item ${p.selected?.id === item.id ? 'selected' : ''}`} onClick={() => p.select(item.id)} aria-pressed={p.selected?.id === item.id}><span className={`gov-case-severity ${item.severity}`}/><div><small>{item.severity.toUpperCase()} · {item.status.toUpperCase()}</small><strong>{item.title}</strong><span>{item.target.type} / {item.target.name}</span></div><ChevronRight size={15}/></button>) : <Empty icon={<ShieldCheck/>} title="No incidents" detail="Operational incidents will appear here."/>}</div>
      <article className="gov-case-file" key={p.selected?.id ?? 'none'}><div className="gov-section-title"><span>02 / CASE FILE</span>{p.selected && <span>{date(p.selected.createdAt)}</span>}</div>{p.selected ? <><div className="gov-case-head"><span className={`gov-case-severity ${p.selected.severity}`}/><div><small>{p.selected.status.toUpperCase()} / {p.selected.severity.toUpperCase()}</small><h2>{p.selected.title}</h2><p>{p.selected.description || 'No description provided.'}</p></div></div><div className="gov-case-evidence"><div><span>TARGET</span><strong>{p.selected.target.type} · {p.selected.target.name}</strong></div><div><span>CORRELATION</span><strong className="gov-break">{p.selected.correlationId}</strong></div><div><span>OPENED</span><strong>{date(p.selected.createdAt)}</strong></div><div><span>ACKNOWLEDGED</span><strong>{date(p.selected.acknowledgedAt)}</strong></div><div><span>RESOLVED</span><strong>{date(p.selected.resolvedAt)}</strong></div></div><div className={`gov-target-control ${p.targetControl?.state === 'suspended' ? 'suspended' : ''}`}><div><small>TARGET EXECUTION / INDEPENDENT CONTROL</small><strong>{p.targetControl?.state ?? 'Checking state'}</strong><p>{p.targetControl?.reason || 'No target stop is active.'}</p></div>{p.canManage && <button disabled={p.busy || !p.targetControl} onClick={p.targetToggle}>{p.targetControl?.state === 'suspended' ? 'Restore target' : 'Suspend target'} <ArrowRight size={14}/></button>}</div>{p.canManage && <div className="gov-case-actions">{p.selected.status === 'open' && <button disabled={p.busy} onClick={() => p.transition('acknowledged')}><Check size={14}/> Acknowledge</button>}{p.selected.status !== 'resolved' && <button disabled={p.busy} onClick={() => p.transition('resolved')}>Resolve case <ArrowRight size={14}/></button>}</div>}{p.selected.status === 'resolved' && <div className="gov-resolution"><small>RESOLUTION NOTE</small><p>{p.selected.resolutionNote || '—'}</p><strong>Execution remains independently controlled.</strong></div>}</> : <Empty icon={<FileSearch/>} title="Select a case" detail="Review the timeline, target state and available controls."/>}</article></div>
  </section>;
}

const categories: AuditCategory[] = ['identity', 'workforce', 'integration', 'policy', 'action', 'approval', 'risk', 'incident', 'security', 'system'];
export function AuditStage(p: { apiVersion: ApiVersion; onApiVersionChange: (value: ApiVersion) => void; organizationName: string; result: AuditResult; selected: AuditEvent | null; select: (event: AuditEvent) => void; q: string; setQ: (value: string) => void; category: AuditCategory | ''; setCategory: (value: AuditCategory | '') => void; severity: AuditSeverity | ''; setSeverity: (value: AuditSeverity | '') => void; correlationId: string; loading: boolean; error: string | null; refresh: () => void; clear: () => void; trace: (event: AuditEvent) => void }) {
  return <section className="gov-page gov-audit"><Header number="04" label="AUDIT HISTORY" title="Follow the evidence." detail={`A bounded, append-only view of control-plane events for ${p.organizationName}. Trace a correlation to see connected decisions.`} apiVersion={p.apiVersion} onApiVersionChange={p.onApiVersionChange}/>{p.error && <div className="inline-error">{p.error}</div>}
    <div className="gov-audit-topline"><div><span>VISIBLE EVENTS</span><strong>{p.result.summary.visible}</strong></div><div><span>CRITICAL</span><strong>{p.result.summary.bySeverity.critical}</strong></div><div><span>WARNINGS</span><strong>{p.result.summary.bySeverity.warning}</strong></div><div><span>TRACES</span><strong>{p.result.summary.uniqueCorrelations}</strong></div><div><span>LAST EVENT</span><strong className="gov-date-value">{date(p.result.summary.latestAt)}</strong></div></div>
    <form className="gov-audit-filter" onSubmit={event => { event.preventDefault(); p.refresh(); }}><label className="gov-search"><Search size={15}/><input value={p.q} onChange={event => p.setQ(event.target.value)} placeholder="Search events, people, resources…" aria-label="Search audit events"/></label><select aria-label="Audit category" value={p.category} onChange={event => p.setCategory(event.target.value as AuditCategory | '')}><option value="">All categories</option>{categories.map(item => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Audit severity" value={p.severity} onChange={event => p.setSeverity(event.target.value as AuditSeverity | '')}><option value="">All severities</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select><button type="submit" className="gov-strong-button"><SlidersHorizontal size={14}/> Apply</button><button type="button" className="gov-clear-button" onClick={p.clear}><X size={14}/> Clear</button></form>
    {p.correlationId && <div className="gov-trace-mode"><Fingerprint size={16}/><span>TRACE ACTIVE <strong>{p.correlationId}</strong></span><button onClick={p.clear}>Exit trace <X size={14}/></button></div>}
    <div className="gov-audit-body"><div className="gov-audit-timeline"><div className="gov-section-title"><span>01 / EVENT STREAM</span><span>MOST RECENT FIRST</span></div>{p.loading ? <Empty icon={<Loader2 className="spin"/>} title="Loading events" detail="Reading the bounded audit window."/> : p.result.events.length ? p.result.events.map((event, index) => <button key={event.id} className={`gov-event ${p.selected?.id === event.id ? 'selected' : ''}`} onClick={() => p.select(event)} aria-pressed={p.selected?.id === event.id} style={{ animationDelay: `${Math.min(index, 7) * 45}ms` }}><span className="gov-event-time">{new Date(event.occurredAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}<small>{new Date(event.occurredAt).toLocaleDateString()}</small></span><span className={`gov-event-pin ${event.severity}`}/><span className="gov-event-copy"><small>{event.category.toUpperCase()} / {event.severity.toUpperCase()}</small><strong>{event.eventType}</strong><span>{event.summary}</span><em>{event.actor.label || event.actor.id} → {event.resource.name || event.resource.id}</em></span><ChevronRight size={15}/></button>) : <Empty icon={<ShieldCheck/>} title="No matching events" detail="Adjust the filters or wait for new control-plane activity."/>}</div>
    <aside className="gov-evidence-file" key={p.selected?.id ?? 'none'}><div className="gov-section-title"><span>02 / EVIDENCE FILE</span>{p.selected && <span>{p.selected.severity.toUpperCase()}</span>}</div>{p.selected ? <><div className="gov-evidence-head"><span className={`gov-evidence-severity ${p.selected.severity}`}>{p.selected.severity}</span><h2>{p.selected.eventType}</h2><p>{p.selected.summary}</p></div><dl className="gov-evidence-fields"><div><dt>TIME</dt><dd>{date(p.selected.occurredAt)}</dd></div><div><dt>ACTOR</dt><dd>{p.selected.actor.type} · {p.selected.actor.label || p.selected.actor.id}</dd></div><div><dt>RESOURCE</dt><dd>{p.selected.resource.type} · {p.selected.resource.name || p.selected.resource.id}</dd></div><div><dt>OUTCOME</dt><dd>{p.selected.outcome || '—'}</dd></div><div><dt>CORRELATION</dt><dd className="gov-break">{p.selected.correlationId || '—'}</dd></div></dl>{p.selected.correlationId && <button className="gov-trace-button" onClick={() => p.trace(p.selected!)}>Follow this correlation <ArrowRight size={15}/></button>}<div className="gov-metadata"><span>RECORDED METADATA</span><pre>{JSON.stringify(p.selected.metadata, null, 2)}</pre></div></> : <Empty icon={<FileSearch/>} title="Choose an event" detail="Open its actor, resource, outcome and recorded metadata."/>}</aside></div>
    {p.result.window.truncated && <p className="gov-window-note">This view searched the most recent {p.result.window.limit} events. Earlier records were not loaded in this request.</p>}
  </section>;
}
