import type { IntegrationAdapter, ProviderCapabilityDescriptor, ProviderConnectionResult, ProviderHealthResult } from './contracts';
interface GitHubRepositoryPayload { full_name?: unknown; name?: unknown; private?: unknown; default_branch?: unknown; archived?: unknown; html_url?: unknown; owner?: { login?: unknown }; }
const GITHUB_CAPABILITIES: ProviderCapabilityDescriptor[] = [
    { providerOperation: 'repository.metadata.read', resourceType: 'repository', action: 'read', target: 'metadata', scope: 'github.repository.metadata.read', description: 'Read connected repository metadata and visibility information.', risk: 'low' },
    { providerOperation: 'repository.issues.read', resourceType: 'repository', action: 'read', target: 'issues', scope: 'github.repository.issues.read', description: 'Read issues exposed by the connected repository.', risk: 'low' },
    { providerOperation: 'repository.pull_requests.read', resourceType: 'repository', action: 'read', target: 'pull_requests', scope: 'github.repository.pull_requests.read', description: 'Read pull requests exposed by the connected repository.', risk: 'low' },
];
function repositoryCoordinates(value: unknown) { const repository = typeof value === 'string' ? value.trim() : ''; if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)) throw new Error('Repository must use the owner/repository format.'); const [owner, name] = repository.split('/'); return { owner, name }; }
async function githubRepository(config: Record<string, unknown> | Record<string, string>, credential?: string): Promise<GitHubRepositoryPayload> { const { owner, name } = repositoryCoordinates(config.repository); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8000); try { const headers: Record<string, string> = { Accept: 'application/vnd.github+json', 'User-Agent': 'AgentGate/0.5', 'X-GitHub-Api-Version': '2022-11-28' }; if (credential) headers.Authorization = `Bearer ${credential}`; const response = await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`, { headers, signal: controller.signal }); if (response.status === 401) throw new Error('GitHub rejected the supplied credential.'); if (response.status === 404) throw new Error('Repository was not found or the supplied credential cannot access it.'); if (response.status === 403) throw new Error('GitHub denied the repository check. Verify credential scope or API rate limits.'); if (!response.ok) throw new Error(`GitHub repository check failed with status ${response.status}.`); return await response.json() as GitHubRepositoryPayload; } catch (caught) { if (caught instanceof Error && caught.name === 'AbortError') throw new Error('GitHub repository check timed out.'); throw caught; } finally { clearTimeout(timeout); } }
function normalized(payload: GitHubRepositoryPayload): ProviderConnectionResult { if (typeof payload.full_name !== 'string' || typeof payload.name !== 'string' || !payload.owner || typeof payload.owner.login !== 'string') throw new Error('GitHub returned an invalid repository response.'); const fullName = payload.full_name; const webUrl = typeof payload.html_url === 'string' ? payload.html_url : `https://github.com/${fullName}`; return { resourceKey: fullName.toLowerCase(), displayName: fullName, webUrl, config: { repository: fullName }, metadata: { owner: payload.owner.login, repository: payload.name, private: payload.private === true, defaultBranch: typeof payload.default_branch === 'string' ? payload.default_branch : 'main', archived: payload.archived === true } }; }
export const githubAdapter: IntegrationAdapter = { provider: 'github', displayName: 'GitHub', credentialPolicy: 'optional', capabilities: GITHUB_CAPABILITIES, supportedOperations: GITHUB_CAPABILITIES.map((capability) => capability.providerOperation), async validateConnection(config, credential) { return normalized(await githubRepository(config, credential)); }, async checkHealth(config, credential): Promise<ProviderHealthResult> { const result = normalized(await githubRepository(config, credential)); return { state: 'healthy', message: `Repository ${result.displayName} is reachable.`, checkedAt: new Date().toISOString(), metadata: result.metadata }; } };
