import type { PerformanceWorkspace } from '../lib/performanceApi';
import type { WorkforceSnapshot } from '../lib/workforceApi';
import type { JobsWorkspace } from '../lib/jobsApi';
import type { Artifact, MemoryRecord } from '../lib/memoryApi';
import type { ResultsWorkspace, ResultDetail } from '../lib/resultsApi';
import type { ApprovalRecord } from '../lib/approvalApi';
import type { ActionRecord } from '../lib/actionApi';
import type { RuntimeRun, RuntimeStep } from '../lib/runtimeApi';
import type { Escalation, EscalationRule } from '../lib/supervisionApi';
import type { AuditEvent, AuditResult } from '../lib/auditApi';
import type { CapabilityCatalog } from '../lib/capabilityApi';
import type { IncidentRecord } from '../lib/incidentApi';
import type { PolicyRecord } from '../lib/policyApi';
import type { RiskAssessment, RiskOverview } from '../lib/riskApi';

const org = 'preview-organization';
const time = '2026-09-30T10:00:00Z';
const recent = (daysAgo: number) => new Date(Date.now() - daysAgo * 86400000).toISOString();
const workerId = 'preview-worker-1';
const jobId = 'preview-job-1';
const agentId = 'preview-agent-1';

export const previewPerformance: PerformanceWorkspace = {
  generatedAt: time,
  summary: { workers: 2, activeWorkers: 2, runs: 28, terminalRuns: 24, completed: 21, failed: 2, cancelled: 1, successRate: 87.5, failureRate: 8.3, approvalRate: 100, blockedActions: 3, escalations: 2, escalationsPer100Runs: 7.1, incidents: 1, incidentsPer100Runs: 3.6, averageRunDurationMs: 91000, medianRunDurationMs: 74000 },
  workers: [
    { id: workerId, name: 'Research analyst', department: 'Research', status: 'active', supervisorUserId: 'preview-user', runs: 18, completed: 15, failed: 1, cancelled: 1, waitingApproval: 1, successRate: 88.2, failureRate: 5.9, approvalRate: 100, blockedActions: 2, escalations: 1, incidents: 0, averageRunDurationMs: 82000, medianRunDurationMs: 70000 },
    { id: 'preview-worker-2', name: 'Operations coordinator', department: 'Operations', status: 'active', supervisorUserId: 'preview-user', runs: 10, completed: 6, failed: 1, cancelled: 0, waitingApproval: 0, successRate: 85.7, failureRate: 14.3, approvalRate: 100, blockedActions: 1, escalations: 1, incidents: 1, averageRunDurationMs: 104000, medianRunDurationMs: 79000 },
  ],
  departments: [
    { name: 'Research', workers: 1, runs: 18, completed: 15, failed: 1, cancelled: 1, successRate: 88.2, escalations: 1, incidents: 0 },
    { name: 'Operations', workers: 1, runs: 10, completed: 6, failed: 1, cancelled: 0, successRate: 85.7, escalations: 1, incidents: 1 },
  ],
  tools: [{ id: 'preview-tool', name: 'Sample repository', provider: 'github', executed: 14, failed: 1, blocked: 2, held: 1, providerAttempts: 15, reliabilityRate: 93.3 }],
  trends: Array.from({ length: 14 }, (_, index) => ({ date: recent(13 - index).slice(0, 10), completed: index % 4 === 0 ? 1 : 2, failed: index === 8 ? 1 : 0, cancelled: index === 3 ? 1 : 0 })),
  activity: [
    { id: 'activity-1', workerId, workerName: 'Research analyst', department: 'Research', kind: 'escalation', status: 'open', label: 'Source review needs a human decision', occurredAt: recent(0), correlationId: 'preview-correlation-1' },
    { id: 'activity-2', workerId, workerName: 'Research analyst', department: 'Research', kind: 'run', status: 'completed', label: 'Weekly research brief completed', occurredAt: recent(1), correlationId: 'preview-correlation-2' },
    { id: 'activity-3', workerId: 'preview-worker-2', workerName: 'Operations coordinator', department: 'Operations', kind: 'action', status: 'blocked', label: 'External update blocked by policy', occurredAt: recent(2), correlationId: 'preview-correlation-3' },
  ],
  window: { runs: { scanned: 28, limit: 100, truncated: false }, actions: { scanned: 18, limit: 100, truncated: false } },
  methodology: { score: 'No composite score', successRate: 'Completed / terminal runs', approvalRate: 'Decided approval records', toolReliability: 'Successful provider attempts / attempts', escalationRate: 'Escalations per 100 runs', incidentRate: 'Incidents per 100 runs', bounded: true },
};

const hours = {
  timezone: 'Africa/Lagos',
  days: Object.fromEntries(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'].map((day, index) => [day, { enabled: index < 5, start: '09:00', end: '17:00' }])),
} as WorkforceSnapshot['workers'][number]['workingHours'];

const workforce: WorkforceSnapshot = {
  roles: [{ id: 'preview-role-1', organizationId: org, name: 'Research analyst', purpose: 'Turn source material into a reviewable brief.', defaultInstructions: 'Summarize sources and cite evidence.', defaultResponsibilities: ['Research', 'Briefing'], recommendedCapabilities: ['github.repository.read'], createdBy: 'preview-user', createdAt: time, updatedAt: time }],
  workers: [
    { id: workerId, organizationId: org, agentIdentityId: agentId, agentIdentityProvisioning: 'automatic', name: 'Research analyst', roleId: 'preview-role-1', department: 'Research', supervisorUserId: 'preview-user', description: 'Prepares concise research briefs for review.', responsibilities: ['Review sources', 'Draft briefs'], instructions: 'Work from cited sources and request approval before external actions.', status: 'active', workingHours: hours, createdBy: 'preview-user', createdAt: time, updatedAt: time },
    { id: 'preview-worker-2', organizationId: org, agentIdentityId: 'preview-agent-2', agentIdentityProvisioning: 'automatic', name: 'Operations coordinator', roleId: 'preview-role-1', department: 'Operations', supervisorUserId: 'preview-user', description: 'Keeps the daily operational picture current.', responsibilities: ['Track work'], instructions: 'Escalate unclear or sensitive work.', status: 'active', workingHours: hours, createdBy: 'preview-user', createdAt: time, updatedAt: time },
  ],
  securityIdentities: [{ id: agentId, name: 'Research analyst identity', status: 'active', credentialStatus: 'active', boundWorkerId: workerId }],
  summary: { workers: 2, active: 2, paused: 0, suspended: 0, roles: 1, departments: 2 },
  window: { workersTruncated: false, rolesTruncated: false },
};

const conversationThreads = [
  { id: 'preview-thread-1', organizationId: org, workerId, title: 'Weekly research brief', status: 'active', createdBy: 'preview-user', createdAt: recent(2), updatedAt: recent(0) },
  { id: 'preview-thread-2', organizationId: org, workerId, title: 'Source review', status: 'active', createdBy: 'preview-user', createdAt: recent(5), updatedAt: recent(2) },
  { id: 'preview-thread-3', organizationId: org, workerId: 'preview-worker-2', title: 'Daily operations', status: 'active', createdBy: 'preview-user', createdAt: recent(3), updatedAt: recent(1) },
];
const conversationMessages = {
  'preview-thread-1': [
    { id: 'preview-message-1', organizationId: org, threadId: 'preview-thread-1', role: 'user', content: 'What is the state of the weekly brief?', artifactReferences: [], commandReferences: [], resultReferences: [], createdAt: recent(1) },
    { id: 'preview-message-2', organizationId: org, threadId: 'preview-thread-1', role: 'assistant', content: 'The brief is ready for your review. One source still needs a human decision before any external update.', artifactReferences: [], commandReferences: [], resultReferences: [], createdAt: recent(0) },
  ],
  'preview-thread-2': [{ id: 'preview-message-3', organizationId: org, threadId: 'preview-thread-2', role: 'assistant', content: 'I gathered the source material and marked the items that need confirmation.', artifactReferences: [], commandReferences: [], resultReferences: [], createdAt: recent(2) }],
  'preview-thread-3': [{ id: 'preview-message-4', organizationId: org, threadId: 'preview-thread-3', role: 'assistant', content: 'The daily work queue is current. A policy block was recorded for review.', artifactReferences: [], commandReferences: [], resultReferences: [], createdAt: recent(1) }],
};

const job: JobsWorkspace['jobs'][number] = {
  id: jobId, organizationId: org, workerId, name: 'Weekly research brief', description: 'Summarize relevant updates.', objective: 'Produce a reviewable brief.', instructions: 'Use available source material and cite it.', responsibilityLinks: ['Research'], requiredCapabilities: [], priority: 'normal', completionCriteria: ['A concise brief is ready for review'], status: 'active', triggerType: 'manual', scheduleId: null, revision: 1, createdBy: 'preview-user', createdAt: time, updatedBy: 'preview-user', updatedAt: time,
};
const jobs: JobsWorkspace = {
  jobs: [job, { ...job, id: 'preview-job-2', workerId: 'preview-worker-2', name: 'Daily operations review', description: 'Review the day’s operational exceptions.', objective: 'Give the team a clear list of exceptions requiring attention.', priority: 'high', status: 'paused', revision: 2 }, { ...job, id: 'preview-job-3', name: 'Source verification', description: 'Verify source evidence before a brief is circulated.', objective: 'Confirm every cited source is current and trustworthy.', status: 'draft' }],
  workItems: [{ id: 'preview-item-1', organizationId: org, workerId, jobId, jobRevision: 1, trigger: { type: 'manual', requestedByType: 'human', requestedBy: 'preview-user', requestedAt: recent(0), key: null, eventId: null, payload: null, scheduledFor: null, dedupeKey: null, sourceJobId: null, sourceWorkItemId: null, configId: null }, priority: 'normal', status: 'queued', scheduledAt: recent(0), startedAt: null, completedAt: null, retryCount: 0, runId: null, correlationId: 'preview-correlation-queue', snapshot: { jobName: job.name, objective: job.objective, instructions: job.instructions, responsibilityLinks: job.responsibilityLinks, requiredCapabilities: [], completionCriteria: job.completionCriteria, priority: 'normal' }, cancelledBy: null, cancelledAt: null, createdAt: recent(0), updatedAt: recent(0) }],
  jobSummary: { total: 3, draft: 1, active: 1, paused: 1, archived: 0 }, queueSummary: { total: 1, queued: 1, cancelled: 0, completed: 0, failed: 0 }, window: { jobsTruncated: false, workItemsTruncated: false }, dispatch: { state: 'ok', detail: 'Sample queue only', updatedAt: time },
};

const memoryBase: MemoryRecord = { id: 'preview-memory-1', organizationId: org, scope: 'worker', workerId, runId: null, title: 'Briefing standards', content: 'Keep research briefs concise. Cite primary sources, identify uncertainty, and pause before publishing anything externally.', tags: ['research', 'briefing'], source: 'human', sourceMemoryId: null, status: 'active', createdByType: 'human', createdBy: 'preview-user', correlationId: null, createdAt: recent(12), updatedAt: recent(2), expiresAt: recent(-120) };
const previewMemories: MemoryRecord[] = [memoryBase, { ...memoryBase, id: 'preview-memory-2', scope: 'organization', workerId: null, title: 'External communication practice', content: 'Any customer-facing change requires a human review of the final wording and recipient list.', tags: ['operations', 'review'], createdAt: recent(20), updatedAt: recent(4) }, { ...memoryBase, id: 'preview-memory-3', scope: 'run', runId: 'preview-run', title: 'Source review outcome', content: 'Three sources were checked. One needs confirmation before the weekly brief is circulated.', tags: ['source-review'], source: 'runtime', createdByType: 'system', createdBy: 'runtime', correlationId: 'preview-correlation-2', createdAt: recent(1), updatedAt: recent(1), expiresAt: recent(-29) }];
const previewArtifacts: Artifact[] = [{ id: 'preview-artifact-1', organizationId: org, workerId, runId: 'preview-run', stepId: null, name: 'Weekly research brief.pdf', kind: 'run_result', contentType: 'application/pdf', bytes: 184320, createdAt: recent(1), correlationId: 'preview-correlation-2' }];

const result: ResultDetail = {
  id: 'preview-result-1', organizationId: org, workerId, workerName: 'Research analyst', department: 'Research', jobId, jobName: job.name, workItemId: 'preview-work-item', runId: 'preview-run', agentId, title: 'Weekly research brief', summary: 'A short sample brief prepared for human review.', status: 'completed', version: 1, createdAt: time, completedAt: time, hasTables: false, isNew: true, contentType: 'structured_v1', blocks: [{ type: 'heading', text: 'Key finding', level: 2 }, { type: 'paragraph', text: 'This is sample content for evaluating the workspace layout.' }], artifactIds: [], sourceReferences: [], capabilitiesUsed: [], actionIds: [], approvalIds: [], correlationId: 'preview-correlation-2', runStartedAt: time, durationMs: 74000,
};
const results: ResultsWorkspace = {
  items: [result], workers: [{ id: workerId, name: 'Research analyst', department: 'Research', resultCount: 1, weekCount: 1, lastResultAt: time }], jobs: [{ id: jobId, name: job.name, workerId, workerName: 'Research analyst', department: 'Research', resultCount: 1, lastResultAt: time, latestResultId: result.id }], recentExports: [], summary: { total: 1, new: 1, completed: 1, attention: 0, failed: 0, cancelled: 0 }, filters: { departments: ['Research'], lastSeenAt: null }, window: { limit: 150, truncated: false },
};

const approval: ApprovalRecord = {
  id: 'preview-approval-1', organizationId: org, actionId: 'preview-action-1', agentId, agentName: 'Research analyst', request: { resourceId: 'preview-resource-1', resourceName: 'Sample repository', integrationId: 'preview-integration-1', scope: 'github.repository.write', action: 'update', target: 'sample/repository', risk: 'high', providerOperation: 'repository.update', input: {} }, policy: { outcome: 'REQUIRE_APPROVAL', reason: 'External write requires a person to review it.', winningPolicy: { id: 'preview-policy-1', name: 'Review external writes', effect: 'require_approval', priority: 100, revision: 1 }, matchedPolicies: [] }, status: 'pending', decision: null, execution: { state: 'not_started', actionStatus: null, summary: null, completedAt: null, reauthorization: null }, notification: { state: 'not_attempted', attemptedAt: null, sent: 0, failed: 0 }, requestedAt: time,
};

const previewAction: ActionRecord = { id: 'preview-action-1', organizationId: org, agent: { id: agentId, name: 'Research analyst', credentialFingerprint: 'PREVIEW' }, request: { resourceId: 'preview-resource-1', resourceName: 'Sample repository', integrationId: 'preview-integration-1', provider: 'github', scope: 'github.repository.write', action: 'update', target: 'sample/repository', risk: 'high', providerOperation: 'repository.update', input: {} }, status: 'held', correlationId: 'preview-correlation-1', idempotencyHash: 'preview-hash', policy: approval.policy, result: null, error: null, requestedAt: recent(0), completedAt: null };
const previewActions: ActionRecord[] = [previewAction, { ...previewAction, id: 'preview-action-2', status: 'executed', request: { ...previewAction.request, scope: 'github.repository.read', action: 'read', providerOperation: 'repository.read', risk: 'low' }, policy: { ...approval.policy, outcome: 'ALLOW', reason: 'Read operation permitted.' }, correlationId: 'preview-correlation-2', result: { providerOperation: 'repository.read', summary: 'Repository metadata retrieved.', executedAt: recent(1), providerRequestId: 'sample-request', data: { repository: 'sample/repository' } }, requestedAt: recent(1), completedAt: recent(1) }, { ...previewAction, id: 'preview-action-3', agent: { id: 'preview-agent-2', name: 'Operations coordinator', credentialFingerprint: 'PREVIEW' }, request: { ...previewAction.request, risk: 'critical' }, status: 'blocked', correlationId: 'preview-correlation-3', policy: { ...approval.policy, outcome: 'DENY', reason: 'Policy prevented this external update.' }, requestedAt: recent(2), completedAt: recent(2) }];

const previewRun: RuntimeRun = { id: 'preview-run', organizationId: org, workItemId: 'preview-item-1', jobId, workerId, agentId, correlationId: 'preview-correlation-2', attempt: 1, status: 'completed', currentStep: 3, stepIds: ['preview-step-1', 'preview-step-2', 'preview-step-3'], contextMemoryIds: ['preview-memory-1'], artifactIds: ['preview-artifact-1'], planSummary: 'Review source material and prepare a concise research brief.', resultSummary: 'Brief ready for human review.', failure: null, createdAt: recent(1), startedAt: recent(1), completedAt: recent(1), updatedAt: recent(1) };
const previewSteps: RuntimeStep[] = [{ id: 'preview-step-1', organizationId: org, runId: previewRun.id, index: 0, kind: 'reasoning', title: 'Plan the source review', instruction: 'Identify current, primary sources.', resourceId: '', scope: '', status: 'completed', output: 'Three sources selected.', actionId: null, approvalId: null, error: null, startedAt: recent(1), completedAt: recent(1) }, { id: 'preview-step-2', organizationId: org, runId: previewRun.id, index: 1, kind: 'action', title: 'Read repository context', instruction: 'Retrieve source metadata through the gateway.', resourceId: 'preview-resource-1', scope: 'github.repository.read', status: 'completed', output: 'Metadata retrieved.', actionId: 'preview-action-2', approvalId: null, error: null, startedAt: recent(1), completedAt: recent(1) }, { id: 'preview-step-3', organizationId: org, runId: previewRun.id, index: 2, kind: 'finish', title: 'Prepare the brief', instruction: 'Produce a reviewable result.', resourceId: '', scope: '', status: 'completed', output: 'Brief created.', actionId: null, approvalId: null, error: null, startedAt: recent(1), completedAt: recent(1) }];

const previewEscalation: Escalation = { id: 'preview-escalation-1', organizationId: org, trigger: 'risk_high', severity: 'high', status: 'open', workerId, workerName: 'Research analyst', supervisorUserId: 'preview-user', assignedToUserId: 'preview-user', jobId, workItemId: 'preview-item-1', runId: previewRun.id, actionId: 'preview-action-1', approvalId: approval.id, incidentId: null, correlationId: 'preview-correlation-1', sourceType: 'action', sourceId: 'preview-action-1', title: 'External update needs review', summary: 'The worker proposed an external repository update that requires a human decision.', reason: 'High-risk external write crossed the supervisor threshold.', notes: [], interventions: [], notification: { state: 'sent', attemptedAt: recent(0), sent: 1, failed: 0 }, createdAt: recent(0), updatedAt: recent(0), acknowledgedBy: null, acknowledgedAt: null, resolvedBy: null, resolvedAt: null };
const previewRules: EscalationRule[] = (['job_failure', 'policy_decision', 'risk_high', 'risk_critical'] as const).map((trigger) => ({ id: `preview-rule-${trigger}`, organizationId: org, trigger, enabled: true, severity: trigger === 'risk_critical' ? 'critical' : 'high', notifySupervisor: true, updatedBy: 'preview-user', updatedAt: recent(2) }));

const governanceCatalog: CapabilityCatalog = { resources: [{ id: 'preview-resource-1', organizationId: org, integrationId: 'preview-integration-1', provider: 'github', type: 'repository', key: 'sample/repository', displayName: 'Sample repository', status: 'connected', metadata: {}, scopes: ['github.repository.read', 'github.repository.write'], actions: [{ id: 'preview-capability-read', action: 'read', target: 'repository', providerOperation: 'repository.read', scope: 'github.repository.read', description: 'Read repository metadata', risk: 'low' }, { id: 'preview-capability-write', action: 'update', target: 'repository', providerOperation: 'repository.update', scope: 'github.repository.write', description: 'Update repository content', risk: 'high' }] }, { id: 'preview-resource-browser', organizationId: org, integrationId: 'preview-integration-browser', provider: 'browser', type: 'website', key: 'https://example.com', displayName: 'Sample website', status: 'connected', metadata: {}, scopes: ['browser.page.read', 'browser.navigation.open', 'browser.form.submit'], actions: [{ id: 'preview-browser-read', action: 'read', target: 'page', providerOperation: 'page.observe', scope: 'browser.page.read', description: 'Observe the current governed browser page.', risk: 'low' }, { id: 'preview-browser-open', action: 'open', target: 'page', providerOperation: 'navigation.open', scope: 'browser.navigation.open', description: 'Open an authorized URL in an isolated browser session.', risk: 'low' }, { id: 'preview-browser-submit', action: 'submit', target: 'form', providerOperation: 'form.submit', scope: 'browser.form.submit', description: 'Submit a governed form after higher-risk policy evaluation.', risk: 'high' }] }], scopes: ['github.repository.read', 'github.repository.write', 'browser.page.read', 'browser.navigation.open', 'browser.form.submit'], summary: { resources: 2, actions: 5, scopes: 5 } };
const governancePolicies: PolicyRecord[] = [
  { id: 'preview-policy-2', organizationId: org, name: 'Block unreviewed external changes', description: 'A restrictive rule for sensitive external updates.', effect: 'deny', priority: 700, status: 'enabled', selectors: { agentIds: [], resourceIds: [], actions: ['update'], scopes: [], risks: ['critical'] }, revision: 2, createdBy: 'preview-user', createdAt: recent(18), updatedBy: 'preview-user', updatedAt: recent(3) },
  { id: 'preview-policy-1', organizationId: org, name: 'Review external writes', description: 'Require a person to approve higher risk repository updates.', effect: 'require_approval', priority: 500, status: 'enabled', selectors: { agentIds: [], resourceIds: ['preview-resource-1'], actions: ['update'], scopes: ['github.repository.write'], risks: ['high'] }, revision: 3, createdBy: 'preview-user', createdAt: recent(20), updatedBy: 'preview-user', updatedAt: recent(2) },
  { id: 'preview-policy-3', organizationId: org, name: 'Permit source reading', description: 'Allow the research identity to read connected repository material.', effect: 'allow', priority: 300, status: 'enabled', selectors: { agentIds: [agentId], resourceIds: ['preview-resource-1'], actions: ['read'], scopes: ['github.repository.read'], risks: ['low'] }, revision: 1, createdBy: 'preview-user', createdAt: recent(9), updatedBy: 'preview-user', updatedAt: recent(9) },
];
const riskAssessment: RiskAssessment = { baselineRisk: 'high', effectiveRisk: 'critical', elevationSteps: 1, evaluatedAt: recent(0), context: { agentId: 'preview-agent-2', agentName: 'Operations coordinator', resourceId: 'preview-resource-1', resourceName: 'Sample repository', scope: 'github.repository.write', action: 'update' }, signals: [{ code: 'burst_activity', active: true, increment: 1, count: 6, threshold: 5, windowMinutes: 10, reason: 'Six requests in ten minutes crossed the burst threshold.' }, { code: 'repeated_blocks', active: false, increment: 0, count: 1, threshold: 3, windowMinutes: 30, reason: 'One blocked action in the observation window.' }, { code: 'repeated_failures', active: false, increment: 0, count: 0, threshold: 2, windowMinutes: 30, reason: 'No repeated provider failures.' }, { code: 'approval_pressure', active: false, increment: 0, count: 1, threshold: 3, windowMinutes: 30, reason: 'One approval request in the observation window.' }, { code: 'history_truncated', active: false, increment: 0, count: 0, threshold: 1, windowMinutes: null, reason: 'History is within the bounded window.' }], counters: { requests10m: 6, blocked30m: 1, failed30m: 0, approval30m: 1 }, window: { scanned: 18, agentMatches: 6, limit: 100, truncated: false } };
const governanceRisk: RiskOverview = { assessments: [{ actionId: 'preview-action-3', correlationId: 'preview-correlation-3', status: 'blocked', agent: { id: 'preview-agent-2', name: 'Operations coordinator' }, resource: { id: 'preview-resource-1', name: 'Sample repository' }, scope: 'github.repository.write', assessment: riskAssessment }, { actionId: 'preview-action-1', correlationId: 'preview-correlation-1', status: 'held', agent: { id: agentId, name: 'Research analyst' }, resource: { id: 'preview-resource-1', name: 'Sample repository' }, scope: 'github.repository.write', assessment: { ...riskAssessment, baselineRisk: 'high', effectiveRisk: 'high', elevationSteps: 0, context: { ...riskAssessment.context, agentId, agentName: 'Research analyst' }, signals: riskAssessment.signals.map(signal => ({ ...signal, active: false, increment: 0 })) } }, { actionId: 'preview-action-2', correlationId: 'preview-correlation-2', status: 'executed', agent: { id: agentId, name: 'Research analyst' }, resource: { id: 'preview-resource-1', name: 'Sample repository' }, scope: 'github.repository.read', assessment: { ...riskAssessment, baselineRisk: 'low', effectiveRisk: 'low', elevationSteps: 0, evaluatedAt: recent(1), context: { ...riskAssessment.context, scope: 'github.repository.read', action: 'read' }, signals: riskAssessment.signals.map(signal => ({ ...signal, active: false, increment: 0 })) } }], summary: { assessedActions: 3, elevated: 1, activeSignalHits: 1, highOrCritical: 2, byEffectiveRisk: { low: 1, medium: 0, high: 1, critical: 1 }, latestAt: recent(0) }, window: { scanned: 18, limit: 100, truncated: false }, thresholds: { burst: { count: 5, minutes: 10 }, blocks: { count: 3, minutes: 30 }, failures: { count: 2, minutes: 30 }, approvals: { count: 3, minutes: 30 }, truncatedHistoryElevation: true } };
const previewIncident: IncidentRecord = { id: 'preview-incident-1', organizationId: org, title: 'External update requires investigation', description: 'The operations identity attempted an unexpected repository change. The target was suspended while the team checks intent and authorization.', severity: 'high', status: 'acknowledged', target: { type: 'agent', id: 'preview-agent-2', name: 'Operations coordinator' }, correlationId: 'preview-correlation-3', createdBy: 'preview-user', createdAt: recent(1), acknowledgedBy: 'preview-user', acknowledgedAt: recent(0), resolvedBy: null, resolvedAt: null, resolutionNote: null, updatedAt: recent(0) };
const governanceEvents: AuditEvent[] = [
  { id: 'preview-audit-1', organizationId: org, eventType: 'incident.acknowledged', category: 'incident', severity: 'warning', actor: { type: 'human', id: 'preview-user', label: 'Sample operator' }, resource: { type: 'incident', id: previewIncident.id, name: previewIncident.title }, correlationId: 'preview-correlation-3', outcome: 'acknowledged', summary: 'The incident was assigned for investigation.', metadata: { severity: 'high', target: 'Operations coordinator' }, occurredAt: recent(0) },
  { id: 'preview-audit-2', organizationId: org, eventType: 'execution.suspended', category: 'security', severity: 'critical', actor: { type: 'human', id: 'preview-user', label: 'Sample operator' }, resource: { type: 'agent', id: 'preview-agent-2', name: 'Operations coordinator' }, correlationId: 'preview-correlation-3', outcome: 'suspended', summary: 'Execution was suspended for the operations identity.', metadata: { reason: 'Unexpected external update' }, occurredAt: recent(1) },
  { id: 'preview-audit-3', organizationId: org, eventType: 'policy.denied', category: 'policy', severity: 'warning', actor: { type: 'agent', id: 'preview-agent-2', label: 'Operations coordinator' }, resource: { type: 'repository', id: 'preview-resource-1', name: 'Sample repository' }, correlationId: 'preview-correlation-3', outcome: 'DENY', summary: 'The policy engine blocked the external update.', metadata: { priority: 700, risk: 'critical' }, occurredAt: recent(2) },
  { id: 'preview-audit-4', organizationId: org, eventType: 'action.executed', category: 'action', severity: 'info', actor: { type: 'agent', id: agentId, label: 'Research analyst' }, resource: { type: 'repository', id: 'preview-resource-1', name: 'Sample repository' }, correlationId: 'preview-correlation-2', outcome: 'executed', summary: 'Repository metadata was read for a research brief.', metadata: { scope: 'github.repository.read' }, occurredAt: recent(3) },
];
const governanceAudit: AuditResult = { events: governanceEvents, summary: { visible: governanceEvents.length, bySeverity: { info: 1, warning: 2, critical: 1 }, byCategory: { identity: 0, workforce: 0, integration: 0, policy: 1, action: 1, approval: 0, risk: 0, incident: 1, security: 1, system: 0 }, uniqueCorrelations: 2, latestAt: recent(0) }, window: { scanned: governanceEvents.length, limit: 200, truncated: false } };

type PreviewReply = { data: unknown; status: number; headers: Headers };

export async function previewResponse(method: string, path: string, _body?: unknown): Promise<PreviewReply> {
  const pathname = path.split('?')[0];
  // These two Results calls are automatic refresh housekeeping. They remain local no-ops.
  if (method === 'POST' && /\/results\/(backfill|seen)$/.test(pathname)) return { data: {}, status: 200, headers: new Headers() };
  if (method !== 'GET') throw new Error('Workspace preview is read-only. No change was sent.');
  if (!pathname.startsWith('/api/v1/')) throw new Error('Workspace preview shows the API v1 layout only.');
  const endpoint = pathname.replace(/^\/api\/v1\/organizations\/[^/]+/, '');
  const data = fixtureFor(endpoint, pathname, new URL(path, 'http://preview.local').searchParams);
  return { data, status: 200, headers: new Headers({ 'Content-Type': 'application/json' }) };
}

function fixtureFor(endpoint: string, fullPath: string, search: URLSearchParams): unknown {
  if (fullPath === '/api/v1/system/status') return { service: 'Audoryn preview', apiVersion: 'v1', status: 'operational', securityMode: 'fail-closed', architecture: 'modular-monolith', currentVersion: 'v2', supportedVersions: ['v1', 'v2'], checkedAt: time };
  if (fullPath === '/api/v1/organizations') return { organizations: [{ id: org, name: 'Sample workspace', role: 'owner', permissions: [], createdAt: time }] };
  if (endpoint === '/performance') return previewPerformance;
  if (endpoint === '/workforce') return workforce;
  if (endpoint === '/conversations') return { threads: conversationThreads };
  if (endpoint.startsWith('/conversations/')) {
    const id = endpoint.split('/')[2] as keyof typeof conversationMessages;
    const thread = conversationThreads.find((item) => item.id === id);
    if (!thread) throw new Error('Sample conversation not found.');
    return { thread, messages: conversationMessages[id] };
  }
  if (endpoint === '/workforce/templates') return { templates: [] };
  if (endpoint === '/jobs') return { jobs: jobs.jobs, summary: jobs.jobSummary, window: { truncated: false } };
  if (endpoint === '/work-items') return { workItems: jobs.workItems, summary: jobs.queueSummary, window: { truncated: false }, dispatch: jobs.dispatch };
  if (endpoint === '/results') return results;
  if (endpoint.startsWith('/results/')) return { result };
  if (endpoint === '/approvals') return { approvals: [approval] };
  if (endpoint === '/agents') return { agents: [{ id: agentId, organizationId: org, name: 'Research analyst identity', description: 'Sample agent identity', ownerUserId: 'preview-user', status: 'active', credential: { status: 'active', fingerprint: 'PREVIEW', version: 1, scopes: [], expiresAt: null, lastUsedAt: time }, createdAt: time, updatedAt: time }, { id: 'preview-agent-2', organizationId: org, name: 'Operations coordinator', description: 'Sample operations identity', ownerUserId: 'preview-user', status: 'active', credential: { status: 'active', fingerprint: 'PREVIEW', version: 1, scopes: [], expiresAt: null, lastUsedAt: time }, createdAt: time, updatedAt: time }] };
  if (/^\/agents\/[^/]+\/capabilities$/.test(endpoint)) { const identity = endpoint.split('/')[2]; const research = identity === agentId; const declaredScopes = research ? ['github.repository.read', 'browser.page.read'] : ['github.repository.write', 'browser.navigation.open']; return { profile: { agent: { id: identity, name: research ? 'Research analyst identity' : 'Operations coordinator', status: 'active' }, declaredScopes, activeScopes: declaredScopes, staleScopes: [], updatedAt: time, updatedBy: 'preview-user', authorization: { state: 'contextual', reason: 'A declaration remains subject to policy.' } } }; }
  if (endpoint === '/integrations') return { integrations: [{ id: 'preview-integration-1', organizationId: org, provider: 'github', displayName: 'Sample repository', resourceKey: 'sample/repository', webUrl: '', metadata: {}, supportedOperations: ['read', 'update'], status: 'connected', credential: { mode: 'none', configured: false, fingerprint: null }, health: { message: 'Connection healthy', lastCheckedAt: recent(0) }, createdBy: 'preview-user', createdAt: time, updatedAt: time }, { id: 'preview-integration-browser', organizationId: org, provider: 'browser', displayName: 'Sample website', resourceKey: 'https://example.com', webUrl: '', metadata: { allowedOrigins: ['https://example.com'] }, supportedOperations: ['page.observe', 'navigation.open', 'form.submit'], status: 'connected', credential: { mode: 'none', configured: false, fingerprint: null }, health: { message: 'Governed browser resource ready', lastCheckedAt: recent(0) }, createdBy: 'preview-user', createdAt: time, updatedAt: time }] };
  if (endpoint === '/integrations/security') return { security: { credentialVaultConfigured: false, encryption: 'Preview only', secretSource: 'None' } };
  if (endpoint === '/capabilities') return governanceCatalog;
  if (endpoint === '/policies') return { policies: governancePolicies };
  if (endpoint === '/actions') return { actions: previewActions };
  if (endpoint === '/risk') return governanceRisk;
  if (endpoint === '/incidents') return { incidents: [previewIncident], summary: { open: 0, acknowledged: 1, resolved: 0, critical: 0 }, window: { limit: 100, truncated: false } };
  if (endpoint.startsWith('/execution-controls/')) { const target = endpoint.split('/'); const isOrg = target[2] === 'organization'; return { control: { organizationId: org, targetType: isOrg ? 'organization' : target[2], targetId: isOrg ? org : target[3], targetName: isOrg ? 'Sample workspace' : 'Operations coordinator', state: isOrg ? 'active' : 'suspended', reason: isOrg ? '' : 'Unexpected external update under investigation', incidentId: isOrg ? null : previewIncident.id, changedBy: 'preview-user', changedAt: recent(1) } }; }
  if (endpoint === '/audit') { const matches = governanceEvents.filter(event => (!search.get('correlationId') || event.correlationId === search.get('correlationId')) && (!search.get('category') || event.category === search.get('category')) && (!search.get('severity') || event.severity === search.get('severity')) && (!search.get('q') || JSON.stringify(event).toLowerCase().includes(search.get('q')!.toLowerCase()))); return { ...governanceAudit, events: matches, summary: { ...governanceAudit.summary, visible: matches.length, bySeverity: { info: matches.filter(event => event.severity === 'info').length, warning: matches.filter(event => event.severity === 'warning').length, critical: matches.filter(event => event.severity === 'critical').length }, uniqueCorrelations: new Set(matches.map(event => event.correlationId).filter(Boolean)).size } }; }
  if (endpoint === '/runtime') return { runs: [previewRun], summary: { total: 1, planning: 0, running: 0, waitingApproval: 0, completed: 1, failed: 0 }, window: { limit: 100, truncated: false }, runtime: { autonomousCadence: 'every 5 minutes', maxAiRunsPerCron: 5, maxPlanSteps: 6, maxRetries: 2 } };
  if (endpoint === `/runs/${previewRun.id}`) return { run: previewRun, steps: previewSteps };
  if (endpoint === '/triggers') return { configs: [], history: [], summary: { configs: 0, scheduled: 0, apiEnabled: 0, eventDriven: 0, dependencyDriven: 0, history: { total: 0, queued: 0, skipped: 0, blocked: 0 } }, window: { configsTruncated: false, historyTruncated: false }, scheduler: { cadenceMinutes: 5, mode: 'queue_only' } };
  if (endpoint === '/supervision') return { escalations: [previewEscalation], rules: previewRules, summary: { total: 1, open: 1, acknowledged: 0, resolved: 0, critical: 0, assignedToMe: 1 }, window: { limit: 100, truncated: false } };
  if (endpoint === '/memory') return { memories: previewMemories, policy: { runRetentionDays: 30, workerRetentionDays: 90, organizationRetentionDays: 365, runtimeWriteMode: 'auto_run_only', longTermWriteMode: 'human_only', updatedBy: 'preview-user', updatedAt: time }, summary: { total: previewMemories.length, active: previewMemories.length, archived: 0 }, window: { limit: 100, truncated: false } };
  if (endpoint === '/artifacts') return { artifacts: previewArtifacts, summary: { total: previewArtifacts.length }, window: { limit: 100, truncated: false } };
  if (endpoint === '/product') return productFixture;
  if (endpoint === '/commercial') return commercialFixture;
  if (endpoint === '/ai/operations') return { configuration: { enabled: true, configured: true, provider: 'Sample provider', providerHealth: 'operational', coordinatorModel: 'Sample planner', visionModel: 'Sample vision' }, invocations: { sampleSize: 28, successes: 26, failures: 2, successRate: 92.9, averageLatencyMs: 850, errorsByCategory: {}, roleRouting: {}, window: { limit: 100, truncated: false } }, planner: { waitingCount: 0, waitingConfiguration: 0, waitingProvider: 0, window: { limit: 100, truncated: false } } };
  throw new Error(`No local preview fixture for ${fullPath}. No network request was made.`);
}

const productFixture = {
  workspace: { organizationId: org, name: 'Sample workspace', securityContactEmail: 'security@example.invalid', companyUrl: '', updatedBy: null, updatedAt: null },
  plans: [{ id: 'free', name: 'Free', priceMonthlyUsd: 0, agentLimit: 3, positioning: 'Explore with a small workforce.' }],
  subscription: { planId: 'free', status: 'active', billingProvider: 'none', enforcement: 'advisory', canCheckout: false },
  usage: { registeredAgents: 2, activeAgents: 2, connectedIntegrations: 1, enabledPolicies: 1, actions30d: 18, heldActions: 1, blocked30d: 3, failed30d: 2, activeIncidents: 0, agentLimitAdvisory: 3, agentLimitState: 'within_limit', windowTruncated: false },
  onboarding: { steps: [], complete: 3, total: 4, percent: 75 }, generatedAt: time,
};

const commercialFixture = {
  organization: { id: org, name: 'Sample workspace' },
  billing: { subscription: { planId: 'free', provider: 'none', verified: true, source: 'preview' }, adapter: { key: 'none', checkoutAvailable: false, providerConnected: false, verified: false }, plan: { id: 'free', name: 'Free', priceMonthlyUsd: 0, workerLimit: 3, positioning: 'A small starting workspace.' }, plans: [{ id: 'free', name: 'Free', priceMonthlyUsd: 0, workerLimit: 3, positioning: 'A small starting workspace.' }], enforcement: 'worker_limit_active' },
  entitlements: { workerLimit: 3, currentWorkers: 2, remainingWorkers: 1, features: {} },
  usage: { periodStart: time, workers: 2, jobsTotal: 1, jobsCreatedThisMonth: 1, runsThisMonth: 28, runsCompletedThisMonth: 21, runsFailedThisMonth: 2, accountingEventsThisMonth: 33, windowTruncated: false },
  onboarding: { steps: [{ id: 'workspace', label: 'Create a workspace', complete: true, required: true, destination: 'settings' }, { id: 'worker', label: 'Add a worker', complete: true, required: true, destination: 'workforce' }], complete: 2, total: 2, percent: 100, commercialReady: true },
  templates: { available: 0, applied: false }, invitations: { canInvite: false, recent: [], windowTruncated: false },
  production: { state: 'healthy', deadLetterWorkItems: 0, failedRunsThisMonth: 2, failedActionsThisMonth: 0, openEscalations: 1, criticalEscalations: 0, criticalIncidents: 0, windowTruncated: false, checkedAt: time }, generatedAt: time,
};
