import { getOrganizationForUser } from './organizations';
import { getApprovalEntry, listApprovalEntries, setApprovalDecision, setApprovalExecution, type ApprovalDecision, type ApprovalEntry, type ApprovalExecution, type ApprovalPolicySnapshot } from './approvalStore';
import { rejectHeldActionForApproval, resumeHeldActionAfterApproval } from './actionGateway';
import { appendAuditEvent } from './audit';
export class ApprovalDomainError extends Error { statusCode: number; constructor(message: string, statusCode = 400) { super(message); this.statusCode = statusCode; } }
async function requireAccess(userId: string, organizationId: string) { const organization = await getOrganizationForUser(userId, organizationId); if (!organization) throw new ApprovalDomainError('Organization not found or access denied.', 404); if (!organization.permissions.includes('approvals.review')) throw new ApprovalDomainError('Forbidden: your organization role does not grant approval review permission.', 403); return organization; }
function publicApproval(entry: ApprovalEntry) { return { id: entry.id, ...entry.record }; }
function parseDecision(value: unknown): ApprovalDecision { if (value !== 'approve' && value !== 'reject') throw new ApprovalDomainError('Approval decision must be approve or reject.'); return value; }
function parseNote(value: unknown) { const note = typeof value === 'string' ? value.trim() : ''; if (note.length > 500) throw new ApprovalDomainError('Approval note must be 500 characters or fewer.'); return note; }
function executionFor(action: Awaited<ReturnType<typeof rejectHeldActionForApproval>>, reauthorization: ApprovalPolicySnapshot | null): ApprovalExecution { const state = action.status === 'executed' ? 'executed' : action.status === 'blocked' ? 'blocked' : 'failed'; return { state, actionStatus: action.status, summary: action.result?.summary ?? action.error ?? action.policy.reason, completedAt: action.completedAt ?? new Date().toISOString(), reauthorization }; }
export async function listApprovalsForUser(userId: string, organizationId: string) { await requireAccess(userId, organizationId); return (await listApprovalEntries(organizationId)).map(publicApproval); }
export async function decideApprovalForUser(userId: string, organizationId: string, approvalId: string, rawDecision: unknown, rawNote: unknown) { await requireAccess(userId, organizationId); const decision = parseDecision(rawDecision); const note = parseNote(rawNote); let entry = await getApprovalEntry(organizationId, approvalId); if (!entry) throw new ApprovalDomainError('Approval request not found.', 404); const expected = decision === 'approve' ? 'approved' : 'rejected'; if (entry.record.status !== 'pending' && entry.record.status !== expected) throw new ApprovalDomainError('This approval has already received the opposite immutable decision.', 409); if (entry.record.status === 'pending') { const decided = await setApprovalDecision(organizationId, approvalId, decision, note, userId); if (!decided) throw new ApprovalDomainError('Approval request disappeared during decision persistence.', 409); entry = decided; } try { await appendAuditEvent({organizationId,eventType:decision==='approve'?'approval.approved':'approval.rejected',category:'approval',severity:decision==='approve'?'info':'warning',actor:{type:'human',id:userId,label:null},resource:{type:'approval',id:approvalId,name:entry.record.request.resourceName},correlationId:entry.record.correlationId,outcome:decision,summary:`Human reviewer ${decision==='approve'?'approved':'rejected'} ${entry.record.request.scope}.`,metadata:{actionId:entry.record.actionId,notePresent:Boolean(note)}}); if (decision === 'reject') { const action = await rejectHeldActionForApproval(organizationId, entry.record.actionId, approvalId); const updated = await setApprovalExecution(organizationId, approvalId, executionFor(action, null)); if (!updated) throw new Error('Approval execution state disappeared.'); return publicApproval(updated); } const resumed = await resumeHeldActionAfterApproval(organizationId, entry.record.actionId, approvalId); const updated = await setApprovalExecution(organizationId, approvalId, executionFor(resumed.action, resumed.reauthorization)); if (!updated) throw new Error('Approval execution state disappeared.'); return publicApproval(updated); } catch (caught) { try { await setApprovalExecution(organizationId, approvalId, { state: 'failed', actionStatus: null, summary: caught instanceof Error ? caught.message : 'Approval execution finalization failed.', completedAt: new Date().toISOString(), reauthorization: null }); } catch {} throw new ApprovalDomainError(`Approval decision was recorded but execution finalization failed: ${caught instanceof Error ? caught.message : 'unknown error'}`, 500); } }
export function serializeApprovalV2(approval: ReturnType<typeof publicApproval>) { return { identity: { id: approval.id, status: approval.status, requestedAt: approval.requestedAt }, action: { id: approval.actionId, agent: { id: approval.agentId, name: approval.agentName }, request: approval.request, policy: approval.policy }, decision: approval.decision, execution: approval.execution, notification: approval.notification, organizationId: approval.organizationId }; }
