import { db,storage } from '@appdeploy/sdk';
import { randomUUID } from 'node:crypto';
import { appendAuditEventBestEffort } from './audit';
import { getOrganizationForUser } from './organizations';
interface ArtifactRecord{organizationId:string;workerId:string;runId:string;stepId:string|null;name:string;kind:'run_result'|'step_output';contentType:string;storagePath:string;bytes:number;createdAt:string;correlationId:string}
export class ArtifactDomainError extends Error{statusCode:number;constructor(message:string,statusCode=400){super(message);this.statusCode=statusCode}}
function table(org:string){return`artifacts:${org}`}function pub(id:string,r:ArtifactRecord){return{id,...r}}async function access(userId:string,org:string){const o=await getOrganizationForUser(userId,org);if(!o)throw new ArtifactDomainError('Organization not found or access denied.',404);if(!o.permissions.includes('artifacts.read'))throw new ArtifactDomainError('Forbidden: your organization role does not grant artifact access.',403);return o}
export async function createRunArtifactForRuntime(org:string,workerId:string,runId:string,correlationId:string,payload:unknown){const content=JSON.stringify(payload,null,2),token=randomUUID(),path=`artifacts/${org}/${runId}/${token}.json`;const[written]=await storage.write([{path,content,contentType:'application/json'}]);if(!written)throw new ArtifactDomainError('Run artifact payload could not be stored.',500);const now=new Date().toISOString();const record:ArtifactRecord={organizationId:org,workerId,runId,stepId:null,name:`Run ${runId.slice(0,8)} result.json`,kind:'run_result',contentType:'application/json',storagePath:path,bytes:new TextEncoder().encode(content).length,createdAt:now,correlationId};const[id]=await db.add(table(org),[record]);if(!id){await storage.delete([path]);throw new ArtifactDomainError('Run artifact metadata could not be persisted.',500)}await appendAuditEventBestEffort({organizationId:org,eventType:'artifact.created',category:'workforce',severity:'info',actor:{type:'system',id:'managed-runtime',label:'Managed Runtime'},resource:{type:'artifact',id,name:record.name},correlationId,outcome:'created',summary:'Managed Runtime result artifact created.',metadata:{runId,workerId,bytes:record.bytes}});return pub(id,record)}
export async function listArtifactsForUser(userId:string,org:string){await access(userId,org);const{items,nextToken}=await db.list<ArtifactRecord>(table(org),{limit:150});const artifacts=items.map((i)=>{const{id,...r}=i;return pub(id,r as ArtifactRecord)}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return{artifacts,summary:{total:artifacts.length,runResults:artifacts.filter((a)=>a.kind==='run_result').length},window:{limit:150,truncated:Boolean(nextToken)}}}
export async function getArtifactUrlForUser(userId:string,org:string,id:string){await access(userId,org);const[r]=await db.get<ArtifactRecord>(table(org),[id]);if(!r)throw new ArtifactDomainError('Artifact not found.',404);const[result]=await storage.url([r.storagePath]);if(!result?.url)throw new ArtifactDomainError('Artifact URL could not be created.',500);return{artifact:pub(id,r),url:result.url,expiresInMinutes:15}}
export function serializeArtifactV2(a:ReturnType<typeof pub>){return{identity:{id:a.id,name:a.name,kind:a.kind,createdAt:a.createdAt},organizationId:a.organizationId,assignment:{workerId:a.workerId,runId:a.runId,stepId:a.stepId},storage:{contentType:a.contentType,bytes:a.bytes},trace:{correlationId:a.correlationId}}}
