import { db } from '@appdeploy/sdk';
export type CommercialPlanId='free'|'team'|'business'|'scale';
export interface CommercialPlan{id:CommercialPlanId;name:string;priceMonthlyUsd:number;workerLimit:number;positioning:string;entitlements:{workforceTemplates:boolean;organizationInvites:boolean;productionMonitoring:boolean;usageAccounting:boolean}}
export interface BillingSubscription{organizationId:string;planId:CommercialPlanId;status:'active';provider:'not_connected'|'external';providerReference:string|null;verified:boolean;source:'catalog_default'|'billing_adapter';updatedAt:string|null}
interface SubscriptionRecord{planId:CommercialPlanId;status:'active';provider:'external';providerReference:string;verified:boolean;updatedAt:string}
interface WorkerRecord{status:string}
interface UsageEventRecord{organizationId:string;kind:string;sourceId:string;occurredAt:string;metadata:Record<string,string|number|boolean|null>}
export class BillingDomainError extends Error{statusCode:number;constructor(message:string,statusCode=409){super(message);this.statusCode=statusCode}}
export const COMMERCIAL_PLANS:CommercialPlan[]=[{id:'free',name:'Free',priceMonthlyUsd:0,workerLimit:2,positioning:'Start a supervised AI workforce with core production controls.',entitlements:{workforceTemplates:true,organizationInvites:true,productionMonitoring:true,usageAccounting:true}},{id:'team',name:'Team',priceMonthlyUsd:49,workerLimit:5,positioning:'For small teams operating several managed AI workers.',entitlements:{workforceTemplates:true,organizationInvites:true,productionMonitoring:true,usageAccounting:true}},{id:'business',name:'Business',priceMonthlyUsd:149,workerLimit:20,positioning:'For growing organizations with broader workforce operations.',entitlements:{workforceTemplates:true,organizationInvites:true,productionMonitoring:true,usageAccounting:true}},{id:'scale',name:'Scale',priceMonthlyUsd:399,workerLimit:100,positioning:'For higher-volume AI workforce operations and larger teams.',entitlements:{workforceTemplates:true,organizationInvites:true,productionMonitoring:true,usageAccounting:true}}];
function subscriptionTable(org:string){return`billing_subscription:${org}`}function workersTable(org:string){return`workforce_workers:${org}`}function usageTable(org:string){return`commercial_usage:${org}`}
function planById(id:CommercialPlanId){return COMMERCIAL_PLANS.find(plan=>plan.id===id)!}
export interface BillingAdapter{key:string;readSubscription(organizationId:string):Promise<BillingSubscription>}
export const databaseBillingAdapter:BillingAdapter={key:'app_database_subscription',async readSubscription(organizationId){const{items,nextToken}=await db.list<SubscriptionRecord>(subscriptionTable(organizationId),{limit:2});if(nextToken||items.length>1)throw new BillingDomainError('Billing subscription state is ambiguous. Workforce expansion fails closed.',503);if(!items[0])return{organizationId,planId:'free',status:'active',provider:'not_connected',providerReference:null,verified:false,source:'catalog_default',updatedAt:null};const record=items[0];if(!COMMERCIAL_PLANS.some(plan=>plan.id===record.planId)||record.status!=='active'||record.provider!=='external'||!record.verified)throw new BillingDomainError('Billing subscription is not verified. Workforce expansion fails closed.',503);return{organizationId,planId:record.planId,status:'active',provider:'external',providerReference:record.providerReference,verified:true,source:'billing_adapter',updatedAt:record.updatedAt}}};
export async function getBillingSubscriptionForOrganization(organizationId:string){const subscription=await databaseBillingAdapter.readSubscription(organizationId);return{subscription,plan:planById(subscription.planId),adapter:{key:databaseBillingAdapter.key,checkoutAvailable:false,providerConnected:subscription.provider==='external',verified:subscription.verified}}}
export async function assertWorkerCapacityForOrganization(organizationId:string){const billing=await getBillingSubscriptionForOrganization(organizationId);const{items,nextToken}=await db.list<WorkerRecord>(workersTable(organizationId),{limit:101});if(nextToken)throw new BillingDomainError('Worker collection exceeds the entitlement verification window. Creation fails closed.',503);const current=items.filter(worker=>worker.status!=='archived').length;if(current>=billing.plan.workerLimit)throw new BillingDomainError(`${billing.plan.name} permits up to ${billing.plan.workerLimit} non-archived managed worker${billing.plan.workerLimit===1?'':'s'}. Archive a worker or move to a verified higher-capacity plan.`,409);return{current,limit:billing.plan.workerLimit,planId:billing.plan.id}}
export async function recordCommercialUsageEvent(organizationId:string,kind:string,sourceId:string,metadata:Record<string,string|number|boolean|null>={}){try{const record:UsageEventRecord={organizationId,kind:kind.slice(0,80),sourceId:sourceId.slice(0,160),occurredAt:new Date().toISOString(),metadata};const[id]=await db.add(usageTable(organizationId),[record]);if(!id)console.warn('Audoryn commercial usage event was not persisted');return Boolean(id)}catch(caught){console.warn('Audoryn commercial usage accounting failed',caught);return false}}
export async function listCommercialUsageEvents(organizationId:string){return db.list<UsageEventRecord>(usageTable(organizationId),{limit:200})}
