import { db } from '@appdeploy/sdk';
export type OrganizationRole = 'owner' | 'admin' | 'security_manager' | 'operator' | 'approver' | 'viewer';
export interface OrganizationRecord { name: string; createdBy: string; createdAt: string; }
export interface MembershipRecord { organizationId: string; userId: string; role: OrganizationRole; createdAt: string; }
const ROLE_PERMISSIONS: Record<OrganizationRole, string[]> = {
    owner: ['organizations.read','organizations.manage','memberships.manage','agents.read','agents.manage','workforce.read','workforce.manage','jobs.read','jobs.manage','jobs.run','supervision.read','performance.read','supervision.manage','memory.read','memory.manage','artifacts.read','results.read','results.export','integrations.read','integrations.manage','capabilities.read','capabilities.manage','policies.read','policies.manage','actions.read','actions.manage','approvals.review','audit.read','risk.read','incidents.read','incidents.manage'],
    admin: ['organizations.read','organizations.manage','memberships.manage','agents.read','agents.manage','workforce.read','workforce.manage','jobs.read','jobs.manage','jobs.run','supervision.read','performance.read','supervision.manage','memory.read','memory.manage','artifacts.read','results.read','results.export','integrations.read','integrations.manage','capabilities.read','capabilities.manage','policies.read','policies.manage','actions.read','actions.manage','approvals.review','audit.read','risk.read','incidents.read','incidents.manage'],
    security_manager: ['organizations.read','agents.read','agents.manage','workforce.read','jobs.read','supervision.read','performance.read','supervision.manage','memory.read','artifacts.read','results.read','results.export','integrations.read','integrations.manage','capabilities.read','capabilities.manage','policies.read','policies.manage','actions.read','actions.manage','approvals.review','audit.read','risk.read','incidents.read','incidents.manage'],
    operator: ['organizations.read','agents.read','agents.manage','workforce.read','workforce.manage','jobs.read','jobs.manage','jobs.run','supervision.read','performance.read','supervision.manage','memory.read','memory.manage','artifacts.read','results.read','results.export','integrations.read','capabilities.read','capabilities.manage','policies.read','actions.read','actions.manage','audit.read','risk.read','incidents.read','incidents.manage'],
    approver: ['organizations.read','agents.read','workforce.read','jobs.read','supervision.read','performance.read','memory.read','artifacts.read','results.read','results.export','integrations.read','capabilities.read','policies.read','actions.read','approvals.review','audit.read','risk.read','incidents.read'],
    viewer: ['organizations.read','agents.read','workforce.read','jobs.read','supervision.read','performance.read','memory.read','artifacts.read','results.read','integrations.read','capabilities.read','policies.read','actions.read','audit.read','risk.read','incidents.read'],
};
function membershipsTable(userId: string) { return `memberships:${userId}`; }
export async function createOrganization(userId: string, rawName: unknown) { const name = typeof rawName === 'string' ? rawName.trim() : ''; if (name.length < 2 || name.length > 80) throw new Error('Organization name must be between 2 and 80 characters.'); const createdAt = new Date().toISOString(); const [organizationId] = await db.add('organizations', [{ name, createdBy: userId, createdAt }]); if (!organizationId) throw new Error('Failed to create organization.'); const [membershipId] = await db.add(membershipsTable(userId), [{ organizationId, userId, role: 'owner', createdAt }]); if (!membershipId) { await db.delete('organizations', [organizationId]); throw new Error('Failed to create organization membership.'); } return { id: organizationId, name, role: 'owner' as const, permissions: ROLE_PERMISSIONS.owner, createdAt }; }
export async function listOrganizationsForUser(userId: string) { const { items: memberships } = await db.list<MembershipRecord>(membershipsTable(userId), { limit: 50 }); if (memberships.length === 0) return []; const organizationIds = memberships.map((membership) => membership.organizationId); const organizations = await db.get<OrganizationRecord>('organizations', organizationIds); return memberships.flatMap((membership, index) => { const organization = organizations[index]; if (!organization) return []; return [{ id: membership.organizationId, name: organization.name, role: membership.role, permissions: ROLE_PERMISSIONS[membership.role], createdAt: organization.createdAt }]; }); }
export async function getOrganizationForUser(userId: string, organizationId: string) { const organizations = await listOrganizationsForUser(userId); return organizations.find((organization) => organization.id === organizationId) ?? null; }
export function isInvitableOrganizationRole(value: unknown): value is Exclude<OrganizationRole,'owner'> { return value === 'admin' || value === 'security_manager' || value === 'operator' || value === 'approver' || value === 'viewer'; }
export async function addOrganizationMembershipFromInvite(userId:string,organizationId:string,role:Exclude<OrganizationRole,'owner'>){const[organization]=await db.get<OrganizationRecord>('organizations',[organizationId]);if(!organization)throw new Error('Invited organization does not exist.');const table=membershipsTable(userId);const{items,nextToken}=await db.list<MembershipRecord>(table,{limit:50});if(nextToken)throw new Error('Membership collection exceeds the safe invitation window.');const existing=items.find(item=>item.organizationId===organizationId);if(existing)return{id:organizationId,name:organization.name,role:existing.role,permissions:ROLE_PERMISSIONS[existing.role],createdAt:organization.createdAt};const createdAt=new Date().toISOString();const[id]=await db.add(table,[{organizationId,userId,role,createdAt}]);if(!id)throw new Error('Organization membership could not be created.');return{id:organizationId,name:organization.name,role,permissions:ROLE_PERMISSIONS[role],createdAt:organization.createdAt}}
export function serializeOrganizationsV1(organizations: Awaited<ReturnType<typeof listOrganizationsForUser>>) { return { organizations, count: organizations.length }; }
export function serializeOrganizationsV2(organizations: Awaited<ReturnType<typeof listOrganizationsForUser>>) { return { items: organizations.map(({ id, name, createdAt, role, permissions }) => ({ organization: { id, name, createdAt }, membership: { role, permissions } })), total: organizations.length }; }
