from typing import Protocol


class CodingRuntime(Protocol):
    async def create(self, *, metadata: dict[str, str], timeout: int) -> str: ...
    async def connect(self, sandbox_id: str, timeout: int): ...
    async def find(self, session_id: str) -> str | None: ...
    async def read(self, sandbox_id: str, path: str) -> str: ...
    async def write(self, sandbox_id: str, path: str, content: str | bytes) -> None: ...
    async def run(self, sandbox_id: str, command: str, background: bool = False): ...
    async def cancel(self, sandbox_id: str, process_id: int) -> None: ...
    async def command_result(self, sandbox_id: str, process_id: int) -> dict: ...
    async def pause(self, sandbox_id: str) -> None: ...
    async def delete(self, sandbox_id: str) -> None: ...
