import { useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, Clock3, Radio, Save, Send, ShieldCheck } from 'lucide-react';
import type { OrganizationAccess } from '../lib/identityApi';
import type { ApiVersion } from '../lib/systemApi';
import type { Job } from '../lib/jobsApi';
import type { ManagedWorker } from '../lib/workforceApi';
import { emitInternalEvent, loadTriggerWorkspace, saveTriggerConfig, type TriggerConfigInput, type TriggerHistory, type TriggerWorkspace, type Weekday } from '../lib/schedulerApi';

const DAYS: Weekday[] = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
const EMPTY: TriggerWorkspace = { configs: [], history: [], summary: { configs: 0, scheduled: 0, apiEnabled: 0, eventDriven: 0, dependencyDriven: 0, history: { total: 0, queued: 0, skipped: 0, blocked: 0 } }, window: { configsTruncated: false, historyTruncated: false }, scheduler: { cadenceMinutes: 5, mode: 'queue_only' } };
function base(timezone = 'UTC'): TriggerConfigInput { return { schedule: { enabled: false, cadence: 'daily', timezone, localTime: '09:00', weekdays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'], intervalMinutes: 60, missedRunPolicy: 'queue_once', outsideWorkingHoursPolicy: 'next_open' }, apiEnabled: false, internalEventKeys: [], dependencyJobIds: [] }; }
interface SchedulerPanelProps { organization: OrganizationAccess; apiVersion: ApiVersion; jobs: Job[]; workers: ManagedWorker[]; onWorkChanged: () => void; }
export default function SchedulerPanel({ organization, apiVersion, jobs, workers, onWorkChanged }: SchedulerPanelProps) {
  const [data, setData] = useState<TriggerWorkspace>(EMPTY); const [selectedId, setSelectedId] = useState(jobs.find((job) => job.status !== 'archived')?.id ?? ''); const [form, setForm] = useState<TriggerConfigInput>(base()); const [eventKey, setEventKey] = useState(''); const [eventPayload, setEventPayload] = useState('{}'); const [sourceJobId, setSourceJobId] = useState(''); const [sourceWorkItemId, setSourceWorkItemId] = useState('qa-source-item'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const canManage = organization.permissions.includes('jobs.manage'); const canRun = organization.permissions.includes('jobs.run'); const selected = jobs.find((job) => job.id === selectedId); const worker = selected ? workers.find((item) => item.id === selected.workerId) : null; const config = useMemo(() => data.configs.find((item) => item.jobId === selectedId), [data.configs, selectedId]); const availableJobs = jobs.filter((job) => job.status !== 'archived'); const apiTriggerPath = selected ? `POST /api/v1/runtime/organizations/${organization.id}/jobs/${selected.id}/trigger` : ''; const history = selectedId ? data.history.filter((item) => item.jobId === selectedId).slice(0, 12) : data.history.slice(0, 12);
  async function refresh() { setLoading(true); setError(null); try { setData(await loadTriggerWorkspace(apiVersion, organization.id)); } catch (caught) { setError(errorText(caught)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [apiVersion, organization.id]); useEffect(() => { if (!selectedId) { const first = jobs.find((job) => job.status !== 'archived'); if (first) setSelectedId(first.id); } }, [jobs, selectedId]); useEffect(() => { if (config) setForm({ schedule: { enabled: config.schedule.enabled, cadence: config.schedule.cadence, timezone: config.schedule.timezone, localTime: config.schedule.localTime, weekdays: config.schedule.weekdays, intervalMinutes: config.schedule.intervalMinutes, missedRunPolicy: config.schedule.missedRunPolicy, outsideWorkingHoursPolicy: config.schedule.outsideWorkingHoursPolicy }, apiEnabled: config.apiEnabled, internalEventKeys: config.internalEventKeys, dependencyJobIds: config.dependencyJobIds }); else if (worker) setForm(base(worker.workingHours.timezone)); }, [config?.id, config?.revision, selectedId, worker?.id]);
  function toggleDay(day: Weekday) { setForm((current) => ({ ...current, schedule: { ...current.schedule, weekdays: current.schedule.weekdays.includes(day) ? current.schedule.weekdays.filter((item) => item !== day) : [...current.schedule.weekdays, day] } })); }
  function toggleDependency(jobId: string) { setForm((current) => ({ ...current, dependencyJobIds: current.dependencyJobIds.includes(jobId) ? current.dependencyJobIds.filter((item) => item !== jobId) : [...current.dependencyJobIds, jobId] })); }
  function setCadence(value: string) { if (value === 'daily' || value === 'weekly' || value === 'interval') setForm((current) => ({ ...current, schedule: { ...current.schedule, cadence: value } })); }
  function setMissedRun(value: string) { if (value === 'skip' || value === 'queue_once') setForm((current) => ({ ...current, schedule: { ...current.schedule, missedRunPolicy: value } })); }
  function setWorkingHoursPolicy(value: string) { if (value === 'queue_anyway' || value === 'next_open') setForm((current) => ({ ...current, schedule: { ...current.schedule, outsideWorkingHoursPolicy: value } })); }
  async function save() { if (!selected) return; setSaving(true); setError(null); try { await saveTriggerConfig(apiVersion, organization.id, selected.id, form); setMessage('Trigger configuration saved. Scheduler remains queue-only.'); await refresh(); } catch (caught) { setError(errorText(caught)); } finally { setSaving(false); } }
  async function emit() { setSaving(true); setError(null); try { let payload: Record<string, unknown> | null = null; if (eventPayload.trim()) { const parsed = JSON.parse(eventPayload); if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) throw new Error('Event payload must be a JSON object.'); payload = parsed as Record<string, unknown>; } const result = await emitInternalEvent(apiVersion, organization.id, { key: eventKey, payload, sourceJobId: eventKey === 'job.completed' ? sourceJobId || null : null, sourceWorkItemId: eventKey === 'job.completed' ? sourceWorkItemId || null : null }); setMessage(`Event accepted: ${result.queued} queued, ${result.blocked} blocked.`); await refresh(); onWorkChanged(); } catch (caught) { setError(errorText(caught)); } finally { setSaving(false); } }
  return <div className="scheduler-panel">
    {error && <div className="inline-error">{error}</div>}{message && <div className="product-success">{message}</div>}
    <div className="scheduler-summary"><Summary label="Scheduled Jobs" value={data.summary.scheduled}/><Summary label="Event-driven" value={data.summary.eventDriven}/><Summary label="API-enabled" value={data.summary.apiEnabled}/><Summary label="Trigger history" value={data.summary.history.total}/></div>
    <div className="scheduler-grid">
      <section className="trigger-card">
        <div className="section-title"><div><p className="panel-kicker">TRIGGER CONFIGURATION</p><h2>When should this Job enter the queue?</h2></div><CalendarClock size={18}/></div>
        <label>Job<select value={selectedId} onChange={(event)=>setSelectedId(event.target.value)}>{availableJobs.map((job)=><option key={job.id} value={job.id}>{job.name} · {job.status}</option>)}</select></label>
        {!selected && <p className="trigger-help">Create a non-archived Job before configuring triggers.</p>}
        {selected && <div className="trigger-config-body">
          <div className="trigger-boundary"><ShieldCheck size={16}/><span>Triggers create Work Items only. F16 will own Run creation and execution.</span></div>
          <label className="toggle-line"><input type="checkbox" checked={form.schedule.enabled} onChange={(event)=>setForm({...form,schedule:{...form.schedule,enabled:event.target.checked}})}/><span>Enable recurring schedule</span></label>
          {form.schedule.enabled && <div className="schedule-fields">
            <label>Cadence<select value={form.schedule.cadence} onChange={(event)=>setCadence(event.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="interval">Interval</option></select></label>
            {form.schedule.cadence==='interval' && <label>Every minutes<input type="number" min={5} max={10080} value={form.schedule.intervalMinutes} onChange={(event)=>setForm({...form,schedule:{...form.schedule,intervalMinutes:Number(event.target.value)}})}/></label>}
            {form.schedule.cadence!=='interval' && <label>Timezone<input value={form.schedule.timezone} onChange={(event)=>setForm({...form,schedule:{...form.schedule,timezone:event.target.value}})}/></label>}
            {form.schedule.cadence!=='interval' && <label>Local time<input type="time" value={form.schedule.localTime} onChange={(event)=>setForm({...form,schedule:{...form.schedule,localTime:event.target.value}})}/></label>}
            {form.schedule.cadence==='weekly' && <div className="weekday-picker">{DAYS.map((day)=><button type="button" className={form.schedule.weekdays.includes(day)?'active':''} key={day} onClick={()=>toggleDay(day)}>{day.slice(0,3)}</button>)}</div>}
            <label>Missed run<select value={form.schedule.missedRunPolicy} onChange={(event)=>setMissedRun(event.target.value)}><option value="queue_once">Queue one catch-up</option><option value="skip">Skip stale occurrence</option></select></label>
            <label>Outside working hours<select value={form.schedule.outsideWorkingHoursPolicy} onChange={(event)=>setWorkingHoursPolicy(event.target.value)}><option value="next_open">Queue for next working opening</option><option value="queue_anyway">Queue at scheduled time</option></select></label>
            {config?.schedule.nextDueAt && <div className="next-run"><Clock3 size={14}/><span>Next due: {new Date(config.schedule.nextDueAt).toLocaleString()}</span></div>}
          </div>}
          <label className="toggle-line"><input type="checkbox" checked={form.apiEnabled} onChange={(event)=>setForm({...form,apiEnabled:event.target.checked})}/><span>Enable authenticated API trigger</span></label>
          {form.apiEnabled && <div className="api-trigger-note"><code>{apiTriggerPath}</code><p>Authenticate with the bound Agent Identity credential. Optional body: idempotencyKey + payload.</p></div>}
          <label>Internal event keys<textarea placeholder="One event key per line" value={form.internalEventKeys.join('\n')} onChange={(event)=>setForm({...form,internalEventKeys:event.target.value.split('\n').map((item)=>item.trim()).filter(Boolean)})}/></label>
          <fieldset><legend>Dependency Jobs</legend><small>Queue this Job when a selected upstream Job later emits a job.completed event.</small><div className="dependency-list">{availableJobs.filter((job)=>job.id!==selected.id).map((job)=><label key={job.id}><input type="checkbox" checked={form.dependencyJobIds.includes(job.id)} onChange={()=>toggleDependency(job.id)}/><span>{job.name}</span></label>)}</div></fieldset>
          {canManage && <button className="primary-button" disabled={saving} onClick={()=>void save()}><Save size={14}/> Save triggers</button>}
        </div>}
      </section>
      <section className="trigger-card">
        <div className="section-title"><div><p className="panel-kicker">INTERNAL EVENT INGESTION</p><h2>Emit an event</h2></div><Radio size={18}/></div>
        <p className="trigger-help">This is the authenticated internal-event surface. job.completed is also the dependency hook F16 will call automatically.</p>
        <label>Event key<input value={eventKey} placeholder="support.ticket.created" onChange={(event)=>setEventKey(event.target.value)}/></label>
        {eventKey==='job.completed' && <div className="schedule-fields"><label>Source Job<select value={sourceJobId} onChange={(event)=>setSourceJobId(event.target.value)}><option value="">Select upstream Job</option>{availableJobs.map((job)=><option key={job.id} value={job.id}>{job.name}</option>)}</select></label><label>Source Work Item<input value={sourceWorkItemId} onChange={(event)=>setSourceWorkItemId(event.target.value)}/></label></div>}
        <label>Payload JSON<textarea value={eventPayload} onChange={(event)=>setEventPayload(event.target.value)}/></label>
        {canRun && <button className="secondary-button" disabled={saving||!eventKey.trim()||(eventKey==='job.completed'&&!sourceJobId)} onClick={()=>void emit()}><Send size={14}/> Emit event</button>}
        <History loading={loading} history={history} selected={Boolean(selected)}/>
      </section>
    </div>
    {(data.window.configsTruncated||data.window.historyTruncated) && <p className="audit-window-note">The bounded trigger read window is truncated; Audoryn is not inventing totals beyond the scanned window.</p>}
  </div>;
}
function Summary({label,value}:{label:string;value:number}){return <div><span>{label}</span><strong>{value}</strong></div>}
function History({loading,history,selected}:{loading:boolean;history:TriggerHistory[];selected:boolean}){return <div className="trigger-history"><div className="section-title"><div><p className="panel-kicker">TRIGGER HISTORY</p><h3>{selected?'Selected Job':'Recent triggers'}</h3></div><CheckCircle2 size={17}/></div>{loading?<p>Loading trigger history…</p>:history.length===0?<p>No trigger attempts recorded yet.</p>:history.map((item)=><div className="trigger-history-row" key={item.id}><span className={`trigger-outcome ${item.outcome}`}>{item.outcome}</span><div><strong>{item.triggerType.replace('_',' ')}</strong><span>{new Date(item.occurredAt).toLocaleString()} · {item.key??'no key'}</span>{item.reason&&<small>{item.reason}</small>}</div></div>)}</div>}
function errorText(value:unknown){const data=value as{response?:{data?:{error?:string}};message?:string};return data.response?.data?.error||data.message||'Trigger request failed.'}

