import test from 'node:test';
import assert from 'node:assert/strict';
import {jsPDF} from 'jspdf';
import * as XLSX from 'xlsx';

test('patched PDF library preserves result-export pagination, typography and footer APIs', () => {
 const doc=new jsPDF({unit:'pt',format:'a4'});
 const width=doc.internal.pageSize.getWidth(),height=doc.internal.pageSize.getHeight();
 doc.setFont('helvetica','bold');doc.setFontSize(18);
 doc.text('Audoryn result',54,58);
 doc.addPage();doc.setFont('helvetica','normal');doc.setFontSize(10);
 doc.text(doc.splitTextToSize('Evidence and a source URL: https://example.org/result',width-108),54,58);
 assert.equal(doc.getNumberOfPages(),2);
 for(let page=1;page<=2;page++){
  doc.setPage(page);doc.setFontSize(8);doc.setTextColor(90);
  doc.text(`Generated by Audoryn · ${page}/2`,54,height-28);
 }
 const output=Buffer.from(doc.output('arraybuffer'));
 assert.ok(output.length>1000);assert.equal(output.subarray(0,5).toString(),'%PDF-');
 assert.match(output.toString('latin1'),/\/Count 2/);
});

test('maintained spreadsheet library preserves multiple tables, exact text and numeric cells', () => {
 const workbook=XLSX.utils.book_new();
 const rows=[['Name','Count','Notes'],['Audoryn',3,'=literal text'],['Résumé',0,'Line one\nLine two']];
 XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet(rows),'Table 1');
 XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['Status'],['Completed']]),'Table 2');
 const output=XLSX.write(workbook,{bookType:'xlsx',type:'array'});
 const read=XLSX.read(output,{type:'array'});
 assert.deepEqual(read.SheetNames,['Table 1','Table 2']);
 assert.deepEqual(XLSX.utils.sheet_to_json(read.Sheets['Table 1'],{header:1}),rows);
 assert.equal(read.Sheets['Table 1'].C2.f,undefined,'Text beginning with = stays text');
});
