import { usePublicText, usePublicCollection } from './content/ContentContext';
import { useEffect } from 'react';
import { ArrowRight, Check, ChevronDown, ShieldCheck } from 'lucide-react';
import './pricing-showcase.css';



export default function PricingShowcase({ onNavigate }: { onNavigate: (route: 'signup' | 'product') => void }) {
  const text = usePublicText('PricingShowcase');
const plans = usePublicCollection('PricingShowcase','plans', [
  { name: text('field-free-3b6a9f4a90', "Free"), price: '0', limit: '3', audience: text('field-start-with-a-small-supervised-workforce-eb3b31e4dd', "Start with a small supervised workforce."), state: text('field-available-now-6f71ae8a74', "AVAILABLE NOW") },
  { name: text('field-team-5ca46d5345', "Team"), price: '49', limit: '15', audience: text('field-coordinate-a-growing-workforce-across-a-team-a1898a8837', "Coordinate a growing workforce across a team."), state: text('field-catalog-plan-c048e33c68', "CATALOG PLAN") },
  { name: text('field-business-4fd3cfee69', "Business"), price: '199', limit: '75', audience: text('field-run-more-workers-across-recurring-company-wor-feca14c121', "Run more workers across recurring company work."), state: text('field-catalog-plan-c048e33c68', "CATALOG PLAN") },
  { name: text('field-scale-12b011323d', "Scale"), price: '499', limit: '250', audience: text('field-plan-for-a-larger-governed-workforce-0b5424bc75', "Plan for a larger governed workforce."), state: text('field-catalog-plan-c048e33c68', "CATALOG PLAN") },
] as const);

  useEffect(() => {
    const root = document.querySelector<HTMLElement>('.pricing-page');
    if (!root || window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) return;
    const observer = new IntersectionObserver((entries) => { entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }); }, { threshold: .08, rootMargin: '0px 0px -5% 0px' });
    const items = root.querySelectorAll<HTMLElement>('[data-pricing-reveal]');
    items.forEach((item) => observer.observe(item));
    root.classList.add('pricing-motion-ready');
    return () => { observer.disconnect(); root.classList.remove('pricing-motion-ready'); };
  }, []);

  return <div className='pricing-page'>
    <section className='pricing-hero'><div className='public-container pricing-hero-inner'><div><p className='pricing-kicker'>{text('copy-audoryn-pricing-fbffa9ae4d', "AUDORYN / PRICING")}</p><h1>{text('copy-start-free-5caa4b71a6', "Start free.")}<br/>{text('copy-grow-with-the-work-b5a0cf9f27', "Grow with the work.")}</h1></div><div className='pricing-hero-side'><p>{text('copy-choose-capacity-for-the-number-of-ai-workers-6141777273', "Choose capacity for the number of AI workers you need. The same authority and oversight model applies at every size.")}</p><span><i/> {text('copy--free-workspace-available-now-e2ae9cdb0b', " FREE WORKSPACE AVAILABLE NOW")}</span></div></div></section>

    <section className='pricing-plans public-container' data-pricing-reveal><div className='pricing-section-head'><div><p className='pricing-kicker'>{text('copy-plan-catalog-da684ba55b', "PLAN CATALOG")}</p><h2>{text('copy-capacity-at-a-glance-75145d1496', "Capacity at a glance.")}</h2></div><p>{text('copy-monthly-usd-catalog-prices-paid-upgrades-are-898a084f44', "Monthly USD catalog prices. Paid upgrades are not yet available for self-service purchase.")}</p></div><div className='pricing-plan-grid'>{plans.map((plan, index) => <article className={plan.availability === 'free_signup' ? 'is-free' : ''} key={plan.id}><div className='pricing-plan-top'><span>0{index + 1} / {plan.name.toUpperCase()}</span><span>{plan.state}</span></div><h3>{plan.name}</h3><p className='pricing-plan-audience'>{plan.audience}</p><div className='pricing-plan-price'><strong>{plan.currency==='USD'?text('copy--0d3e336d0b', "$"):new Intl.NumberFormat('en',{style:'currency',currency:plan.currency||'USD',currencyDisplay:'narrowSymbol'}).formatToParts(0).find(part=>part.type==='currency')?.value}{plan.price}</strong><span>{plan.billingPeriod==='year'?'/ year':text('copy--month-7cadcf741a', "/ month")}<br/>{text('copy-catalog-027d78805d', "catalog")}</span></div><div className='pricing-plan-limit'><span>{text('copy-managed-workers-7c63b92fd6', "MANAGED WORKERS")}</span><strong>{text('copy-up-to-12f147e3dd', "Up to ")}{plan.limit}</strong></div>{plan.availability === 'free_signup' ? <button type='button' onClick={() => onNavigate('signup')}>{text('copy-get-started-free-efd16b962f', "Get started free ")}<ArrowRight size={15}/></button> : plan.availability==='contact'&&plan.contactDestination?<a className='pricing-plan-unavailable' href={plan.contactDestination}>Contact</a>: <span className='pricing-plan-unavailable'>{text('copy-paid-activation-not-yet-open-31aeb992da', "Paid activation not yet open")}</span>}</article>)}</div><p className='pricing-catalog-note'>{text('copy-the-backend-currently-defaults-organizations-e61500d587', "The backend currently defaults organizations to Free. The paid plan figures above describe the catalog; they are not a live checkout offer.")}</p></section>

    <section className='pricing-common' data-pricing-reveal><div className='public-container pricing-common-inner'><div><p className='pricing-kicker'>{text('copy-the-same-control-model-6ed6dc03c2', "THE SAME CONTROL MODEL")}</p><h2>{text('copy-capacity-changes-c7ae494b52', "Capacity changes.")}<br/>{text('copy-authority-does-not-956b660059', "Authority does not.")}</h2></div><div className='pricing-common-list'><div><ShieldCheck size={19} strokeWidth={1.5}/><span>{text('copy-capability-and-policy-checks-on-external-acti-689805952a', "Capability and policy checks on external actions")}</span></div><div><Check size={19} strokeWidth={1.5}/><span>{text('copy-human-approval-when-the-rule-requires-it-03def9c3e0', "Human approval when the rule requires it")}</span></div><div><Check size={19} strokeWidth={1.5}/><span>{text('copy-connected-tools-and-inspectable-results-dc4e201148', "Connected tools and inspectable results")}</span></div></div></div></section>

    <section className='pricing-questions public-container' data-pricing-reveal><div className='pricing-questions-heading'><p className='pricing-kicker'>{text('copy-common-questions-476ad41718', "COMMON QUESTIONS")}</p><h2>{text('copy-before-you-begin-cec82f2702', "Before you begin.")}</h2></div><div className='pricing-faq'><details><summary>{text('copy-can-i-start-without-a-paid-plan-8aadb71d54', "Can I start without a paid plan?")}<ChevronDown size={16}/></summary><p>{text('copy-yes-new-organizations-start-on-free-which-sup-a67aac9fd5', "Yes. New organizations start on Free, which supports up to three managed workers.")}</p></details><details><summary>{text('copy-can-i-purchase-team-business-or-scale-today-796d30cbe7', "Can I purchase Team, Business or Scale today?")}<ChevronDown size={16}/></summary><p>{text('copy-no-the-paid-plans-are-in-the-product-catalog-db059d00b8', "No. The paid plans are in the product catalog, but a billing provider and checkout are not connected yet.")}</p></details><details><summary>{text('copy-does-a-larger-plan-give-workers-more-authorit-914ce9004a', "Does a larger plan give workers more authority?")}<ChevronDown size={16}/></summary><p>{text('copy-no-plan-capacity-is-separate-from-identity-ca-feaede7521', "No. Plan capacity is separate from identity, capability, risk, policy, approvals and incident controls.")}</p></details></div></section>

    <section className='pricing-close'><div className='public-container'><p className='pricing-kicker'>{text('copy-start-with-audoryn-9a63f271f1', "START WITH AUDORYN")}</p><h2>{text('copy-put-the-first-worker-to-work-b32942fc71', "Put the first worker to work.")}</h2><p>{text('copy-begin-on-free-and-define-a-clear-role-job-and-72e5ccedf6', "Begin on Free and define a clear role, job and supervisor.")}</p><div><button type='button' onClick={() => onNavigate('signup')}>{text('copy-get-started-8942f59ca0', "Get started ")}<ArrowRight size={16}/></button><button type='button' onClick={() => onNavigate('product')}>{text('copy-explore-the-product-92a1b1f60e', "Explore the product ")}<ArrowRight size={16}/></button></div></div></section>
  </div>;
}
