import { usePublicText, usePublicImage, usePublicCollection, usePublicContent } from './content/ContentContext';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, Check, CirclePause, Clock3, FileText, GitBranch, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import humanOversightFallback from './assets/human-oversight.webp';
import './product-showcase.css';
import baselineDemo from '../../content-seed/demonstration-baseline.json';
import {payloadOf} from './content/contract';
import type {Demonstration} from './content/publicContent.generated';

type Destination = 'signup' | 'security';
type View = 'Workforce' | 'Jobs' | 'Approvals';

const views: View[] = ['Workforce', 'Jobs', 'Approvals'];

function WorkspacePreview() {
  const text = usePublicText('ProductShowcase');

  const [view, setView] = useState<View>('Workforce');
  const bundle=usePublicContent();
  const demo:Demonstration=bundle.page?payloadOf(bundle.page).demonstration as Demonstration:baselineDemo;
  const tab=(item:View)=>text('tab-'+item.toLowerCase(),item);

  return <div className='product-workspace' aria-label={text('copy-illustrative-audoryn-workspace-preview-ad166b1b02', "Illustrative Audoryn workspace preview")}>
    <div className='product-workspace-bar'><span className='product-workspace-brand'><i /> {text('copy--audoryn-65b4c2d381', " AUDORYN ")}<em>/</em> {text('copy--workspace-20052e5553', " WORKSPACE")}</span><span className='product-workspace-org'>{demo.organization_label+' '}<span className='product-workspace-avatar'>{text('copy-n-2f45d4f8fb', "N")}</span></span></div>
    <div className='product-workspace-body'>
      <div className='product-workspace-rail'><span className='product-rail-title'>{text('copy-operate-e40e94fdf5', "OPERATE")}</span>{views.map((item) => <button type='button' key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)} aria-pressed={view === item}>{tab(item)}</button>)}<span className='product-rail-title product-rail-manage'>{text('copy-manage-17012392a1', "MANAGE")}</span><span>{text('copy-integrations-45e338a51c', "Integrations")}</span><span>{text('copy-policies-6ee683e406', "Policies")}</span><span>{text('copy-audit-58136373aa', "Audit")}</span></div>
      <div className='product-workspace-main' key={view}>
        <div className='product-workspace-context'><span>{text('copy-workspace-f0906cfdad', "WORKSPACE / ")}{tab(view).toUpperCase()}</span><span>{text('copy-example-view-bbd48542e9', "EXAMPLE VIEW")}</span></div>
        {view === 'Workforce' && <><div className='product-preview-heading'><div><p>{text('copy-workforce-85e515065b', "Workforce")}</p><h3>{text('copy-people-and-ai-one-clear-structure-263cb54823', "People and AI, one clear structure.")}</h3></div><span className='product-preview-count'>{text('copy-02-workers-cb0ef86d72', "02 WORKERS")}</span></div><div className='product-preview-table'><div className='product-preview-th'><span>{text('copy-worker-d4da0c8687', "WORKER")}</span><span>{text('copy-role-318be8d028', "ROLE")}</span><span>{text('copy-supervisor-25e20c1bd5', "SUPERVISOR")}</span><span>{text('copy-state-a8a6917e5b', "STATE")}</span></div>{(demo.workers||[]).map(worker=><div key={worker.id}><span className='product-preview-person'><b>{worker.id===baselineDemo.workers[0].id?'AR':worker.id===baselineDemo.workers[1].id?'OC':worker.label.split(' ').map(word=>word[0]).join('').slice(0,2)}</b><strong>{worker.label}<small>{worker.summary}</small></strong></span><span>{worker.category}</span><span>{worker.detail}</span><span className='product-state'><i />{' '+worker.status_label}</span></div>)}</div><div className='product-preview-foot'><span><ShieldCheck size={14} /> {text('copy--separate-agent-identity-666a92263e', " Separate agent identity")}</span><span><Clock3 size={14} /> {text('copy--defined-working-hours-999fcdef13', " Defined working hours")}</span></div></>}
        {view === 'Jobs' && <><div className='product-preview-heading'><div><p>{text('copy-jobs-4f95b87691', "Jobs")}</p><h3>{text('copy-work-with-a-visible-state-bb1828c59f', "Work with a visible state.")}</h3></div><span className='product-preview-count'>{text('copy-03-work-items-384b09ff72', "03 WORK ITEMS")}</span></div><div className='product-job-list'>{(demo.jobs||[]).map(job=>{const baseIndex=baselineDemo.jobs.findIndex(item=>item.id===job.id);const Icon=[FileText,GitBranch,Mail][baseIndex]||FileText;return <div key={job.id}><span className='product-job-icon'><Icon size={17}/></span><strong>{job.label}<small>{job.summary}</small></strong><em className={'product-job-status '+(['complete','running',''][baseIndex]||'')}>{job.status_label}</em></div>;})}</div><div className='product-preview-foot'><span><Check size={14} /> {text('copy--objective-and-completion-criteria-cb54f4df66', " Objective and completion criteria")}</span><span>{text('copy-run-history-retained-f053d23c47', "Run history retained")}</span></div></>}
        {view === 'Approvals' && <><div className='product-preview-heading'><div><p>{text('copy-approvals-5de0b61ae3', "Approvals")}</p><h3>{text('copy-judgment-returns-to-a-person-d180bf5e84', "Judgment returns to a person.")}</h3></div><span className='product-preview-count'>{text('copy-01-needs-review-8a9da18688', "01 NEEDS REVIEW")}</span></div>{(demo.approvals||[]).map(approval=><div className='product-approval-preview' key={approval.id}><span className='product-approval-flag'><CirclePause size={15}/>{' '+approval.status_label}</span><h4>{approval.label}</h4><p>{approval.description}</p><div><span>{text('copy-requested-by-09dcdd07c7','REQUESTED BY ')}<strong>{approval.summary}</strong></span><span>{text('copy-reviewer-25e5eb9c62','REVIEWER ')}<strong>{approval.detail}</strong></span></div></div>)}<div className='product-preview-foot'><span><ShieldCheck size={14} /> {text('copy--policy-and-risk-checked-again-before-resume-431b09394a', " Policy and risk checked again before resume")}</span></div></>}
      </div>
    </div>
    <div className='product-workspace-caption'>{demo.disclosure}</div>
  </div>;
}



export default function ProductShowcase({ onNavigate }: { onNavigate: (route: Destination) => void }) {
  const text = usePublicText('ProductShowcase');
  const humanOversightImage = usePublicImage('human-oversight',humanOversightFallback);
const integrations = usePublicCollection('ProductShowcase','integrations', [
  { mark: 'GH', name: text('field-github-74f8c3b1d0', "GitHub"), use: 'Repository and issue workflows' },
  { mark: 'M', name: text('field-gmail-d3bddbea07', "Gmail"), use: 'Mailbox context and recent messages' },
  { mark: 'D', name: text('field-google-drive-2f0fbdbe71', "Google Drive"), use: 'Documents and files' },
  { mark: 'S', name: text('field-slack-a342ac5f54', "Slack"), use: 'Team conversations' },
  { mark: 'C', name: text('field-google-calendar-4a161453ac', "Google Calendar"), use: 'Calendar context' },
  { mark: '↗', name: text('field-governed-browser-f97bc0ca4d', "Governed Browser"), use: 'Approved site interactions' },
]);

  useEffect(() => {
    const root = document.querySelector<HTMLElement>('.product-page');
    if (!root || window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) return;
    const items = root.querySelectorAll<HTMLElement>('[data-product-reveal]');
    const observer = new IntersectionObserver((entries) => { entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }); }, { threshold: .08, rootMargin: '0px 0px -5% 0px' });
    items.forEach((item) => observer.observe(item));
    root.classList.add('product-motion-ready');
    return () => { observer.disconnect(); root.classList.remove('product-motion-ready'); };
  }, []);

  return <div className='product-page'>
    <section className='product-hero'>
      <div className='public-container product-hero-inner'>
        <div className='product-hero-copy'><p className='product-eyebrow'>{text('copy-audoryn-product-2d9994e3dd', "AUDORYN / PRODUCT")}</p><h1>{text('copy-give-work-to-ai-e3bf010963', "Give work to AI.")}<br/><span>{text('copy-keep-people-in-control-d7956073c0', "Keep people in control.")}</span></h1><p>{text('copy-build-a-supervised-ai-workforce-for-the-work-bbf36cd5f3', "Build a supervised AI workforce for the work your organization already does. Define the role, assign the job, connect the tools and see every important decision.")}</p><div className='product-hero-actions'><button className='public-cta' onClick={() => onNavigate('signup')}>{text('copy-get-started-c3d0e3b774', "Get started ")}<ArrowRight size={15}/></button><a href={text('copy--product-workforce-c67b46f873', "#product-workforce")}>{text('copy-explore-the-product-ddfb9814b1', "Explore the product ")}<ArrowDown size={15}/></a></div><div className='product-hero-meta'><span>{text('copy-workers-4f0fb03fd9', "WORKERS")}</span><i/><span>{text('copy-jobs-f102d297fb', "JOBS")}</span><i/><span>{text('copy-supervision-5a3701a338', "SUPERVISION")}</span><i/><span>{text('copy-integrations-a1bc6fcf6d', "INTEGRATIONS")}</span></div></div>
        <div className='product-hero-visual'><div className='product-visual-halo'/><WorkspacePreview/></div>
      </div>
    </section>

    <section className='product-statement public-container' data-product-reveal><span>{text('copy-01-the-workforce-3ba12fc10b', "01 / THE WORKFORCE")}</span><p>{text('copy-a-useful-ai-worker-needs-more-than-a-prompt-a-47cea51301', "A useful AI worker needs more than a prompt. Audoryn gives it a role, a job and a place in your organization.")}</p></section>

    <section id='product-workforce' className='product-feature public-container' data-product-reveal><div className='product-feature-copy'><p className='product-eyebrow'>{text('copy-workforce-01-100937443f', "WORKFORCE / 01")}</p><h2>{text('copy-make-the-work-legible-before-it-begins-b9ac15c0f7', "Make the work legible before it begins.")}</h2><p>{text('copy-create-workers-with-responsibilities-working-5ad7147bc3', "Create workers with responsibilities, working hours and a named human supervisor. Give each job an objective, requirements and a clear definition of done.")}</p><div className='product-feature-notes'><span><Check size={15}/> {text('copy--named-roles-and-supervisors-f9d20e4ec3', " Named roles and supervisors")}</span><span><Check size={15}/> {text('copy--scheduled-and-triggered-jobs-e43c684d7f', " Scheduled and triggered jobs")}</span><span><Check size={15}/> {text('copy--a-separate-security-identity-for-every-worke-c441feb5c4', " A separate security identity for every worker")}</span></div></div><div className='product-job-visual' aria-label={text('copy-illustration-of-a-worker-and-a-defined-job-7bfdcf91f5', "Illustration of a worker and a defined job")}><div className='product-job-visual-top'><span>{text('copy-worker-profile-c9ef3e02d9', "WORKER PROFILE")}</span><span>01 / 02</span></div><div className='product-worker-identity'><span>{text('copy-ar-0598909a56', "AR")}</span><div><small>{text('copy-research-insights-674be78ca5', "RESEARCH / INSIGHTS")}</small><strong>{text('copy-research-analyst-e8e2a20356', "Research analyst")}</strong><em>{text('copy-supervised-by-ada-m-ad11396cc4', "Supervised by Ada M.")}</em></div></div><div className='product-worker-divider'/><div className='product-worker-job'><span>{text('copy-assigned-job-4443ac2806', "ASSIGNED JOB")}</span><strong>{text('copy-compile-weekly-research-brief-c79edfa62e', "Compile weekly research brief")}</strong><p>{text('copy-gather-relevant-sources-summarize-findings-an-b03204ccf4', "Gather relevant sources, summarize findings and deliver a structured brief.")}</p><div><span>{text('copy-mon-09-00-69e036170d', "MON · 09:00")}</span><span>{text('copy-review-before-delivery-aa837859dc', "REVIEW BEFORE DELIVERY")}</span></div></div><div className='product-job-visual-bottom'><span><i/> {text('copy--active-worker-1183fa48df', " ACTIVE WORKER")}</span><span>{text('copy-role-job-queue-6767ecc3f1', "ROLE → JOB → QUEUE")}</span></div></div></section>

    <section className='product-runtime' data-product-reveal><div className='public-container product-runtime-inner'><div className='product-runtime-copy'><p className='product-eyebrow'>{text('copy-runtime-02-fbf21a690c', "RUNTIME / 02")}</p><h2>{text('copy-from-assignment-to-a-traceable-result-ce16590421', "From assignment to a traceable result.")}</h2><p>{text('copy-jobs-enter-a-durable-queue-runs-have-steps-ch-018a38e91e', "Jobs enter a durable queue. Runs have steps, checkpoints, retries and a recorded outcome, so work can be followed instead of guessed at.")}</p></div><div className='product-run-panel'><div className='product-run-head'><span>{text('copy-run-weekly-research-brief-089fa7de0e', "RUN / WEEKLY RESEARCH BRIEF")}</span><span><i/> {text('copy--in-progress-90231989a0', " IN PROGRESS")}</span></div><ol><li className='done'><span>01</span><div><strong>{text('copy-read-assigned-context-7b1b561f61', "Read assigned context")}</strong><small>{text('copy-sources-and-job-requirements-loaded-010599d190', "Sources and job requirements loaded")}</small></div><Check size={15}/></li><li className='done'><span>02</span><div><strong>{text('copy-plan-the-work-4fe1ff535d', "Plan the work")}</strong><small>{text('copy-bounded-ai-planning-ab01550f57', "Bounded AI planning")}</small></div><Check size={15}/></li><li className='current'><span>03</span><div><strong>{text('copy-collect-observations-870b4d7a8c', "Collect observations")}</strong><small>{text('copy-connected-tools-governed-access-234cd0ece6', "Connected tools, governed access")}</small></div><span className='product-run-spinner'/></li><li><span>04</span><div><strong>{text('copy-assess-completion-db5eeda954', "Assess completion")}</strong><small>{text('copy-compare-result-with-the-job-criteria-b6903f6e6e', "Compare result with the job criteria")}</small></div></li></ol><div className='product-run-tail'><span>{text('copy-work-item-8f24-a3137c908d', "WORK ITEM / 8F24")}</span><span>{text('copy-example-run-acd7415fe2', "EXAMPLE RUN")}</span></div></div></div></section>

    <section className='product-intelligence public-container' data-product-reveal><div className='product-intelligence-title'><p className='product-eyebrow'>{text('copy-ai-03-d6be6ed883', "AI / 03")}</p><h2>{text('copy-intelligence-where-it-helps-8036cafd5e', "Intelligence where it helps.")}<br/>{text('copy-authority-where-it-belongs-be2a5cbf09', "Authority where it belongs.")}</h2><p>{text('copy-audoryn-routes-planning-and-visual-understand-0da09bb08d', "Audoryn routes planning and visual understanding through shared NVIDIA API models. The model can reason about the task; Audoryn still controls what may happen outside it.")}</p></div><div className='product-model-rows'><div><span className='product-model-number'>01</span><span className='product-model-icon'><Sparkles size={21}/></span><div><h3>{text('copy-planning-and-coordination-0dfdfd7ce7', "Planning and coordination")}</h3><p>{text('copy-nvidia-nemotron-supports-bounded-planning-and-9f805e070c', "NVIDIA Nemotron supports bounded planning and internal reasoning for managed runs.")}</p></div><span className='product-model-label'>{text('copy-nemotron-61fbdf37e5', "NEMOTRON")}</span></div><div><span className='product-model-number'>02</span><span className='product-model-icon'><FileText size={21}/></span><div><h3>{text('copy-visual-understanding-c3b9322bdb', "Visual understanding")}</h3><p>{text('copy-nvidia-ising-analyzes-uploaded-images-and-ret-43f8b74530', "NVIDIA Ising analyzes uploaded images and returns relevant findings for the task.")}</p></div><span className='product-model-label'>{text('copy-ising-4993b766a9', "ISING")}</span></div></div><p className='product-model-note'>{text('copy-models-provide-analysis-not-credentials-or-pe-905a7af239', "Models provide analysis, not credentials or permission to use connected tools.")}</p></section>

    <section className='product-supervision' data-product-reveal><div className='product-supervision-image'><img src={humanOversightImage} onError={event=>{if(event.currentTarget.dataset.fallbackUsed)return;event.currentTarget.dataset.fallbackUsed='true';event.currentTarget.src=humanOversightFallback;}} alt={text('alt-colleagues-reviewing-a-decision-together-442edd1dff', "Colleagues reviewing a decision together")} loading='lazy'/></div><div className='product-supervision-copy'><div><p className='product-eyebrow'>{text('copy-supervision-04-b6c8cb4600', "SUPERVISION / 04")}</p><h2>{text('copy-the-moments-that-matter-come-back-to-a-person-a3733493fb', "The moments that matter come back to a person.")}</h2><p>{text('copy-policy-can-allow-deny-or-hold-an-action-for-r-2b1f81eb3a', "Policy can allow, deny or hold an action for review. A held run waits while a human sees the context, makes a decision and leaves an auditable record.")}</p><button type='button' onClick={() => onNavigate('security')}>{text('copy-explore-the-security-model-b951f6a2f5', "Explore the security model ")}<ArrowRight size={15}/></button></div><div className='product-decision-line'><span>{text('copy-request-d9b7ed51aa', "REQUEST")}</span><i/><span>{text('copy-policy-cdccb8e1f4', "POLICY")}</span><i/><span>{text('copy-human-review-00c5fd2e56', "HUMAN REVIEW")}</span><i/><span>{text('copy-recorded-outcome-7ae945a0c4', "RECORDED OUTCOME")}</span></div></div></section>

    <section id='product-integrations' className='product-integrations public-container' data-product-reveal><div className='product-integrations-heading'><div><p className='product-eyebrow'>{text('copy-integrations-05-d8da836819', "INTEGRATIONS / 05")}</p><h2>{text('copy-work-across-the-tools-c10fa11022', "Work across the tools")}<br/>{text('copy-your-team-already-uses-e8bdd46aac', "your team already uses.")}</h2></div><p>{text('copy-connect-workplace-systems-to-audoryn-s-govern-f23b455117', "Connect workplace systems to Audoryn’s governed action gateway. Each provider exposes defined capabilities; a connection alone never gives a worker permission to act.")}</p></div><div className='product-integration-grid'>{integrations.map((item) => <div key={item.name}><span className='product-integration-mark'>{item.mark}</span><strong>{item.name}</strong><p>{item.use}</p><ArrowRight size={15} aria-hidden='true'/></div>)}</div><p className='product-integrations-note'>{text('copy-available-operations-depend-on-provider-confi-c2b7467db5', "Available operations depend on provider configuration, declared capabilities and policy.")}</p></section>

    <section className='product-close'><div className='public-container'><p className='product-eyebrow'>{text('copy-start-with-a-defined-worker-e738a97808', "START WITH A DEFINED WORKER")}</p><h2>{text('copy-bring-ai-into-the-workflow-6737b9724e', "Bring AI into the workflow.")}<br/>{text('copy-keep-the-organization-in-charge-ac6020cb52', "Keep the organization in charge.")}</h2><p>{text('copy-start-small-make-authority-explicit-and-grow-19ab5d7dc0', "Start small, make authority explicit and grow the workforce as the work proves useful.")}</p><button className='public-cta' onClick={() => onNavigate('signup')}>{text('copy-get-started-c3d0e3b774', "Get started ")}<ArrowRight size={16}/></button></div></section>
  </div>;
}
